//! Emission: turn discovered declarations into the generated `.rs`.
//!
//! The output is a plain module body meant to be `include!`d by whichever crate
//! owns the JIT/AOT symbol installation. It names no Rust module paths — every
//! address comes from an `unsafe extern "C"` declaration with an explicit
//! `#[link_name]` — so it depends only on the symbols being LINKED, not on them
//! being `pub`-reachable. Its single dependency is `rts-abi`, for the shared
//! [`rts_abi::table::SymbolEntry`] type.
//!
//! ## Determinism
//!
//! Rendering is a pure function of the declaration set: entries are sorted by
//! symbol name (ties broken by source path), the internal extern identifiers are
//! assigned `__rts_sym_<i>` AFTER sorting, and nothing timestamped or
//! path-absolute is written. Two bakes of unchanged sources are byte-identical,
//! which is what makes `--check` a usable CI drift guard.

use std::collections::BTreeMap;

use anyhow::{Result, bail};

use crate::scan::Declaration;

/// Sort + validate the declarations, then render the generated file.
pub fn render(mut decls: Vec<Declaration>) -> Result<String> {
    decls.sort_by(|a, b| a.symbol.cmp(&b.symbol).then(a.origin.cmp(&b.origin)));
    decls.dedup();
    check_duplicates(&decls)?;

    let mut s = String::with_capacity(decls.len() * 200);
    header(&mut s, decls.len());
    externs(&mut s, &decls);
    jit_table(&mut s, &decls);
    aot_table(&mut s, &decls);
    Ok(s)
}

/// A symbol may appear twice ONLY when every occurrence is `#[cfg]`-gated —
/// the platform-alternative shape (`posix` vs `win32`). Two ungated definitions
/// of one name are a real collision: the linker would pick one and the table
/// would silently install the wrong address.
fn check_duplicates(decls: &[Declaration]) -> Result<()> {
    let mut groups: BTreeMap<&str, Vec<&Declaration>> = BTreeMap::new();
    for d in decls {
        groups.entry(d.symbol.as_str()).or_default().push(d);
    }
    for (name, group) in groups {
        if group.len() > 1 && group.iter().any(|d| d.cfgs.is_empty()) {
            let where_ = group
                .iter()
                .map(|d| d.origin.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            bail!("symbol `{name}` is declared more than once without a #[cfg] gate: {where_}");
        }
    }
    Ok(())
}

fn header(s: &mut String, n: usize) {
    s.push_str(
        "// @generated by `rts-symbol-baker` — DO NOT EDIT BY HAND.\n\
         //\n\
         // Regenerate with `cargo run -p rts-symbol-baker`; verify with\n\
         // `cargo run -p rts-symbol-baker -- --check` (CI runs the latter).\n\
         //\n\
         // ORDERING INVARIANT: entries are in strictly ascending byte order of the\n\
         // symbol name, so lookup is a binary search and every scope (`__rtsa_`,\n\
         // `__rtsm_node_fs_`, …) is ONE contiguous range. See `rts_abi::table`.\n\
         //\n",
    );
    s.push_str(&format!("// {n} symbols.\n\n"));
}

fn externs(s: &mut String, decls: &[Declaration]) {
    s.push_str(
        "// Addresses are taken through the LINKER name, not a Rust module path: that\n\
         // reaches every `#[no_mangle]` symbol regardless of Rust visibility, and makes\n\
         // a missing one a link error instead of a runtime crash.\n\
         unsafe extern \"C\" {\n",
    );
    for (i, d) in decls.iter().enumerate() {
        for cfg in &d.cfgs {
            s.push_str(&format!("    {cfg}\n"));
        }
        s.push_str(&format!(
            "    #[link_name = \"{}\"]\n    fn __rts_sym_{i}();\n",
            d.symbol
        ));
    }
    s.push_str("}\n\n");
}

fn jit_table(s: &mut String, decls: &[Declaration]) {
    s.push_str(
        "/// Every RTS symbol with its address, for `JITBuilder::symbol`.\n\
         ///\n\
         /// Sorted ascending by name; `#[cfg]`-gated rows drop out on platforms where\n\
         /// they do not exist, which preserves the order of the rows that remain.\n",
    );
    s.push_str(&format!(
        "pub fn symbols() -> ::std::vec::Vec<::rts_abi::table::SymbolEntry> {{\n    \
         let mut out = ::std::vec::Vec::with_capacity({});\n",
        decls.len()
    ));
    for (i, d) in decls.iter().enumerate() {
        push_row(
            s,
            &d.cfgs,
            &format!(
                "out.push(::rts_abi::table::SymbolEntry {{ name: \"{}\", ptr: __rts_sym_{i} as *const u8 }});",
                d.symbol
            ),
        );
    }
    s.push_str("    out\n}\n\n");
}

fn aot_table(s: &mut String, decls: &[Declaration]) {
    s.push_str(
        "/// The same symbols as names only, for the AOT object module's declaration\n\
         /// list. Same order, same `#[cfg]` gating — the two paths cannot diverge.\n",
    );
    s.push_str(&format!(
        "pub fn aot_symbols() -> ::std::vec::Vec<&'static str> {{\n    \
         let mut out = ::std::vec::Vec::with_capacity({});\n",
        decls.len()
    ));
    for d in decls {
        push_row(s, &d.cfgs, &format!("out.push(\"{}\");", d.symbol));
    }
    s.push_str("    out\n}\n");
}

/// One `#[cfg]`-gated statement. A `#[cfg]` cannot sit on an array element, so
/// the table is built by `push` — which is also why the invariant is "sorted",
/// not "indexed by position".
fn push_row(s: &mut String, cfgs: &[String], stmt: &str) {
    if cfgs.is_empty() {
        s.push_str(&format!("    {stmt}\n"));
        return;
    }
    for cfg in cfgs {
        s.push_str(&format!("    {cfg}\n"));
    }
    s.push_str(&format!("    {{\n        {stmt}\n    }}\n"));
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decl(symbol: &str, cfgs: &[&str]) -> Declaration {
        Declaration {
            symbol: symbol.into(),
            cfgs: cfgs.iter().map(|c| c.to_string()).collect(),
            origin: "crates/x/src/a.rs".into(),
        }
    }

    #[test]
    fn output_is_sorted_and_deterministic() {
        let input = vec![decl("__rtsn_b", &[]), decl("__rtsa_a", &[])];
        let out = render(input.clone()).unwrap();
        assert!(out.find("__rtsa_a").unwrap() < out.find("__rtsn_b").unwrap());
        // Re-rendering a permutation gives the identical file.
        let mut rev = input;
        rev.reverse();
        assert_eq!(out, render(rev).unwrap());
    }

    #[test]
    fn ungated_duplicate_is_an_error() {
        let d = vec![decl("__rtsn_x", &[]), Declaration {
            origin: "crates/y/src/b.rs".into(),
            ..decl("__rtsn_x", &[])
        }];
        assert!(render(d).is_err());
    }

    #[test]
    fn cfg_gated_duplicate_is_allowed_and_gated_in_output() {
        let d = vec![
            decl("__rtsn_x", &["#[cfg(unix)]"]),
            Declaration {
                origin: "crates/y/src/b.rs".into(),
                ..decl("__rtsn_x", &["#[cfg(windows)]"])
            },
        ];
        let out = render(d).unwrap();
        assert!(out.contains("#[cfg(unix)]"));
        assert!(out.contains("#[cfg(windows)]"));
    }
}
