//! `crypto` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "random_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_BYTES",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Fills ptr..ptr+len with CSPRNG bytes. 0 ok, -1 err.",
        ts_signature: "random_bytes(ptr: number, len: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "random_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_I64",
        args: &[],
        returns: AbiType::I64,
        doc: "Cryptographically secure i64.",
        ts_signature: "random_i64(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "random_buffer",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_BUFFER",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Allocates a buffer of `len` random bytes. Handle 0 on error.",
        ts_signature: "random_buffer(len: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "random_uuid",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_UUID",
        args: &[],
        returns: AbiType::Handle,
        doc: "Generates a UUID v4 (random) in canonical 8-4-4-4-12 hex format. RFC 4122.",
        ts_signature: "random_uuid(): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hash_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HASH_NEW",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Creates a streaming hasher (sha256 only v0). Returns 0 on unsupported alg.",
        ts_signature: "hash_new(alg: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hash_update_str",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HASH_UPDATE_STR",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Appends UTF-8 bytes to the hasher.",
        ts_signature: "hash_update_str(h: number, data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hash_update_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HASH_UPDATE_BYTES",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Appends raw bytes (ptr+len) to the hasher.",
        ts_signature: "hash_update_bytes(h: number, ptr: number, len: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hash_digest_hex",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HASH_DIGEST_HEX",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Finalizes and returns the digest as a hex string handle.",
        ts_signature: "hash_digest_hex(h: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hash_digest_base64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HASH_DIGEST_BASE64",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Finalizes and returns the digest as a base64 string handle.",
        ts_signature: "hash_digest_base64(h: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "sha256_str",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_SHA256_STR",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "SHA-256 of a UTF-8 string, returned as a 64-char hex string handle.",
        ts_signature: "sha256_str(s: string): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "sha256_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_SHA256_BYTES",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "SHA-256 of a raw memory region. Use with buffer.ptr(h).",
        ts_signature: "sha256_bytes(ptr: number, len: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hex_encode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HEX_ENCODE",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Lowercase hex of a memory region.",
        ts_signature: "hex_encode(ptr: number, len: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "hex_decode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HEX_DECODE",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Decodes hex into a buffer handle. 0 on malformed input.",
        ts_signature: "hex_decode(s: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "base64_encode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_BASE64_ENCODE",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Base64 (RFC 4648 padded) of a memory region.",
        ts_signature: "base64_encode(ptr: number, len: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "base64_decode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_BASE64_DECODE",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Decodes base64 into a buffer handle. 0 on malformed input.",
        ts_signature: "base64_decode(s: string): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "crypto",
    doc: "Cryptographic primitives: SHA-256, CSPRNG, hex, base64.",
    members: MEMBERS,
};
