//! `#[rtse::constant]` — expose a Rust `const` as a Registry CONSTANT.
//!
//! ```ignore
//! #[rtse::constant(global)]                     pub const EXEMPLO: &str = "";
//! #[rtse::constant(module = "math")]            pub const PI: f64 = 3.141592653589793;
//! #[rtse::constant(global = "Number", value = "MAX_SAFE_INTEGER")]
//! pub const MAX_SAFE: f64 = 9007199254740991.0;
//! ```
//!
//! The `const` itself is emitted UNCHANGED (it stays ordinary Rust). Next to it
//! the macro emits:
//!
//! 1. an `extern "C"` zero-argument GETTER carrying the derived linker symbol —
//!    that is what `MemberKind::Constant` is in this engine: `ptr` is a
//!    `fn() -> ty` the codegen calls where the name appears without parens;
//! 2. the `SymbolDesc` const (same `_ABI` naming as `#[rtse::abi]`), so a codegen
//!    consumer gets name + ABI shape at ITS compile time;
//! 3. `pub fn <name>_member() -> Member`, the Registry entry, which the owning
//!    declaration pushes through the existing `.member(...)` escape hatch:
//!    `e.module("rts", "math").member(pi_member())…`, `e.class("Number")
//!    .member(max_safe_member())…`, `e.global().member(exemplo_member())`.
//!
//! It deliberately does NOT self-register into a module: `ModuleBuilder::done`
//! REPLACES the module at its key, so a constant that built its own one-member
//! module would silently wipe the rest of that module. Handing back a `Member`
//! keeps one declaration site per module, which is also what makes the constant
//! obey the module's own aliases and privacy.
//!
//! Scope arguments are `#[rtse::abi]`'s, parsed by the same `abi::scope`
//! (`module = "…"` / `global` / `global = "Class"` / `native` / `abi`, plus
//! `value = "…"`), so a constant and a function in the same scope cannot drift
//! onto different naming rules.
//!
//! # Supported types
//!
//! `&'static str` (allocated into the string pool on read, returned as a
//! `Handle`), `f64`, `i64`, `i32`, `bool`. Anything else is a compile error: the
//! getter has to return ONE ABI slot, and a composite (`&[T]`, a struct, a tuple)
//! has no such form — expose it as a `#[rtse::abi]` function returning a handle.

use proc_macro::TokenStream;
use quote::{format_ident, quote};

use crate::abi::scope::{AbiArgs, symbol_for};
use crate::naming::{abi_const_name, to_camel};
use crate::types::scalar;

pub(crate) fn expand(a: TokenStream, item: TokenStream) -> TokenStream {
    let item = syn::parse_macro_input!(item as syn::ItemConst);
    let args = match syn::parse::<AbiArgs>(a) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error().into(),
    };

    let rust_ident = item.ident.clone();
    let js_name = match &args.0 {
        rts_abi::scope::Naming::Scoped {
            value: Some(v), ..
        } => v.clone(),
        _ => js_name_of(&rust_ident.to_string()),
    };
    let sym = symbol_for(&args.0, &js_name);

    // The reader: a zero-arg getter over the const. A string is materialized into
    // the string pool per read (a `&str` cannot cross as one ABI slot); a scalar
    // is returned directly, `bool` widened to the `i64` the ABI uses for `Bool`.
    let (abi, ext_ty, ts, read) = if is_str(&item.ty) {
        (
            quote!(::rts_engine::AbiType::Handle),
            quote!(u64),
            "string",
            quote!(::rts_engine::heap::handles::alloc_entry(
                ::rts_engine::heap::handles::Entry::String(#rust_ident.to_string().into_bytes())
            )),
        )
    } else if let Some((abi, ext_ty, ts)) = scalar(&item.ty) {
        let is_bool = matches!(&*item.ty, syn::Type::Path(p) if p.path.is_ident("bool"));
        let read = if is_bool {
            quote!(#rust_ident as i64)
        } else {
            quote!(#rust_ident)
        };
        (abi, ext_ty, ts, read)
    } else {
        return syn::Error::new_spanned(
            &item.ty,
            "#[rtse::constant]: no ABI spelling for this type — a constant must be \
             `&'static str`, `f64`, `i64`, `i32` or `bool`. A composite value has no \
             single-slot getter form; expose it as an `#[rtse::abi]` function returning \
             a `Handle`.",
        )
        .to_compile_error()
        .into();
    };

    let extern_ident = proc_macro2::Ident::new(&sym, rust_ident.span());
    let const_ident = proc_macro2::Ident::new(&abi_const_name(&sym), rust_ident.span());
    let member_fn = format_ident!("{}_member", rust_ident.to_string().to_lowercase());
    let desc_doc = format!("ABI descriptor for `{sym}` (generated by `#[rtse::constant]`).");
    let member_doc =
        format!("Registry entry for the constant `{js_name}` — pass it to `.member(...)`.");
    let ts_sig = format!("{js_name}: {ts}");
    let doc = extract_doc(&item.attrs);

    quote! {
        #item

        #[unsafe(no_mangle)]
        pub extern "C" fn #extern_ident() -> #ext_ty { #read }

        #[doc = #desc_doc]
        pub const #const_ident: ::rts_engine::abi::SymbolDesc =
            ::rts_engine::abi::SymbolDesc {
                name: #sym,
                params: &[],
                ret: #abi,
            };

        #[doc = #member_doc]
        pub fn #member_fn() -> ::rts_engine::Member {
            ::rts_engine::Member {
                name: #js_name.into(),
                kind: ::rts_engine::MemberKind::Constant,
                sig: ::rts_engine::Sig::new(::std::vec::Vec::new(), #abi),
                symbol: #sym.into(),
                fn_ptr: ::rts_engine::FnPtr(#extern_ident as *const u8),
                flags: ::rts_engine::MemberFlags::READONLY,
                aliases: ::std::vec::Vec::new(),
                variadic: false,
                ts_signature: #ts_sig.into(),
                doc: #doc.into(),
                pure: true,
                emit: ::core::option::Option::None,
                ret_class: ::core::option::Option::None,
            }
        }
    }
    .into()
}

/// The JS name derived from a Rust const ident when no `value = "…"` is given.
///
/// A SCREAMING_SNAKE ident (the Rust convention for a `const`, and so the common
/// case) is lower-cased first, then camel-cased: `EXEMPLO` → `exemplo`,
/// `MAX_SAFE_INTEGER` → `maxSafeInteger`. Any other spelling is only camel-cased,
/// so a deliberately-cased ident survives.
///
/// FAILURE CASE, stated because it is not hypothetical: a JS constant that IS
/// spelled in screaming snake — `Number.MAX_SAFE_INTEGER`, `Number.EPSILON` —
/// cannot be derived, because the derivation cannot tell "Rust convention to be
/// undone" from "the JS spelling itself". Those MUST pass `value =
/// "MAX_SAFE_INTEGER"` explicitly. Deriving in the other direction would break
/// the far more common `EXEMPLO` → `exemplo` case the owner asked for.
fn js_name_of(ident: &str) -> String {
    let screaming = ident
        .chars()
        .all(|c| !c.is_ascii_alphabetic() || c.is_ascii_uppercase());
    if screaming {
        to_camel(&ident.to_ascii_lowercase())
    } else {
        to_camel(ident)
    }
}

/// Is the type `&str` / `&'static str`?
fn is_str(ty: &syn::Type) -> bool {
    let syn::Type::Reference(r) = ty else {
        return false;
    };
    matches!(&*r.elem, syn::Type::Path(p) if p.path.is_ident("str"))
}

/// Harvest `///` docs into `Member.doc` (the `.d.ts` generator emits it).
fn extract_doc(attrs: &[syn::Attribute]) -> String {
    let mut lines: Vec<String> = Vec::new();
    for a in attrs {
        if !a.path().is_ident("doc") {
            continue;
        }
        if let syn::Meta::NameValue(nv) = &a.meta {
            if let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(s),
                ..
            }) = &nv.value
            {
                let v = s.value();
                lines.push(v.strip_prefix(' ').unwrap_or(&v).to_string());
            }
        }
    }
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::js_name_of;

    #[test]
    fn screaming_snake_becomes_camel() {
        assert_eq!(js_name_of("EXEMPLO"), "exemplo");
        assert_eq!(js_name_of("MAX_SAFE_INTEGER"), "maxSafeInteger");
    }

    #[test]
    fn mixed_case_is_only_camelized() {
        assert_eq!(js_name_of("read_only"), "readOnly");
        assert_eq!(js_name_of("Infinity"), "Infinity");
    }
}
