//! `Date` global class — ABI registration as `GlobalClassSpec`.

use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── Static methods ────────────────────────────────────────────────────────
    NamespaceMember {
        name: "now",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_DATE_NOW_MS",
        args: &[],
        returns: AbiType::I64,
        doc: "Returns the current time as milliseconds since Unix epoch (UTC).",
        ts_signature: "now(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "parse",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_DATE_FROM_ISO",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Parses an ISO 8601 string to ms since epoch. Returns NaN sentinel on failure.",
        ts_signature: "parse(dateString: string): number",
        intrinsic: None,
        pure: true,
    },
    // (#220) Date.UTC(year, month, day?, hour?, min?, sec?, ms?) — ms since epoch UTC.
    NamespaceMember {
        name: "UTC",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_DATE_FROM_PARTS",
        args: &[
            AbiType::I64, AbiType::I64, AbiType::I64,
            AbiType::I64, AbiType::I64, AbiType::I64, AbiType::I64,
        ],
        returns: AbiType::I64,
        doc: "Date.UTC(year, month, day?, hour?, min?, sec?, ms?) — ms since epoch.",
        ts_signature: "UTC(year: number, month: number, day?: number, hour?: number, min?: number, sec?: number, ms?: number): number",
        intrinsic: None,
        pure: true,
    },
    // ── Constructors (distinguished by arity) ─────────────────────────────────
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DATE_NEW_NOW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Creates a Date representing the current instant.",
        ts_signature: "new Date(): Date",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_from_ms",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DATE_NEW_FROM_MS",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Creates a Date from milliseconds since Unix epoch.",
        ts_signature: "new Date(value: number): Date",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_from_iso",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DATE_NEW_FROM_ISO",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Creates a Date from an ISO 8601 string.",
        ts_signature: "new Date(dateString: string): Date",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods ──────────────────────────────────────────────────────
    NamespaceMember {
        name: "getTime",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_TIME",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Returns ms since epoch.",
        ts_signature: "getTime(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "valueOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_VALUE_OF",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Same as getTime().",
        ts_signature: "valueOf(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getFullYear",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_FULL_YEAR",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Full year (UTC).",
        ts_signature: "getFullYear(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getMonth",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_MONTH",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Month 0-indexed (UTC). Jan=0, Dec=11.",
        ts_signature: "getMonth(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getDate",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_DATE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Day of month 1-31 (UTC).",
        ts_signature: "getDate(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getDay",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_DAY",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Day of week 0-6 (UTC). Sunday=0.",
        ts_signature: "getDay(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getHours",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_HOURS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Hour 0-23 (UTC).",
        ts_signature: "getHours(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getMinutes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_MINUTES",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Minute 0-59 (UTC).",
        ts_signature: "getMinutes(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getSeconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_SECONDS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Second 0-59 (UTC).",
        ts_signature: "getSeconds(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getMilliseconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_MILLISECONDS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Millisecond 0-999 (UTC).",
        ts_signature: "getMilliseconds(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toISOString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_ISO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "ISO 8601 UTC string.",
        ts_signature: "toISOString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "String representation (ISO 8601 UTC).",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLocaleDateString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_LOCALE_DATE_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Locale-agnostic date string (same as toISOString in v0).",
        ts_signature: "toLocaleDateString(): string",
        intrinsic: None,
        pure: true,
    },
    // (#220) UTC getters — alias dos getters principais (RTS sempre UTC).
    NamespaceMember {
        name: "getUTCFullYear",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_FULL_YEAR",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Full year in UTC.",
        ts_signature: "getUTCFullYear(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCMonth",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_MONTH",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Month 0-11 in UTC.",
        ts_signature: "getUTCMonth(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCDate",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_DATE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Day of month 1-31 in UTC.",
        ts_signature: "getUTCDate(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCDay",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_DAY",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Day of week 0-6 in UTC (Sunday=0).",
        ts_signature: "getUTCDay(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCHours",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_HOURS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Hour 0-23 in UTC.",
        ts_signature: "getUTCHours(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCMinutes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_MINUTES",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Minute 0-59 in UTC.",
        ts_signature: "getUTCMinutes(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCSeconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_SECONDS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Second 0-59 in UTC.",
        ts_signature: "getUTCSeconds(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getUTCMilliseconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_UTC_MILLISECONDS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Millisecond 0-999 in UTC.",
        ts_signature: "getUTCMilliseconds(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getTimezoneOffset",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_TIMEZONE_OFFSET",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Minutos entre UTC e local. RTS sempre 0.",
        ts_signature: "getTimezoneOffset(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toUTCString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_UTC_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "UTC string (alias de toISOString em v0).",
        ts_signature: "toUTCString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toDateString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_DATE_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Date portion (YYYY-MM-DD) em UTC.",
        ts_signature: "toDateString(): string",
        intrinsic: None,
        pure: true,
    },
    // (#220) Setters — mutate Entry::DateMs in-place. Retorna novos ms.
    NamespaceMember {
        name: "setFullYear",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_FULL_YEAR",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui o ano. Retorna ms novos.",
        ts_signature: "setFullYear(year: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setMonth",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_MONTH",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui o mes (0-11). Retorna ms novos.",
        ts_signature: "setMonth(month: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setDate",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_DATE",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui o dia do mes (1-31). Retorna ms novos.",
        ts_signature: "setDate(day: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setHours",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_HOURS",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui hour (0-23).",
        ts_signature: "setHours(hour: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setMinutes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_MINUTES",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui min (0-59).",
        ts_signature: "setMinutes(min: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setSeconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_SECONDS",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui sec (0-59).",
        ts_signature: "setSeconds(sec: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setMilliseconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_MILLISECONDS",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui ms (0-999).",
        ts_signature: "setMilliseconds(ms: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setTime",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_SET_TIME",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "Substitui timestamp completo (ms desde epoch).",
        ts_signature: "setTime(ms: number): number",
        intrinsic: None,
        pure: false,
    },
    // (#220) Conversion methods extras.
    NamespaceMember {
        name: "toJSON",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_JSON",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "JSON serialization — alias de toISOString.",
        ts_signature: "toJSON(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLocaleString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_LOCALE_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Locale string (sem locale support em v0).",
        ts_signature: "toLocaleString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLocaleTimeString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_LOCALE_TIME_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Time portion (HH:MM:SS.mmmZ) — alias de toTimeString.",
        ts_signature: "toLocaleTimeString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toTimeString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_TIME_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Time portion (HH:MM:SS.mmmZ) do ISO.",
        ts_signature: "toTimeString(): string",
        intrinsic: None,
        pure: true,
    },
];

pub const CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Date",
    doc: "Built-in Date class. Stores UTC timestamp as ms since Unix epoch.",
    members: MEMBERS,
};
