//! `Date` global class — ABI registration as `GlobalClassSpec`.

use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── Static methods ────────────────────────────────────────────────────────
    NamespaceMember {
        name: "now",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_DATE_NOW_MS",
        args: &[],
        returns: AbiType::I64,
        doc: "Returns the current time as milliseconds since Unix epoch (UTC).",
        ts_signature: "now(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "parse",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_DATE_FROM_ISO",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Parses an ISO 8601 string to ms since epoch. Returns NaN sentinel on failure.",
        ts_signature: "parse(dateString: string): number",
        intrinsic: None,
        pure: true,
    },
    // ── Constructors (distinguished by arity) ─────────────────────────────────
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DATE_NEW_NOW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Creates a Date representing the current instant.",
        ts_signature: "new Date(): Date",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_from_ms",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DATE_NEW_FROM_MS",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Creates a Date from milliseconds since Unix epoch.",
        ts_signature: "new Date(value: number): Date",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_from_iso",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DATE_NEW_FROM_ISO",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Creates a Date from an ISO 8601 string.",
        ts_signature: "new Date(dateString: string): Date",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods ──────────────────────────────────────────────────────
    NamespaceMember {
        name: "getTime",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_TIME",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Returns ms since epoch.",
        ts_signature: "getTime(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "valueOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_VALUE_OF",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Same as getTime().",
        ts_signature: "valueOf(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getFullYear",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_FULL_YEAR",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Full year (UTC).",
        ts_signature: "getFullYear(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getMonth",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_MONTH",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Month 0-indexed (UTC). Jan=0, Dec=11.",
        ts_signature: "getMonth(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getDate",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_DATE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Day of month 1-31 (UTC).",
        ts_signature: "getDate(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getDay",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_DAY",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Day of week 0-6 (UTC). Sunday=0.",
        ts_signature: "getDay(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getHours",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_HOURS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Hour 0-23 (UTC).",
        ts_signature: "getHours(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getMinutes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_MINUTES",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Minute 0-59 (UTC).",
        ts_signature: "getMinutes(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getSeconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_SECONDS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Second 0-59 (UTC).",
        ts_signature: "getSeconds(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getMilliseconds",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_GET_MILLISECONDS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Millisecond 0-999 (UTC).",
        ts_signature: "getMilliseconds(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toISOString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_ISO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "ISO 8601 UTC string.",
        ts_signature: "toISOString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "String representation (ISO 8601 UTC).",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLocaleDateString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_DATE_TO_LOCALE_DATE_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Locale-agnostic date string (same as toISOString in v0).",
        ts_signature: "toLocaleDateString(): string",
        intrinsic: None,
        pure: true,
    },
];

pub const CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Date",
    doc: "Built-in Date class. Stores UTC timestamp as ms since Unix epoch.",
    members: MEMBERS,
};
