//! `json` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "parse",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_PARSE",
        args: &[AbiType::StrPtr],
        returns: AbiType::U64,
        doc: "Parses a JSON string into an opaque JSON value handle. Returns 0 on syntax error.",
        ts_signature: "parse(text: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "stringify",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_STRINGIFY",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Serializes a JSON value handle into its compact string form.",
        ts_signature: "stringify(value: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "stringify_pretty",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_STRINGIFY_PRETTY",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Pretty-printed serialization with `indent` spaces (>= 0).",
        ts_signature: "stringify_pretty(value: number, indent: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_FREE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Releases the JSON value handle.",
        ts_signature: "free(handle: number): void",
        intrinsic: None,
        pure: false,
    },
    // ── Acesso por path / tipo ───────────────────────────────────────
    NamespaceMember {
        name: "type_of",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_TYPE_OF",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Returns: 0 null, 1 bool, 2 number, 3 string, 4 array, 5 object, -1 invalid.",
        ts_signature: "type_of(value: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "as_bool",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_AS_BOOL",
        args: &[AbiType::U64],
        returns: AbiType::Bool,
        doc: "Coerces JSON value to bool (true for non-zero/non-null/non-empty).",
        ts_signature: "as_bool(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "as_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_AS_I64",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Reads JSON number as i64 (truncates floats). 0 for invalid/non-number.",
        ts_signature: "as_i64(value: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "as_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_AS_F64",
        args: &[AbiType::U64],
        returns: AbiType::F64,
        doc: "Reads JSON number as f64. NaN for invalid/non-number.",
        ts_signature: "as_f64(value: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "as_string",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_AS_STRING",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Reads JSON string as a string handle. Empty handle (0) for non-string.",
        ts_signature: "as_string(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "array_len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_ARRAY_LEN",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Number of elements when value is array; -1 otherwise.",
        ts_signature: "array_len(value: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "array_get",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_ARRAY_GET",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::U64,
        doc: "Returns a NEW handle to the element at `index`. 0 if out of range.",
        ts_signature: "array_get(value: number, index: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "object_get",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_OBJECT_GET",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::U64,
        doc: "Returns a NEW handle to the property `key`. 0 if missing or non-object.",
        ts_signature: "object_get(value: number, key: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "object_has",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_JSON_OBJECT_HAS",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when value is an object containing `key`.",
        ts_signature: "object_has(value: number, key: string): boolean",
        intrinsic: None,
        pure: true,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "json",
    doc: "JSON parsing and serialization (paridade com JSON.parse/stringify).",
    members: MEMBERS,
};
