//! `gc` namespace registration on the ABI surface.
//!
//! Only the string-handle API is exposed for now; object/array/buffer
//! allocators land as the rest of the runtime is rewired.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "string_from_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_FROM_I64",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Converts an i64 to its decimal string and returns a handle.",
        ts_signature: "string_from_i64(value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_from_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_FROM_F64",
        args: &[AbiType::F64],
        returns: AbiType::Handle,
        doc: "Converts an f64 to its decimal string and returns a handle.",
        ts_signature: "string_from_f64(value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_concat",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_CONCAT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Concatenates two string handles and returns a new handle.",
        ts_signature: "string_concat(a: number, b: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_eq",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_EQ",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "Compara dois string handles por conteudo (memcmp). 1 se iguais, 0 caso contrario.",
        ts_signature: "string_eq(a: number, b: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_from_static",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_FROM_STATIC",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Promotes a static (ptr, len) string to a GC handle.",
        ts_signature: "string_from_static(data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_NEW",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Allocates a string handle from a (ptr, len) pair. Returns 0 on error.",
        ts_signature: "string_new(data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_LEN",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Returns the byte length of the string, or -1 on invalid handle.",
        ts_signature: "string_len(handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_ptr",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_PTR",
        args: &[AbiType::Handle],
        returns: AbiType::U64,
        doc: "Returns the raw pointer to the string buffer, or 0 on invalid handle.",
        ts_signature: "string_ptr(handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "string_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_STRING_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Frees the string handle. Returns 1 on success, 0 if already invalid.",
        ts_signature: "string_free(handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "env_alloc",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_ENV_ALLOC",
        args: &[AbiType::I32],
        returns: AbiType::Handle,
        doc: "Aloca um environment record para closures com `slot_count` slots i64 inicializados em 0. Retorna o handle.",
        ts_signature: "env_alloc(slot_count: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "env_get",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_ENV_GET",
        args: &[AbiType::Handle, AbiType::I32],
        returns: AbiType::I64,
        doc: "Lê o slot `slot` do env record. Retorna 0 em handle inválido ou slot fora do range.",
        ts_signature: "env_get(env: number, slot: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "env_set",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_ENV_SET",
        args: &[AbiType::Handle, AbiType::I32, AbiType::I64],
        returns: AbiType::I64,
        doc: "Escreve `value` no slot `slot` do env record. Retorna 1 em sucesso, 0 em erro.",
        ts_signature: "env_set(env: number, slot: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_NEW",
        args: &[AbiType::I32, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Aloca uma instancia com `size` bytes zerados e tag de classe `class_handle`. Retorna o handle ou 0 em erro.",
        ts_signature: "instance_new(size: number, class_handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_class",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_CLASS",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Retorna o handle da classe (tag string `__rts_class`) da instancia. 0 em handle invalido.",
        ts_signature: "instance_class(handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Libera a instancia. Retorna 1 em sucesso, 0 se ja invalido.",
        ts_signature: "instance_free(handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_load_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_LOAD_I64",
        args: &[AbiType::Handle, AbiType::I32],
        returns: AbiType::I64,
        doc: "Le um i64 little-endian no offset (em bytes). 0 em handle invalido ou offset fora do range.",
        ts_signature: "instance_load_i64(handle: number, offset: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_store_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_STORE_I64",
        args: &[AbiType::Handle, AbiType::I32, AbiType::I64],
        returns: AbiType::I64,
        doc: "Escreve um i64 little-endian no offset. Retorna 1 em sucesso, 0 em erro.",
        ts_signature: "instance_store_i64(handle: number, offset: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_load_i32",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_LOAD_I32",
        args: &[AbiType::Handle, AbiType::I32],
        returns: AbiType::I32,
        doc: "Le um i32 little-endian no offset. 0 em handle invalido ou offset fora do range.",
        ts_signature: "instance_load_i32(handle: number, offset: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_store_i32",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_STORE_I32",
        args: &[AbiType::Handle, AbiType::I32, AbiType::I32],
        returns: AbiType::I64,
        doc: "Escreve um i32 little-endian no offset. Retorna 1 em sucesso, 0 em erro.",
        ts_signature: "instance_store_i32(handle: number, offset: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_load_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_LOAD_F64",
        args: &[AbiType::Handle, AbiType::I32],
        returns: AbiType::F64,
        doc: "Le um f64 little-endian no offset. 0.0 em handle invalido ou offset fora do range.",
        ts_signature: "instance_load_f64(handle: number, offset: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "instance_store_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_INSTANCE_STORE_F64",
        args: &[AbiType::Handle, AbiType::I32, AbiType::F64],
        returns: AbiType::I64,
        doc: "Escreve um f64 little-endian no offset. Retorna 1 em sucesso, 0 em erro.",
        ts_signature: "instance_store_f64(handle: number, offset: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "env_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_GC_ENV_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Libera o env record. Retorna 1 em sucesso, 0 se handle já inválido.",
        ts_signature: "env_free(env: number): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "gc",
    doc: "Runtime-managed handle table and string pool.",
    members: MEMBERS,
};
