//! Object — ABI registration: GlobalClassSpec (JS Object class).
//!
//! Static methods: keys(), values(), entries(), hasOwn(), assign(),
//! create(), fromEntries(), defineProperty(), freeze(), seal().
//! Instance methods: toString(), hasOwnProperty().

use crate::abi::{AbiType, MemberKind, NamespaceMember};
use crate::abi::global_class::GlobalClassSpec;

pub const OBJECT_CLASS_MEMBERS: &[NamespaceMember] = &[
    // ── Constructors ─────────────────────────────────────────────────────
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_OBJECT_CREATE",
        args: &[],
        returns: AbiType::Handle,
        doc: "Object() — creates a new empty object.",
        ts_signature: "new(): number",
        intrinsic: None,
        pure: false,
    },
    // ── Static methods ───────────────────────────────────────────────────
    NamespaceMember {
        name: "keys",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_KEYS",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Object.keys(obj) — returns array of own enumerable property names.",
        ts_signature: "keys(obj: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "values",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_VALUES",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Object.values(obj) — returns array of own enumerable property values.",
        ts_signature: "values(obj: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "entries",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_ENTRIES",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Object.entries(obj) — returns array of [key, value] pairs.",
        ts_signature: "entries(obj: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hasOwn",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_HAS",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "Object.hasOwn(obj, prop) — returns true if obj has own property.",
        ts_signature: "hasOwn(obj: number, prop: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "assign",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_ASSIGN",
        args: &[AbiType::U64, AbiType::U64],
        returns: AbiType::Void,
        doc: "Object.assign(target, source) — copies properties from source to target.",
        ts_signature: "assign(target: number, source: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "create",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_CREATE",
        args: &[],
        returns: AbiType::Handle,
        doc: "Object.create() — creates a new empty object.",
        ts_signature: "create(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "fromEntries",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_FROM_ENTRIES",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Object.fromEntries(iterable) — creates object from key-value pairs.",
        ts_signature: "fromEntries(iterable: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "defineProperty",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_DEFINE_PROP",
        args: &[AbiType::U64, AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Void,
        doc: "Object.defineProperty(obj, prop, value) — defines a property.",
        ts_signature: "defineProperty(obj: number, prop: string, value: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "freeze",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_FREEZE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Object.freeze(obj) — freezes the object (marks as immutable).",
        ts_signature: "freeze(obj: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "seal",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_OBJECT_SEAL",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Object.seal(obj) — seals the object.",
        ts_signature: "seal(obj: number): void",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods ─────────────────────────────────────────────────
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_OBJECT_TO_STRING",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "obj.toString() — returns \"[object Object]\".",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hasOwnProperty",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_HAS",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "obj.hasOwnProperty(prop) — returns true if obj has own property.",
        ts_signature: "hasOwnProperty(prop: string): boolean",
        intrinsic: None,
        pure: true,
    },
];

pub const OBJECT_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Object",
    doc: "JS Object class — Object.keys(), Object.assign(), obj.toString(), etc.",
    members: OBJECT_CLASS_MEMBERS,
};
