//! `num` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── checked: retornam i64::MIN em overflow (sentinela) ────────────
    NamespaceMember {
        name: "checked_add",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_CHECKED_ADD",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a + b com overflow; retorna i64::MIN como sentinela em overflow.",
        ts_signature: "checked_add(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "checked_sub",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_CHECKED_SUB",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a - b com overflow; retorna i64::MIN como sentinela em overflow.",
        ts_signature: "checked_sub(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "checked_mul",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_CHECKED_MUL",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a * b com overflow; retorna i64::MIN como sentinela em overflow.",
        ts_signature: "checked_mul(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "checked_div",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_CHECKED_DIV",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a / b; retorna i64::MIN se b == 0 ou overflow (i64::MIN / -1).",
        ts_signature: "checked_div(a: number, b: number): number",
        intrinsic: None,
    },
    // ── saturating: clamp em i64::MIN/MAX ─────────────────────────────
    NamespaceMember {
        name: "saturating_add",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_SATURATING_ADD",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a + b com saturation em i64::MIN/MAX.",
        ts_signature: "saturating_add(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "saturating_sub",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_SATURATING_SUB",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a - b com saturation em i64::MIN/MAX.",
        ts_signature: "saturating_sub(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "saturating_mul",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_SATURATING_MUL",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a * b com saturation em i64::MIN/MAX.",
        ts_signature: "saturating_mul(a: number, b: number): number",
        intrinsic: None,
    },
    // ── wrapping: comportamento modular ───────────────────────────────
    NamespaceMember {
        name: "wrapping_add",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_WRAPPING_ADD",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a + b modulo 2^64.",
        ts_signature: "wrapping_add(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "wrapping_sub",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_WRAPPING_SUB",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a - b modulo 2^64.",
        ts_signature: "wrapping_sub(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "wrapping_mul",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_WRAPPING_MUL",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a * b modulo 2^64.",
        ts_signature: "wrapping_mul(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "wrapping_neg",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_WRAPPING_NEG",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "-a modulo 2^64 (i64::MIN.wrapping_neg() == i64::MIN).",
        ts_signature: "wrapping_neg(a: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "wrapping_shl",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_WRAPPING_SHL",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a << (n & 63) — shift count masked.",
        ts_signature: "wrapping_shl(a: number, n: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "wrapping_shr",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_WRAPPING_SHR",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a >> (n & 63) (arithmetic shift).",
        ts_signature: "wrapping_shr(a: number, n: number): number",
        intrinsic: None,
    },
    // ── bits ──────────────────────────────────────────────────────────
    NamespaceMember {
        name: "count_ones",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_COUNT_ONES",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Numero de bits 1 em a.",
        ts_signature: "count_ones(a: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "count_zeros",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_COUNT_ZEROS",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Numero de bits 0 em a.",
        ts_signature: "count_zeros(a: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "leading_zeros",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_LEADING_ZEROS",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Numero de zeros leading em a.",
        ts_signature: "leading_zeros(a: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "trailing_zeros",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_TRAILING_ZEROS",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Numero de zeros trailing em a.",
        ts_signature: "trailing_zeros(a: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "rotate_left",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_ROTATE_LEFT",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a rotacionado n bits para a esquerda.",
        ts_signature: "rotate_left(a: number, n: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "rotate_right",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_ROTATE_RIGHT",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "a rotacionado n bits para a direita.",
        ts_signature: "rotate_right(a: number, n: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "reverse_bits",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_REVERSE_BITS",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Bits invertidos (LSB->MSB).",
        ts_signature: "reverse_bits(a: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "swap_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NUM_SWAP_BYTES",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Bytes invertidos (endianness flip).",
        ts_signature: "swap_bytes(a: number): number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "num",
    doc: "Aritmetica com overflow explicito (checked/saturating/wrapping) e bit ops.",
    members: MEMBERS,
};
