//! `mem` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "size_of_i64",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MEM_SIZE_OF_I64",
        args: &[],
        returns: AbiType::I64,
        doc: "Tamanho em bytes de um i64 (= 8).",
        ts_signature: "size_of_i64: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "size_of_f64",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MEM_SIZE_OF_F64",
        args: &[],
        returns: AbiType::I64,
        doc: "Tamanho em bytes de um f64 (= 8).",
        ts_signature: "size_of_f64: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "size_of_i32",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MEM_SIZE_OF_I32",
        args: &[],
        returns: AbiType::I64,
        doc: "Tamanho em bytes de um i32 (= 4).",
        ts_signature: "size_of_i32: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "size_of_bool",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MEM_SIZE_OF_BOOL",
        args: &[],
        returns: AbiType::I64,
        doc: "Tamanho em bytes de um bool (= 1).",
        ts_signature: "size_of_bool: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "align_of_i64",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MEM_ALIGN_OF_I64",
        args: &[],
        returns: AbiType::I64,
        doc: "Alinhamento de i64 (= 8).",
        ts_signature: "align_of_i64: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "align_of_f64",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MEM_ALIGN_OF_F64",
        args: &[],
        returns: AbiType::I64,
        doc: "Alinhamento de f64 (= 8).",
        ts_signature: "align_of_f64: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "swap_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MEM_SWAP_I64",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Retorna `b` (use idiom: `let old = mem.swap_i64(a, b)`).",
        ts_signature: "swap_i64(a: number, b: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "drop_handle",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MEM_DROP_HANDLE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Forca free de um handle GC. Equivalente a gc.string_free / etc.",
        ts_signature: "drop_handle(h: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "forget_handle",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MEM_FORGET_HANDLE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Esquece handle sem rodar drop — vaza memoria intencionalmente.",
        ts_signature: "forget_handle(h: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "replace_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MEM_REPLACE_I64",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Idiom: `mem.replace_i64(slot, new)` — retorna slot e usa caller pra escrever.",
        ts_signature: "replace_i64(slot: number, new_val: number): number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "mem",
    doc: "std::mem: layout (size_of/align_of), swap, drop, forget.",
    members: MEMBERS,
};
