//! `net` namespace — ABI registration. Casa com a issue #16.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── TCP ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "tcp_listen",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_LISTEN",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Bind TCP em `addr` (\"host:port\"). Retorna handle do listener ou 0.",
        ts_signature: "tcp_listen(addr: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "tcp_accept",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_ACCEPT",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Aceita conexao do listener. Bloqueia. Retorna stream handle ou 0.",
        ts_signature: "tcp_accept(listener: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "tcp_connect",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_CONNECT",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Conecta TCP em `addr`. Retorna stream handle ou 0.",
        ts_signature: "tcp_connect(addr: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "tcp_send",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_SEND",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Envia bytes da string no stream. Retorna bytes escritos ou -1.",
        ts_signature: "tcp_send(stream: number, data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "tcp_recv",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_RECV",
        args: &[AbiType::U64, AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Le ate `len` bytes em `bufPtr`. Retorna bytes lidos (0 = EOF, -1 = erro).",
        ts_signature: "tcp_recv(stream: number, bufPtr: number, len: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "tcp_local_addr",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_LOCAL_ADDR",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Endereco local do socket (listener ou stream) como string handle. 0 em erro.",
        ts_signature: "tcp_local_addr(handle: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "tcp_close",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_TCP_CLOSE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Fecha o socket TCP (listener ou stream) e libera o handle.",
        ts_signature: "tcp_close(handle: number): void",
        intrinsic: None,
        pure: false,
    },
    // ── UDP ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "udp_bind",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_UDP_BIND",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Bind UDP em `addr`. Retorna socket handle ou 0.",
        ts_signature: "udp_bind(addr: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "udp_send_to",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_UDP_SEND_TO",
        args: &[AbiType::U64, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Envia bytes da string em `data` para `dest`. Retorna bytes enviados ou -1.",
        ts_signature: "udp_send_to(sock: number, dest: string, data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "udp_recv_from",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_UDP_RECV_FROM",
        args: &[AbiType::U64, AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Le ate `len` bytes em `bufPtr`. Peer endereco fica disponivel via udp_last_peer. Retorna bytes lidos ou -1.",
        ts_signature: "udp_recv_from(sock: number, bufPtr: number, len: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "udp_last_peer",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_UDP_LAST_PEER",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Endereco do peer da ultima recv_from neste socket. String handle ou 0.",
        ts_signature: "udp_last_peer(sock: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "udp_local_addr",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_UDP_LOCAL_ADDR",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Endereco local do socket UDP como string handle. 0 em erro.",
        ts_signature: "udp_local_addr(sock: number): string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "udp_close",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_UDP_CLOSE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Fecha o socket UDP e libera o handle.",
        ts_signature: "udp_close(sock: number): void",
        intrinsic: None,
        pure: false,
    },
    // ── DNS ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "resolve",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_NET_RESOLVE",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "DNS lookup de `host`. Retorna primeiro IP como string handle, ou 0.",
        ts_signature: "resolve(host: string): string",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "net",
    doc: "TCP/UDP sync sockets backed by std::net.",
    members: MEMBERS,
};
