//! `promise` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new_pending",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_NEW_PENDING",
        args: &[],
        returns: AbiType::Handle,
        doc: "Cria uma Promise async pending. Use `promise.resolve(h, v)` ou `promise.reject(h, e)` depois pra settle. Outras Promises (sync/JS Promise.resolve/reject) usam atalhos.",
        ts_signature: "new_pending(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_resolved",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_NEW_RESOLVED",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Cria Promise async ja' fulfilled com `value`. Equivalente do `Promise.resolve(v)` JS.",
        ts_signature: "new_resolved(value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_rejected",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_NEW_REJECTED",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Cria Promise async ja' rejected com `error`. Equivalente do `Promise.reject(e)` JS.",
        ts_signature: "new_rejected(error: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "resolve",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_RESOLVE",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Resolve Promise pending com `value`. Retorna 1 em sucesso, 0 se ja' estava settled (semantica JS — segundo resolve eh no-op).",
        ts_signature: "resolve(promise: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "reject",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_REJECT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Reject Promise pending com `error`. Retorna 1 em sucesso, 0 se ja' estava settled.",
        ts_signature: "reject(promise: number, error: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "state",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_STATE",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Retorna 0 (pending), 1 (fulfilled) ou 2 (rejected). -1 se handle invalido.",
        ts_signature: "state(promise: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "wait",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_WAIT",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Bloqueia thread chamadora ate Promise settle e retorna o valor. Se rejected, retorna o erro com bit alto setado (F5 vai tratar isso pra integrar try/catch). 0 se handle invalido.",
        ts_signature: "wait(promise: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "try_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_TRY_VALUE",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Nao-bloqueante: retorna o valor se Promise ja' settled, 0 se ainda pending ou handle invalido. Para checar pending vs settled use `state` antes.",
        ts_signature: "try_value(promise: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "then",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_THEN_NS",
        args: &[AbiType::U64, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.then(p, fn) — chama fn(value) ao resolve, retorna nova Promise resolvida com retorno de fn. Para PromiseAsync, spawna task tokio que aguarda settle. Equivalente a `p.then(fn)` JS mas com sintaxe namespace pra evitar conflito com instance methods do Promise class spec.",
        ts_signature: "then(p: number, fn: (v: number) => number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "catch",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_CATCH_NS",
        args: &[AbiType::U64, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.catch(p, fn) — chama fn(err) ao reject. Recovers (Promise resultante eh fulfilled).",
        ts_signature: "catch(p: number, fn: (e: number) => number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "finally",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_FINALLY_NS",
        args: &[AbiType::U64, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.finally(p, fn) — chama fn() ao settle. Mantem state/value original.",
        ts_signature: "finally(p: number, fn: () => void): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "take_error",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_TAKE_ERROR",
        args: &[],
        returns: AbiType::I64,
        doc: "Le e limpa o slot de erro thread-local. Retorna handle do erro pendente ou 0 se nao houver. Usado internamente pelo codegen de async fn (F5 #416) — apos chamar o body, watcher checa este slot pra decidir entre `resolve` e `reject`.",
        ts_signature: "take_error(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "all",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_ALL",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Promise.all(promises): aguarda todas as Promises do Vec resolverem. Retorna nova Promise resolvida com Vec dos valores na ordem original. Se qualquer uma rejeitar, a Promise resultante rejeita imediatamente com o erro da primeira a rejeitar. Argumento eh handle de `collections.vec` contendo handles de Promise. Equivalente a `Promise.all` JS.",
        ts_signature: "all(promises: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "race",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_RACE",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Promise.race(promises): retorna nova Promise que settle com o resultado da primeira Promise a settle (resolve OU reject). Equivalente a `Promise.race` JS.",
        ts_signature: "race(promises: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "any",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_ANY",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Promise.any(promises): resolve com a primeira a fulfill. Rejeita SO' se todas rejeitarem (com 0 — sem AggregateError ainda). Equivalente a `Promise.any` JS.",
        ts_signature: "any(promises: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "all_settled",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_ALL_SETTLED",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Promise.allSettled(promises): aguarda todas, sempre resolve. Retorna Vec onde cada slot eh state*1000 + value (encoding: 1xxx=fulfilled, 2xxx=rejected). Permite caller distinguir valores positivos pequenos. Diferente do JS que retorna {status, value/reason} — RTS usa encoding compacto i64.",
        ts_signature: "all_settled(promises: number): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "promise",
    doc: "Promise<T> async com state machine + waiters via tokio oneshot. Base para async/await (issue #412 / epic #411).",
    members: MEMBERS,
};
