//! `promise` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new_pending",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_NEW_PENDING",
        args: &[],
        returns: AbiType::Handle,
        doc: "Cria uma Promise async pending. Use `promise.resolve(h, v)` ou `promise.reject(h, e)` depois pra settle. Outras Promises (sync/JS Promise.resolve/reject) usam atalhos.",
        ts_signature: "new_pending(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_resolved",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_NEW_RESOLVED",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Cria Promise async ja' fulfilled com `value`. Equivalente do `Promise.resolve(v)` JS.",
        ts_signature: "new_resolved(value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new_rejected",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_NEW_REJECTED",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Cria Promise async ja' rejected com `error`. Equivalente do `Promise.reject(e)` JS.",
        ts_signature: "new_rejected(error: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "resolve",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_RESOLVE",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Resolve Promise pending com `value`. Retorna 1 em sucesso, 0 se ja' estava settled (semantica JS — segundo resolve eh no-op).",
        ts_signature: "resolve(promise: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "reject",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_REJECT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Reject Promise pending com `error`. Retorna 1 em sucesso, 0 se ja' estava settled.",
        ts_signature: "reject(promise: number, error: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "state",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_STATE",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Retorna 0 (pending), 1 (fulfilled) ou 2 (rejected). -1 se handle invalido.",
        ts_signature: "state(promise: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "wait",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_WAIT",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Bloqueia thread chamadora ate Promise settle e retorna o valor. Se rejected, retorna o erro com bit alto setado (F5 vai tratar isso pra integrar try/catch). 0 se handle invalido.",
        ts_signature: "wait(promise: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "try_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_TRY_VALUE",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Nao-bloqueante: retorna o valor se Promise ja' settled, 0 se ainda pending ou handle invalido. Para checar pending vs settled use `state` antes.",
        ts_signature: "try_value(promise: number): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "promise",
    doc: "Promise<T> async com state machine + waiters via tokio oneshot. Base para async/await (issue #412 / epic #411).",
    members: MEMBERS,
};
