//! `atomic` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── AtomicI64 ───────────────────────────────────────────────────
    NamespaceMember {
        name: "i64_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_NEW",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Aloca um AtomicI64 inicializado com `value` e retorna o handle.",
        ts_signature: "i64_new(value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_load",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_LOAD",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Le o valor atual do AtomicI64 (SeqCst). 0 se handle invalido.",
        ts_signature: "i64_load(handle: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_store",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_STORE",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Escreve `value` no AtomicI64 (SeqCst). No-op se handle invalido.",
        ts_signature: "i64_store(handle: number, value: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_fetch_add",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_FETCH_ADD",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Soma `delta` e retorna o valor anterior. 0 se handle invalido.",
        ts_signature: "i64_fetch_add(handle: number, delta: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_fetch_sub",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_FETCH_SUB",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Subtrai `delta` e retorna o valor anterior. 0 se handle invalido.",
        ts_signature: "i64_fetch_sub(handle: number, delta: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_fetch_and",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_FETCH_AND",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "AND bit-a-bit com `mask` e retorna o valor anterior. 0 se handle invalido.",
        ts_signature: "i64_fetch_and(handle: number, mask: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_fetch_or",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_FETCH_OR",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "OR bit-a-bit com `mask` e retorna o valor anterior. 0 se handle invalido.",
        ts_signature: "i64_fetch_or(handle: number, mask: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_fetch_xor",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_FETCH_XOR",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "XOR bit-a-bit com `mask` e retorna o valor anterior. 0 se handle invalido.",
        ts_signature: "i64_fetch_xor(handle: number, mask: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_swap",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_SWAP",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Troca o valor por `value` e retorna o valor anterior. 0 se handle invalido.",
        ts_signature: "i64_swap(handle: number, value: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "i64_cas",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_I64_CAS",
        args: &[AbiType::U64, AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Compare-and-swap. Se valor atual == `expected`, escreve `new`. Retorna o valor anterior.",
        ts_signature: "i64_cas(handle: number, expected: number, new_value: number): number",
        intrinsic: None,
        pure: false,
    },
    // ── AtomicBool ─────────────────────────────────────────────────
    NamespaceMember {
        name: "bool_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_BOOL_NEW",
        args: &[AbiType::Bool],
        returns: AbiType::Handle,
        doc: "Aloca um AtomicBool inicializado com `value` e retorna o handle.",
        ts_signature: "bool_new(value: boolean): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "bool_load",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_BOOL_LOAD",
        args: &[AbiType::U64],
        returns: AbiType::Bool,
        doc: "Le o valor atual do AtomicBool (SeqCst). false se handle invalido.",
        ts_signature: "bool_load(handle: number): boolean",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "bool_store",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_BOOL_STORE",
        args: &[AbiType::U64, AbiType::Bool],
        returns: AbiType::Void,
        doc: "Escreve `value` no AtomicBool (SeqCst). No-op se handle invalido.",
        ts_signature: "bool_store(handle: number, value: boolean): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "bool_swap",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_BOOL_SWAP",
        args: &[AbiType::U64, AbiType::Bool],
        returns: AbiType::Bool,
        doc: "Troca o valor por `value` e retorna o valor anterior. false se handle invalido.",
        ts_signature: "bool_swap(handle: number, value: boolean): boolean",
        intrinsic: None,
        pure: false,
    },
    // ── Fences ─────────────────────────────────────────────────────
    NamespaceMember {
        name: "fence_acquire",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_FENCE_ACQUIRE",
        args: &[],
        returns: AbiType::Void,
        doc: "Memory fence Acquire.",
        ts_signature: "fence_acquire(): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "fence_release",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_FENCE_RELEASE",
        args: &[],
        returns: AbiType::Void,
        doc: "Memory fence Release.",
        ts_signature: "fence_release(): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "fence_seq_cst",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_ATOMIC_FENCE_SEQ_CST",
        args: &[],
        returns: AbiType::Void,
        doc: "Memory fence SeqCst.",
        ts_signature: "fence_seq_cst(): void",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "atomic",
    doc: "Primitivas atomicas (AtomicI64, AtomicBool, fences) baseadas em std::sync::atomic.",
    members: MEMBERS,
};
