let i = 5;
console.log(i++);
console.log(i);
console.log(++i);
console.log(i);
let a = 1;
let r = a++ + ++a;
console.log(r);
console.log(a);
let b = 10;
let arr = [b++, b++, ++b];
console.log(arr.join(","));
console.log(b);
let x = 3;
let y = x-- - --x;
console.log(y);
console.log(x);
let n = 0;
n = n++;
console.log(n);