use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "encode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TEXTENC_ENCODE",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Encode string UTF-8 para Buffer handle (Uint8Array semantics).",
        ts_signature: "encode(text: string): Uint8Array",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "decode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TEXTENC_DECODE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Decode Buffer handle (bytes UTF-8) para string handle.",
        ts_signature: "decode(buf: Uint8Array): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "atob",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TEXTENC_ATOB",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Decode base64 string para string handle.",
        ts_signature: "atob(encoded: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "btoa",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TEXTENC_BTOA",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Encode string para base64 handle.",
        ts_signature: "btoa(data: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "structuredClone",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TEXTENC_STRUCTURED_CLONE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Deep clone de handle (Map, Vec, Buffer, String). Primitivos: usar direto.",
        ts_signature: "structuredClone(value: any): any",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "queueMicrotask",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TEXTENC_QUEUE_MICROTASK",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Executa callback imediatamente (RTS é síncrono, sem microtask queue real).",
        ts_signature: "queueMicrotask(callback: () => void): void",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "text_encoding",
    doc: "TextEncoder.encode / TextDecoder.decode / atob / btoa / structuredClone / queueMicrotask.",
    members: MEMBERS,
};
