// Cross-runtime: generators, yield*, the iterator protocol driven by hand — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const m = b;
(function (d, e) {
    const j = b, f = d();
    while (!![]) {
        try {
            const h = parseInt(j(0x107)) / 0x1 + -parseInt(j(0x10c)) / 0x2 * (parseInt(j(0x106)) / 0x3) + -parseInt(j(0xf1)) / 0x4 + -parseInt(j(0xfa)) / 0x5 * (-parseInt(j(0xf4)) / 0x6) + parseInt(j(0x102)) / 0x7 * (-parseInt(j(0x105)) / 0x8) + -parseInt(j(0x103)) / 0x9 + parseInt(j(0xf3)) / 0xa;
            if (h === e)
                break;
            else
                f['push'](f['shift']());
        } catch (i) {
            f['push'](f['shift']());
        }
    }
}(a, 0xbd90d));
const out = [];
function b(c, d) {
    c = c - 0xf0;
    const e = a();
    let f = e[c];
    return f;
}
function* inner() {
    const k = b, d = { 'bbUMe': k(0x100) };
    return yield 'i1', yield 'i2', d['bbUMe'];
}
function* outer() {
    const l = b, d = {
            'UrLII': l(0xf5),
            'mNzYf': function (f) {
                return f();
            },
            'oPbLV': function (f, h) {
                return f + h;
            },
            'oLyiJ': l(0xf6)
        };
    out[l(0xf7)](d[l(0xf8)]);
    const e = yield* d[l(0x104)](inner);
    out[l(0xf7)](d[l(0xff)](d['oLyiJ'], e)), yield 'o1';
}
out[m(0xf7)]([...outer()][m(0xfc)](','));
const it = inner();
out[m(0xf7)](JSON[m(0xf0)](it[m(0x101)]()), JSON['stringify'](it['next']())), out[m(0xf7)](JSON[m(0xf0)](it[m(0x101)]()), JSON[m(0xf0)](it[m(0x101)]()));
function* counter() {
    const n = m, d = {
            'YfcrG': function (f, h) {
                return f === h;
            },
            'AyHBi': function (f, h) {
                return f > h;
            }
        };
    let e = 0x0;
    while (!![]) {
        const f = yield e;
        e += d[n(0x108)](f, undefined) ? 0x1 : f;
        if (d[n(0xfd)](e, 0x6))
            return e;
    }
}
const c = counter();
out['push'](c['next']()[m(0xfb)], c[m(0x101)](0x3)[m(0xfb)], c[m(0x101)](0x3)[m(0xfb)]);
function* withFinally() {
    const o = m, d = { 'BzzqB': o(0xf9) };
    try {
        yield 0x1, yield 0x2;
    } finally {
        out[o(0xf7)](d[o(0xf2)]);
    }
}
const g = withFinally();
g[m(0x101)](), out[m(0xf7)](JSON[m(0xf0)](g[m(0x109)](m(0x10b))));
const manual = {
    [Symbol[m(0x10a)]]() {
        let d = 0x0;
        return {
            'next': () => d < 0x3 ? {
                'value': d++,
                'done': ![]
            } : {
                'value': undefined,
                'done': !![]
            }
        };
    }
};
function a() {
    const p = [
        'BzzqB',
        '23052320yFcYqt',
        '432wYfGRe',
        'pre',
        'got:',
        'push',
        'UrLII',
        'genfin',
        '2595mFCfNV',
        'value',
        'join',
        'AyHBi',
        'log',
        'oPbLV',
        'iend',
        'next',
        '21ElLEbB',
        '4867335UUppwG',
        'mNzYf',
        '930392zjqZzi',
        '607632rSeOZb',
        '108324aMvjKF',
        'YfcrG',
        'return',
        'iterator',
        'bye',
        '4knZQNe',
        'stringify',
        '1518652usxsLq'
    ];
    a = function () {
        return p;
    };
    return a();
}
out[m(0xf7)]([...manual][m(0xfc)]('+'));
for (const v of manual) {
    if (v === 0x1)
        break;
    out['push']('m' + v);
}
console[m(0xfe)](out[m(0xfc)]('|'));