// Cross-runtime: labels, switch fallthrough, try/catch/finally, short-circuit — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x1a4ef0 = _0x1820;
(function (_0x3c39ad, _0x1850b7) {
    const _0x40a295 = _0x1820, _0x4a1ac7 = _0x3c39ad();
    while (!![]) {
        try {
            const _0x269d93 = -parseInt(_0x40a295(0x132)) / 0x1 * (-parseInt(_0x40a295(0x13e)) / 0x2) + -parseInt(_0x40a295(0x134)) / 0x3 * (-parseInt(_0x40a295(0x144)) / 0x4) + -parseInt(_0x40a295(0x140)) / 0x5 + -parseInt(_0x40a295(0x12c)) / 0x6 * (-parseInt(_0x40a295(0x143)) / 0x7) + -parseInt(_0x40a295(0x133)) / 0x8 + -parseInt(_0x40a295(0x13b)) / 0x9 + parseInt(_0x40a295(0x139)) / 0xa;
            if (_0x269d93 === _0x1850b7)
                break;
            else
                _0x4a1ac7['push'](_0x4a1ac7['shift']());
        } catch (_0x5b0a01) {
            _0x4a1ac7['push'](_0x4a1ac7['shift']());
        }
    }
}(_0x1b78, 0xc9a37));
function _0x1820(_0x4fec56, _0x316bbd) {
    _0x4fec56 = _0x4fec56 - 0x12b;
    const _0x1b78be = _0x1b78();
    let _0x182082 = _0x1b78be[_0x4fec56];
    return _0x182082;
}
function _0x1b78() {
    const _0x127b08 = [
        '266wtrrjD',
        '52660bkKHOk',
        'dflt',
        'fin',
        '119364QiWVws',
        'YsqPT',
        'falsy',
        'lmHsk',
        'constructor',
        'deep',
        '7454ThmLKA',
        '5751728XWiHPx',
        '285eNPKqA',
        'LFjMJ',
        'zero',
        'log',
        'truthy',
        '5635700QYOyAM',
        'CelXe',
        '11121597MsXIZR',
        'name',
        'DSlMs',
        '314bXXkBa',
        'QHiip',
        '4799425LQQUoD',
        'join',
        'push'
    ];
    _0x1b78 = function () {
        return _0x127b08;
    };
    return _0x1b78();
}
const out = [];
_0x1b283b:
    for (let i = 0x0; i < 0x4; i++) {
        for (let j = 0x0; j < 0x4; j++) {
            if (j === 0x2)
                continue _0x1b283b;
            if (i === 0x3)
                break _0x1b283b;
            out[_0x1a4ef0(0x142)](i + '' + j);
        }
    }
function sw(_0x1d958d) {
    let _0x4f1f32 = '';
    switch (_0x1d958d) {
    case 0x0:
        _0x4f1f32 += 'z';
    case 0x1:
        _0x4f1f32 += 'o';
        break;
    case 0x2:
        _0x4f1f32 += 't';
        break;
    default:
        _0x4f1f32 += 'd';
    }
    return _0x4f1f32;
}
out[_0x1a4ef0(0x142)](sw(0x0) + sw(0x1) + sw(0x2) + sw(0x9));
function tf(_0xf614e1) {
    const _0x33697e = _0x1a4ef0;
    try {
        if (_0x33697e(0x135) === _0x33697e(0x13a))
            _0x278e28 += 0x2;
        else {
            if (_0xf614e1 === 0x0)
                throw new RangeError(_0x33697e(0x136));
            return 'ok' + _0xf614e1;
        }
    } catch (_0x6cfb67) {
        return _0x33697e(0x12f) !== _0x33697e(0x13d) ? _0x6cfb67[_0x33697e(0x130)][_0x33697e(0x13c)] : _0x5baf6b[_0x33697e(0x130)][_0x33697e(0x13c)];
    } finally {
        _0x33697e(0x12d) === _0x33697e(0x13f) ? _0x12e050[_0x33697e(0x142)](_0x33697e(0x12b) + _0x5d6667) : out[_0x33697e(0x142)](_0x33697e(0x12b) + _0xf614e1);
    }
}
out[_0x1a4ef0(0x142)](tf(0x0), tf(0x1));
let a = null;
out[_0x1a4ef0(0x142)](a ?? _0x1a4ef0(0x145), a?.[_0x1a4ef0(0x131)]?.['er'], 0x0 || _0x1a4ef0(0x12e), 0x1 && _0x1a4ef0(0x138));
let n = 0x0;
do {
    n += 0x2;
} while (n < 0x7);
out[_0x1a4ef0(0x142)](n), console[_0x1a4ef0(0x137)](out[_0x1a4ef0(0x141)]('|'));