// Cross-runtime: descriptors, freeze, symbols, enumeration order, JSON — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x3be790 = _0x2b4c;
(function (_0x5a6b2e, _0x282944) {
    const _0x372479 = _0x2b4c, _0x274656 = _0x5a6b2e();
    while (!![]) {
        try {
            const _0x4fc4a1 = parseInt(_0x372479(0x119)) / 0x1 + -parseInt(_0x372479(0x129)) / 0x2 + parseInt(_0x372479(0x11b)) / 0x3 * (-parseInt(_0x372479(0x115)) / 0x4) + parseInt(_0x372479(0x124)) / 0x5 + parseInt(_0x372479(0x112)) / 0x6 * (-parseInt(_0x372479(0x11a)) / 0x7) + -parseInt(_0x372479(0x120)) / 0x8 + parseInt(_0x372479(0x11d)) / 0x9 * (parseInt(_0x372479(0x127)) / 0xa);
            if (_0x4fc4a1 === _0x282944)
                break;
            else
                _0x274656['push'](_0x274656['shift']());
        } catch (_0x2bbe55) {
            _0x274656['push'](_0x274656['shift']());
        }
    }
}(_0x40ba, 0x93963));
function _0x2b4c(_0x3a0c3f, _0x63c582) {
    _0x3a0c3f = _0x3a0c3f - 0x10d;
    const _0x40ba9f = _0x40ba();
    let _0x2b4c68 = _0x40ba9f[_0x3a0c3f];
    return _0x2b4c68;
}
function _0x40ba() {
    const _0x325bee = [
        'getOwnPropertyDescriptor',
        'map',
        'defineProperty',
        'isFrozen',
        'push',
        'keys',
        '6dEVGym',
        'getOwnPropertySymbols',
        'stringify',
        '108868nLGuXt',
        '{\x22n\x22:[1,{\x22d\x22:true}],\x22s\x22:null}',
        'two',
        'set',
        '1006984vPhmSy',
        '3699612TUwwHR',
        '63ybvDEU',
        'tag',
        '225108mvtKeT',
        'log',
        'freeze',
        '6787352nkOtcP',
        'length',
        'entries',
        'join',
        '5666160kIAeXu',
        'hidden',
        'parse',
        '430jHbTzc',
        'one',
        '1325450JXviRs'
    ];
    _0x40ba = function () {
        return _0x325bee;
    };
    return _0x40ba();
}
const out = [], o = {
        'b': 0x2,
        0x2: _0x3be790(0x117),
        'a': 0x1,
        0x1: _0x3be790(0x128)
    };
out[_0x3be790(0x110)](Object[_0x3be790(0x111)](o)[_0x3be790(0x123)](',')), Object[_0x3be790(0x10e)](o, _0x3be790(0x125), {
    'value': 0x9,
    'enumerable': ![]
}), out[_0x3be790(0x110)](Object[_0x3be790(0x111)](o)[_0x3be790(0x123)](','), o[_0x3be790(0x125)]), out[_0x3be790(0x110)](JSON[_0x3be790(0x114)](Object[_0x3be790(0x12a)](o, _0x3be790(0x125))));
const frozen = Object[_0x3be790(0x11f)]({ 'v': 0x1 });
out[_0x3be790(0x110)](Reflect[_0x3be790(0x118)](frozen, 'v', 0x2), frozen['v'], Object[_0x3be790(0x10f)](frozen));
const sym = Symbol(_0x3be790(0x11c)), withSym = {
        [sym]: 's',
        'plain': 'p'
    };
out[_0x3be790(0x110)](Object[_0x3be790(0x111)](withSym)[_0x3be790(0x123)](','), withSym[sym]), out[_0x3be790(0x110)](Object[_0x3be790(0x113)](withSym)[_0x3be790(0x121)]);
class Box {
    constructor() {
        this['v'] = 0x1;
    }
    ['m']() {
    }
}
const bx = new Box(), seen = [];
for (const k in bx)
    seen[_0x3be790(0x110)](k);
out[_0x3be790(0x110)](seen[_0x3be790(0x123)](',')), out[_0x3be790(0x110)](JSON[_0x3be790(0x114)](JSON[_0x3be790(0x126)](_0x3be790(0x116)))), out[_0x3be790(0x110)](Object[_0x3be790(0x122)]({
    'z': 0x1,
    'y': 0x2
})[_0x3be790(0x10d)](([_0x4a0deb, _0x1f3d40]) => _0x4a0deb + _0x1f3d40)[_0x3be790(0x123)]('')), console[_0x3be790(0x11e)](out[_0x3be790(0x123)]('|'));