// Cross-runtime: closures, per-iteration bindings, shadowing, IIFE chains — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const k = b;
(function (d, e) {
    const j = b, f = d();
    while (!![]) {
        try {
            const g = -parseInt(j(0x7b)) / (-0x47 * 0x2 + -0xe7 * -0x15 + 0x16 * -0xd6) * (parseInt(j(0x79)) / (-0x1 * 0x71e + -0x7 * -0x207 + -0x3 * 0x25b)) + parseInt(j(0x78)) / (0x296 * -0x9 + -0x1db5 + 0x31e * 0x11) + parseInt(j(0x7a)) / (-0x2 * 0x11c2 + -0x1d * -0x25 + 0x1f57) + parseInt(j(0x82)) / (0x1aad + 0xd5c + -0x2804) * (parseInt(j(0x76)) / (0x2049 + 0x1 * -0xf6d + -0x10d6)) + -parseInt(j(0x7f)) / (-0xb * 0xf9 + 0x43 * 0x77 + -0x146b) + -parseInt(j(0x7d)) / (0xef * 0x2 + 0x1 * -0xe00 + 0xc2a) * (-parseInt(j(0x83)) / (0x116b + -0x1715 + 0x5b3)) + parseInt(j(0x80)) / (0x257 + 0x265c + -0x28a9);
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(a, -0x87bcc + -0x1fb0d + 0x1 * 0x11f492));
const out = [], fns = [];
function b(c, d) {
    c = c - (0x2c1 * -0xa + 0xbc + 0x1b42 * 0x1);
    const e = a();
    let f = e[c];
    return f;
}
for (let i = 0x13d9 * -0x1 + -0xa6 * -0x2 + 0x128d; i < -0x5 * -0x25f + -0x5 * 0x19d + 0x15 * -0x2e; i++)
    fns[k(0x75)](() => i * (0x1c8a + 0x18d + -0x1e14));
out['push'](fns['map'](d => d())[k(0x7e)](','));
function counter(e) {
    const l = k;
    let f = e;
    const g = {};
    return g[l(0x77)] = () => ++f, g[l(0x7c)] = () => f, g;
}
const c = counter(0xad6 + 0x1 * 0x6af + -0x117b);
function a() {
    const m = [
        'log',
        '20935cbbzbS',
        '20376GuUqFy',
        'inner',
        'outer',
        'push',
        '150bHrXJT',
        'inc',
        '1031661zKLjHD',
        '2Otwejf',
        '1441508UmvgUE',
        '225028ARkylx',
        'get',
        '1424lKKWqp',
        'join',
        '4510233tLWaAG',
        '1483530LsqkvV'
    ];
    a = function () {
        return m;
    };
    return a();
}
c[k(0x77)](), c[k(0x77)](), out[k(0x75)](c['get']());
let x = k(0x74);
{
    let x = k(0x84);
    out[k(0x75)](x);
}
out['push'](x), out['push'](function (d) {
    return function (e) {
        return d + e;
    }(0x3 * 0x40a + 0x1 * -0x1d7e + 0x1165);
}(0x61 + -0x152 * 0xd + 0x1 * 0x10d0));
const memo = ((() => {
    const d = {};
    return e => d[e] = (d[e] || -0x1 * 0xfa8 + 0x1103 + 0x15b * -0x1) + (-0x77d + -0x1 * 0x189b + 0x9 * 0x391);
})());
memo('a'), memo('a'), memo('b'), out[k(0x75)](memo('a') + ':' + memo('b')), console[k(0x81)](out[k(0x7e)]('|'));