// Cross-runtime: classes, prototypes, getters, static, super, instanceof — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x41e4fb = _0x26f3;
(function (_0x2449a0, _0x1ee9c4) {
    const _0x3752b3 = _0x26f3, _0x37b554 = _0x2449a0();
    while (!![]) {
        try {
            const _0x237f8f = -parseInt(_0x3752b3(0x1a5)) / 0x1 + parseInt(_0x3752b3(0x195)) / 0x2 * (-parseInt(_0x3752b3(0x192)) / 0x3) + -parseInt(_0x3752b3(0x1a4)) / 0x4 * (parseInt(_0x3752b3(0x1a0)) / 0x5) + -parseInt(_0x3752b3(0x1a1)) / 0x6 + -parseInt(_0x3752b3(0x18a)) / 0x7 + -parseInt(_0x3752b3(0x18f)) / 0x8 * (-parseInt(_0x3752b3(0x19a)) / 0x9) + -parseInt(_0x3752b3(0x199)) / 0xa * (-parseInt(_0x3752b3(0x19d)) / 0xb);
            if (_0x237f8f === _0x1ee9c4)
                break;
            else
                _0x37b554['push'](_0x37b554['shift']());
        } catch (_0x189bb5) {
            _0x37b554['push'](_0x37b554['shift']());
        }
    }
}(_0x3311, 0x671ed));
function _0x3311() {
    const _0x51e038 = [
        '544466auHdJt',
        'keys',
        'Shape',
        'kind',
        '22670710KVhSyB',
        '4170519JCNAqs',
        'describe',
        'you',
        '11CWagJC',
        'name',
        'getPrototypeOf',
        '151285gMecSF',
        '1810860etKpHw',
        'log',
        'join',
        '60xUApfk',
        '277128ziFXnz',
        'twice',
        'create',
        '3210123splPsg',
        'shape:',
        'label',
        'prototype',
        'who',
        '8nkVSzQ',
        'push',
        'hi\x20',
        '9vdqFiI',
        'greet',
        'circle'
    ];
    _0x3311 = function () {
        return _0x51e038;
    };
    return _0x3311();
}
const out = [];
class Shape {
    constructor(_0x2b46dd) {
        const _0x260830 = _0x26f3;
        this[_0x260830(0x19e)] = _0x2b46dd;
    }
    get [_0x41e4fb(0x18c)]() {
        const _0x3b40fb = _0x41e4fb;
        return _0x3b40fb(0x18b) + this[_0x3b40fb(0x19e)];
    }
    static [_0x41e4fb(0x198)]() {
        const _0x1fd2ed = _0x41e4fb;
        return _0x1fd2ed(0x197);
    }
    [_0x41e4fb(0x19b)]() {
        const _0x1056ed = _0x41e4fb;
        return this[_0x1056ed(0x18c)];
    }
}
class Circle extends Shape {
    constructor(_0x59cf11) {
        const _0x479e96 = _0x41e4fb;
        super(_0x479e96(0x194)), this['r'] = _0x59cf11;
    }
    get [_0x41e4fb(0x18c)]() {
        const _0x5cbfcd = _0x41e4fb;
        return super[_0x5cbfcd(0x18c)] + ':' + this['r'];
    }
    static [_0x41e4fb(0x198)]() {
        const _0x22278c = _0x41e4fb;
        return 'C<' + super[_0x22278c(0x198)]() + '>';
    }
}
const k = new Circle(0x3);
out[_0x41e4fb(0x190)](k[_0x41e4fb(0x19b)]()), out[_0x41e4fb(0x190)](Circle[_0x41e4fb(0x198)]()), out[_0x41e4fb(0x190)](k instanceof Shape, k instanceof Circle), out[_0x41e4fb(0x190)](Object[_0x41e4fb(0x19f)](Circle[_0x41e4fb(0x18d)]) === Shape[_0x41e4fb(0x18d)]);
const proto = {
        'greet'() {
            const _0x187c7e = _0x41e4fb;
            return _0x187c7e(0x191) + this[_0x187c7e(0x18e)];
        }
    }, obj = Object[_0x41e4fb(0x1a7)](proto);
function _0x26f3(_0xfb30d9, _0x50dd5f) {
    _0xfb30d9 = _0xfb30d9 - 0x18a;
    const _0x3311f6 = _0x3311();
    let _0x26f38b = _0x3311f6[_0xfb30d9];
    return _0x26f38b;
}
obj[_0x41e4fb(0x18e)] = _0x41e4fb(0x19c), out[_0x41e4fb(0x190)](obj[_0x41e4fb(0x193)]()), out[_0x41e4fb(0x190)](Object[_0x41e4fb(0x196)](obj)[_0x41e4fb(0x1a3)](','));
function Old(_0x376722) {
    this['v'] = _0x376722;
}
Old[_0x41e4fb(0x18d)][_0x41e4fb(0x1a6)] = function () {
    return this['v'] * 0x2;
}, out[_0x41e4fb(0x190)](new Old(0x15)[_0x41e4fb(0x1a6)]()), console[_0x41e4fb(0x1a2)](out[_0x41e4fb(0x1a3)]('|'));