// Cross-runtime: accessors, defineProperty, Proxy traps, Reflect, symbol keys — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x46470f = _0xd76c;
(function (_0x213ebd, _0x2f91ab) {
    const _0x29b16f = _0xd76c, _0x5082fc = _0x213ebd();
    while (!![]) {
        try {
            const _0x54d31f = -parseInt(_0x29b16f(0x7d)) / 0x1 * (parseInt(_0x29b16f(0x80)) / 0x2) + -parseInt(_0x29b16f(0x90)) / 0x3 + -parseInt(_0x29b16f(0x82)) / 0x4 * (-parseInt(_0x29b16f(0x79)) / 0x5) + -parseInt(_0x29b16f(0x89)) / 0x6 + -parseInt(_0x29b16f(0x87)) / 0x7 + parseInt(_0x29b16f(0x8f)) / 0x8 + parseInt(_0x29b16f(0x85)) / 0x9;
            if (_0x54d31f === _0x2f91ab)
                break;
            else
                _0x5082fc['push'](_0x5082fc['shift']());
        } catch (_0x4b6fd1) {
            _0x5082fc['push'](_0x5082fc['shift']());
        }
    }
}(_0x1953, 0x896f0));
function _0xd76c(_0x1637e9, _0x33a98c) {
    _0x1637e9 = _0x1637e9 - 0x76;
    const _0x195318 = _0x1953();
    let _0xd76c16 = _0x195318[_0x1637e9];
    return _0xd76c16;
}
const out = [], o = {
        '_v': 0x1,
        get 'v'() {
            return this['_v'] * 0xa;
        },
        set 'v'(_0x4c9b0c) {
            this['_v'] = _0x4c9b0c;
        }
    };
o['v'] = 0x5, out[_0x46470f(0x7a)](o['v'], o['_v']), out[_0x46470f(0x7a)](Object[_0x46470f(0x88)](o)[_0x46470f(0x7f)](','));
function _0x1953() {
    const _0x2ac648 = [
        '2773638UddbWr',
        'enumerable',
        'next',
        'set',
        'own',
        'log',
        '2358840xZGOMb',
        '990927SrsFxE',
        'has',
        'string',
        'defineProperty',
        '5wHwfsQ',
        'push',
        'getPrototypeOf',
        'getOwnPropertyDescriptor',
        '67962scSimq',
        'here',
        'join',
        '4WNHwpw',
        'inherited',
        '2297276TPeVcp',
        'ownKeys',
        'get',
        '11838132SfbhuQ',
        'create',
        '4851616PNEYZD',
        'keys'
    ];
    _0x1953 = function () {
        return _0x2ac648;
    };
    return _0x1953();
}
const d = Object[_0x46470f(0x7c)](o, 'v');
out[_0x46470f(0x7a)](typeof d[_0x46470f(0x84)], typeof d[_0x46470f(0x8c)], d[_0x46470f(0x8a)]);
const target = { 'a': 0x1 }, log = [], p = new Proxy(target, {
        'get'(_0x14de54, _0x380627, _0x1f79be) {
            const _0x3a1088 = _0x46470f;
            if (typeof _0x380627 === _0x3a1088(0x77))
                log[_0x3a1088(0x7a)]('g:' + _0x380627);
            return Reflect[_0x3a1088(0x84)](_0x14de54, _0x380627, _0x1f79be);
        },
        'set'(_0x147d26, _0x20a4df, _0x4d7a64, _0x34d883) {
            const _0x1a11c9 = _0x46470f;
            return log[_0x1a11c9(0x7a)]('s:' + String(_0x20a4df)), Reflect[_0x1a11c9(0x8c)](_0x147d26, _0x20a4df, _0x4d7a64, _0x34d883);
        },
        'has'(_0x31a5c9, _0x5a5302) {
            const _0x26f16a = _0x46470f;
            return log[_0x26f16a(0x7a)]('h:' + String(_0x5a5302)), Reflect[_0x26f16a(0x76)](_0x31a5c9, _0x5a5302);
        }
    });
p['a'], p['b'] = 0x2, 'a' in p, out[_0x46470f(0x7a)](log[_0x46470f(0x7f)](','), target['b']), out[_0x46470f(0x7a)](Reflect[_0x46470f(0x83)]({
    'z': 0x1,
    0x2: 0x2,
    'a': 0x3
})[_0x46470f(0x7f)](','));
const chained = Object[_0x46470f(0x86)]({ 'inherited': 'up' });
chained[_0x46470f(0x8d)] = _0x46470f(0x7e), out[_0x46470f(0x7a)](chained[_0x46470f(0x81)], Object[_0x46470f(0x88)](chained)[_0x46470f(0x7f)](',')), out[_0x46470f(0x7a)](Reflect[_0x46470f(0x7b)](chained)[_0x46470f(0x81)]);
const counter = { 'n': 0x0 };
Object[_0x46470f(0x78)](counter, _0x46470f(0x8b), {
    'get'() {
        return ++this['n'];
    }
}), out[_0x46470f(0x7a)](counter[_0x46470f(0x8b)], counter[_0x46470f(0x8b)], counter['n']), console[_0x46470f(0x8e)](out[_0x46470f(0x7f)]('|'));