// Cross-runtime: array methods, sort, holes, reduce chains, groupBy — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const l = c;
(function (d, e) {
    const k = c, f = d();
    while (!![]) {
        try {
            const g = -parseInt(k(0x102)) / 0x1 + -parseInt(k(0x108)) / 0x2 + parseInt(k(0x10b)) / 0x3 * (parseInt(k(0x107)) / 0x4) + -parseInt(k(0xfa)) / 0x5 + -parseInt(k(0x116)) / 0x6 * (-parseInt(k(0xf9)) / 0x7) + -parseInt(k(0x104)) / 0x8 * (-parseInt(k(0x111)) / 0x9) + parseInt(k(0x113)) / 0xa * (parseInt(k(0x11b)) / 0xb);
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(b, 0xcba50));
const out = [], a = [
        0x5,
        0x1,
        0x4,
        0x2,
        0x3
    ];
out[l(0x105)]([...a][l(0x106)]()[l(0xff)](','), [...a][l(0x106)]((d, e) => d - e)['join'](',')), out[l(0x105)](a['filter'](d => d % 0x2)[l(0x10f)](d => d * d)[l(0x118)]((d, e) => d + e, 0x0)), out[l(0x105)](a[l(0xfc)](d => d < 0x4), a[l(0x101)](d => d < 0x4)), out[l(0x105)]([[
        0x1,
        [
            0x2,
            [0x3]
        ]
    ]][l(0xfd)](0x2)[l(0xff)](','), [
    0x1,
    0x2
]['flatMap'](d => [
    d,
    d * 0xa
])['join'](','));
const holes = [
    0x1,
    ,
    0x3
];
function c(a, d) {
    a = a - 0xf9;
    const e = b();
    let f = e[a];
    return f;
}
out[l(0x105)](holes['length'], 0x1 in holes, JSON[l(0x11c)](holes), holes[l(0x10f)](d => d)[l(0x119)]), out['push'](Array[l(0x117)]({ 'length': 0x3 }, (d, e) => e * 0x2)[l(0xff)](',')), out['push'](Array['of'](0x7, 0x8)['join'](','), [...l(0x112)][l(0xff)]('-')), out[l(0x105)]([
    0x3,
    0x1,
    0x2
][l(0xfb)]()[l(0xff)](','), [
    0x1,
    0x2,
    0x3
][l(0x103)]()['join'](',')), out[l(0x105)]([
    0x1,
    0x2,
    0x3
][l(0x10c)](0x1, 0x9)[l(0xff)](','), [
    0x1,
    0x2,
    0x3
]['at'](-0x1));
const grouped = Object[l(0x100)]([
    0x1,
    0x2,
    0x3,
    0x4,
    0x5
], d => d % 0x2 ? l(0x11a) : l(0x114));
out[l(0x105)](Object[l(0x10a)](grouped)['join'](','), grouped[l(0x11a)][l(0xff)]('')), out['push']([
    0x1,
    0x2,
    0x3
][l(0x10e)](0x2), [
    0x1,
    0x2,
    0x3
][l(0xfe)](0x9));
let sum = 0x0;
function b() {
    const n = [
        'yUxUf',
        '126tnEYDo',
        'from',
        'reduce',
        'length',
        'odd',
        '237963cczORV',
        'stringify',
        '370811ywwbpG',
        '8026455CUZsmY',
        'toSorted',
        'findLast',
        'flat',
        'indexOf',
        'join',
        'groupBy',
        'findLastIndex',
        '1244879wpmPqX',
        'toReversed',
        '900392bcdXBF',
        'push',
        'sort',
        '1374908ExvjxC',
        '72822bFeXnF',
        'log',
        'keys',
        '12zpiDxF',
        'with',
        'cpQFE',
        'includes',
        'map',
        'forEach',
        '45NVcEsz',
        'abc',
        '310LLvamy',
        'even'
    ];
    b = function () {
        return n;
    };
    return b();
}
[
    0x1,
    0x2,
    0x3
][l(0x110)](function (d, e, f) {
    const m = l, g = {
            'cpQFE': function (h, j) {
                return h + j;
            },
            'yUxUf': function (h, j) {
                return h * j;
            }
        };
    sum += g[m(0x10d)](g[m(0x115)](d, e), f[m(0x119)]);
}), out[l(0x105)](sum), console[l(0x109)](out[l(0xff)]('|'));