// Cross-runtime: numeric coercion, bitwise, precedence, comparison — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
function _0x1f25() {
    const _0x5c63f6 = [
        'log',
        'min',
        'toString',
        '12235168cpOUsa',
        'join',
        '20gmMJtQ',
        '3652704vBtFEI',
        'toFixed',
        '343BsPdFv',
        '3099009sJWxSV',
        '7548885SDQVtC',
        '3.5',
        'max',
        '6260675kHmfen',
        '2GOkHnc',
        '163266AuDvDu',
        'isInteger',
        'MAX_SAFE_INTEGER',
        '548560ynxwYs',
        'push',
        '0b101'
    ];
    _0x1f25 = function () {
        return _0x5c63f6;
    };
    return _0x1f25();
}
const _0x436730 = _0x3f2b;
function _0x3f2b(_0x388171, _0xbdd497) {
    _0x388171 = _0x388171 - 0xc5;
    const _0x1f25e0 = _0x1f25();
    let _0x3f2b41 = _0x1f25e0[_0x388171];
    return _0x3f2b41;
}
(function (_0x511e51, _0xd75bc5) {
    const _0x42ef9c = _0x3f2b, _0x1b513c = _0x511e51();
    while (!![]) {
        try {
            const _0x22cd88 = -parseInt(_0x42ef9c(0xcb)) / 0x1 + parseInt(_0x42ef9c(0xc7)) / 0x2 * (parseInt(_0x42ef9c(0xd7)) / 0x3) + parseInt(_0x42ef9c(0xd4)) / 0x4 + parseInt(_0x42ef9c(0xc6)) / 0x5 + -parseInt(_0x42ef9c(0xc8)) / 0x6 * (-parseInt(_0x42ef9c(0xd6)) / 0x7) + -parseInt(_0x42ef9c(0xd1)) / 0x8 + parseInt(_0x42ef9c(0xd8)) / 0x9 * (-parseInt(_0x42ef9c(0xd3)) / 0xa);
            if (_0x22cd88 === _0xd75bc5)
                break;
            else
                _0x1b513c['push'](_0x1b513c['shift']());
        } catch (_0x340646) {
            _0x1b513c['push'](_0x1b513c['shift']());
        }
    }
}(_0x1f25, 0xbd7e7));
const out = [];
out[_0x436730(0xcc)](0.1 + 0.2, (0.1 + 0.2)[_0x436730(0xd5)](0x2)), out[_0x436730(0xcc)](0x1 / 0x0, -0x1 / 0x0, 0x0 / 0x0), out[_0x436730(0xcc)](0x5 % 0x3, -0x5 % 0x3, 0x2 ** 0xa), out[_0x436730(0xcc)](0x7 & 0x3, 0x7 | 0x8, 0x7 ^ 0x5, ~0x7, 0x1 << 0x5, -0x10 >> 0x2, -0x10 >>> 0x1c), out[_0x436730(0xcc)]('5' * '2', '5' + 0x2, 0x5 + '2', +_0x436730(0xd9), -'2'), out[_0x436730(0xcc)]([] + [], [] + {}, 0x1 + null, 0x1 + undefined), out[_0x436730(0xcc)](null == undefined, null === undefined, NaN === NaN), out[_0x436730(0xcc)](Math[_0x436730(0xc5)](0x1, 0x9, 0x3), Math[_0x436730(0xcf)](...[
    0x4,
    0x2,
    0x8
])), out[_0x436730(0xcc)](0xff[_0x436730(0xd0)](0x10), parseInt('ff', 0x10), Number(_0x436730(0xcd))), out[_0x436730(0xcc)](Number[_0x436730(0xc9)](0x5), Number[_0x436730(0xca)]);
let i = 0x5;
out[_0x436730(0xcc)](i++ + ++i, i), console[_0x436730(0xce)](out[_0x436730(0xd2)]('|'));