// Cross-runtime: error hierarchy, rethrow, nested try, custom errors, cause — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const o = b;
(function (c, d) {
    const m = b, f = c();
    while (!![]) {
        try {
            const h = -parseInt(m(0xb9)) / 0x1 + -parseInt(m(0xbc)) / 0x2 * (-parseInt(m(0xbf)) / 0x3) + -parseInt(m(0xc6)) / 0x4 + -parseInt(m(0xcd)) / 0x5 * (parseInt(m(0xc8)) / 0x6) + parseInt(m(0xc0)) / 0x7 * (-parseInt(m(0xbd)) / 0x8) + parseInt(m(0xb3)) / 0x9 * (parseInt(m(0xb0)) / 0xa) + parseInt(m(0xb8)) / 0xb * (parseInt(m(0xaf)) / 0xc);
            if (h === d)
                break;
            else
                f['push'](f['shift']());
        } catch (l) {
            f['push'](f['shift']());
        }
    }
}(a, 0x88a7a));
const out = [];
class AppError extends Error {
    constructor(c, d) {
        const n = b, f = { 'OfyEr': n(0xcb) };
        super(c), this[n(0xc1)] = f['OfyEr'], this[n(0xc5)] = d;
    }
}
try {
    throw new AppError(o(0xc4), 0x2a);
} catch (g) {
    out[o(0xc7)](g[o(0xc1)], g['message'], g['code'], g instanceof Error, g instanceof AppError);
}
function nested(c) {
    const p = o, d = {
            'qworr': p(0xc9),
            'uTOIU': function (f, h) {
                return f + h;
            },
            'rtufK': p(0xb5)
        };
    try {
        try {
            if (c)
                throw new TypeError(d['qworr']);
            return 'no';
        } catch (f) {
            throw new RangeError(d[p(0xb2)](d[p(0xca)], f[p(0xcc)]));
        } finally {
            out['push']('f1');
        }
    } catch (h) {
        return d['uTOIU'](d[p(0xb2)](h[p(0xc1)], ':'), h[p(0xcc)]);
    } finally {
        out[p(0xc7)]('f2');
    }
}
out[o(0xc7)](nested(0x1), nested(0x0));
function b(c, d) {
    c = c - 0xaf;
    const e = a();
    let f = e[c];
    return f;
}
const withCause = new Error(o(0xb7), { 'cause': new Error('root') });
out[o(0xc7)](withCause[o(0xc2)][o(0xcc)]);
try {
    null['x'];
} catch (i) {
    out[o(0xc7)](i[o(0xc3)]['name']);
}
function a() {
    const r = [
        'inner',
        'rtufK',
        'AppError',
        'message',
        '5070zyfcSP',
        'log',
        '6481644TmBjmB',
        '10jEPmbK',
        'mNBUk',
        'uTOIU',
        '8126721qsIaQf',
        'join',
        'wrapped:',
        'parse',
        'outer',
        '22ZjEXOE',
        '799353jzNJMu',
        'map',
        '{bad',
        '47516rKavLy',
        '7032SuXXBN',
        'caught',
        '108TGuVoS',
        '1225TRmmGI',
        'name',
        'cause',
        'constructor',
        'bad',
        'code',
        '3963980ZKhvHB',
        'push',
        '1980ujXUaD'
    ];
    a = function () {
        return r;
    };
    return a();
}
try {
    undefined();
} catch (j) {
    out[o(0xc7)](j['constructor'][o(0xc1)]);
}
try {
    JSON[o(0xb6)](o(0xbb));
} catch (k) {
    out[o(0xc7)](k['constructor'][o(0xc1)]);
}
out[o(0xc7)]([
    0x1,
    0x2
][o(0xba)](c => {
    const q = o, d = {
            'wEAOP': function (f, h) {
                return f === h;
            },
            'mNBUk': q(0xbe)
        };
    try {
        if (d['wEAOP'](c, 0x1))
            throw new Error('s');
        return 'ok';
    } catch {
        return d[q(0xb1)];
    }
})['join'](',')), console[o(0xce)](out[o(0xb4)]('|'));