// Cross-runtime: classes, prototypes, getters, static, super, instanceof — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const j = b;
(function (c, d) {
    const h = b, e = c();
    while (!![]) {
        try {
            const f = parseInt(h(0x17e)) / 0x1 * (-parseInt(h(0x165)) / 0x2) + parseInt(h(0x16a)) / 0x3 * (parseInt(h(0x17a)) / 0x4) + -parseInt(h(0x17f)) / 0x5 * (parseInt(h(0x173)) / 0x6) + parseInt(h(0x16d)) / 0x7 + -parseInt(h(0x172)) / 0x8 * (-parseInt(h(0x166)) / 0x9) + parseInt(h(0x16b)) / 0xa * (-parseInt(h(0x17d)) / 0xb) + -parseInt(h(0x16f)) / 0xc * (-parseInt(h(0x180)) / 0xd);
            if (f === d)
                break;
            else
                e['push'](e['shift']());
        } catch (g) {
            e['push'](e['shift']());
        }
    }
}(a, 0x2598a));
const out = [];
function b(c, d) {
    c = c - 0x15e;
    const e = a();
    let f = e[c];
    return f;
}
class Shape {
    constructor(c) {
        const i = b;
        this[i(0x167)] = c;
    }
    get [j(0x179)]() {
        const l = j, c = {
                'ejZGS': function (d, e) {
                    return d + e;
                },
                'wCmIl': l(0x178)
            };
        return c['ejZGS'](c[l(0x15f)], this[l(0x167)]);
    }
    static [j(0x161)]() {
        const c = { 'Xnwln': 'Shape' };
        return c['Xnwln'];
    }
    [j(0x171)]() {
        const m = j;
        return this[m(0x179)];
    }
}
class Circle extends Shape {
    constructor(c) {
        const n = j, d = { 'oWOEy': 'circle' };
        super(d[n(0x169)]), this['r'] = c;
    }
    get ['label']() {
        const o = j, c = {
                'qGLlQ': function (d, e) {
                    return d + e;
                },
                'niAJl': function (d, e) {
                    return d + e;
                }
            };
        return c[o(0x17c)](c[o(0x162)](super['label'], ':'), this['r']);
    }
    static [j(0x161)]() {
        const p = j, c = {
                'bmzSy': function (d, e) {
                    return d + e;
                }
            };
        return c['bmzSy'](c[p(0x176)]('C<', super[p(0x161)]()), '>');
    }
}
const k = new Circle(0x3);
out['push'](k[j(0x171)]()), out['push'](Circle[j(0x161)]()), out['push'](k instanceof Shape, k instanceof Circle), out[j(0x175)](Object[j(0x163)](Circle[j(0x177)]) === Shape['prototype']);
function a() {
    const r = [
        '344799poRWeH',
        'QpStV',
        '96NLmcsA',
        'twice',
        'describe',
        '8peaNEN',
        '81798nAnZBl',
        'hi\x20',
        'push',
        'bmzSy',
        'prototype',
        'shape:',
        'label',
        '4aSjGHs',
        'create',
        'qGLlQ',
        '33CaENoT',
        '3nowhva',
        '75qnLmWc',
        '682058KJtJPE',
        'keys',
        'join',
        'wCmIl',
        'who',
        'kind',
        'niAJl',
        'getPrototypeOf',
        'you',
        '182498MegjDW',
        '2178261KlCqTt',
        'name',
        'greet',
        'oWOEy',
        '647763Wwmcck',
        '982330fUWuYF',
        'log'
    ];
    a = function () {
        return r;
    };
    return a();
}
const proto = {
        'greet'() {
            const q = j, c = {
                    'QpStV': function (d, e) {
                        return d + e;
                    },
                    'oaFek': q(0x174)
                };
            return c[q(0x16e)](c['oaFek'], this[q(0x160)]);
        }
    }, obj = Object[j(0x17b)](proto);
obj[j(0x160)] = j(0x164), out[j(0x175)](obj[j(0x168)]()), out['push'](Object[j(0x181)](obj)['join'](','));
function Old(c) {
    this['v'] = c;
}
Old[j(0x177)]['twice'] = function () {
    const c = {
        'aMNlX': function (d, e) {
            return d * e;
        }
    };
    return c['aMNlX'](this['v'], 0x2);
}, out[j(0x175)](new Old(0x15)[j(0x170)]()), console[j(0x16c)](out[j(0x15e)]('|'));