// Cross-runtime: destructuring, defaults, rest/spread, computed keys — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const l = c;
(function (d, e) {
    const j = c, g = d();
    while (!![]) {
        try {
            const h = -parseInt(j(0x92)) / 0x1 + -parseInt(j(0x8e)) / 0x2 + parseInt(j(0x93)) / 0x3 + parseInt(j(0x8f)) / 0x4 + -parseInt(j(0x8b)) / 0x5 + parseInt(j(0x86)) / 0x6 + -parseInt(j(0x91)) / 0x7 * (-parseInt(j(0x89)) / 0x8);
            if (h === e)
                break;
            else
                g['push'](g['shift']());
        } catch (i) {
            g['push'](g['shift']());
        }
    }
}(b, 0x75b0b));
function b() {
    const r = [
        '677937vhPglA',
        'map',
        'keys',
        'entries',
        '3470484BdwQgq',
        'length',
        'OKNaD',
        '40NMEnRp',
        'dyn',
        '451740VHiBjp',
        'push',
        'DNnRy',
        '1081368rwQJJL',
        '3103296zjIfBG',
        'join',
        '300503CxBXJe',
        '681771Cucusd'
    ];
    b = function () {
        return r;
    };
    return b();
}
const out = [], {
        a,
        b: bee = 0x9,
        ...rest
    } = {
        'a': 0x1,
        'c': 0x3,
        'd': 0x4
    };
out['push'](a, bee, JSON['stringify'](rest));
const [p, , q = 0x7, ...tail] = [
    0x1,
    0x2,
    undefined,
    0x4,
    0x5
];
out[l(0x8c)](p, q, tail[l(0x90)](','));
function f({
    x: x = 0x1,
    y: y = 0x2
} = {}, ...d) {
    const n = l, e = {
            'DNnRy': function (g, h) {
                return g + h;
            },
            'OKNaD': function (g, h) {
                return g + h;
            }
        };
    return e[n(0x8d)](e[n(0x88)](x, y), d[n(0x87)]);
}
out[l(0x8c)](f(), f({ 'x': 0xa }, 0x1, 0x2));
const key = l(0x8a), o = {
        [key + '1']: 'v1',
        [key + '2']: 'v2'
    };
out[l(0x8c)](Object[l(0x95)](o)[l(0x90)](','));
const merged = {
    ...o,
    'extra': !![]
};
out[l(0x8c)](Object['keys'](merged)[l(0x87)]);
function* gen() {
    yield 0x1, yield 0x2, yield 0x3;
}
function c(a, d) {
    a = a - 0x86;
    const e = b();
    let f = e[a];
    return f;
}
out[l(0x8c)]([...gen()][l(0x90)]('+'));
const [g1, ...grest] = gen();
out[l(0x8c)](g1, grest[l(0x90)]('.'));
const m = new Map([
    [
        'k',
        0x1
    ],
    [
        'j',
        0x2
    ]
]);
out[l(0x8c)]([...m[l(0x96)]()][l(0x94)](([d, e]) => d + e)[l(0x90)](','));
for (const [k, v] of m)
    out[l(0x8c)](k + '=' + v);
console['log'](out['join']('|'));