// Cross-runtime: numeric coercion, bitwise, precedence, comparison — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const j = b;
(function (c, d) {
    const h = b, e = c();
    while (!![]) {
        try {
            const f = parseInt(h(0x7e)) / 0x1 + -parseInt(h(0x84)) / 0x2 * (-parseInt(h(0x77)) / 0x3) + -parseInt(h(0x73)) / 0x4 + parseInt(h(0x80)) / 0x5 * (parseInt(h(0x74)) / 0x6) + -parseInt(h(0x79)) / 0x7 * (-parseInt(h(0x85)) / 0x8) + -parseInt(h(0x83)) / 0x9 * (-parseInt(h(0x7d)) / 0xa) + -parseInt(h(0x7b)) / 0xb;
            if (f === d)
                break;
            else
                e['push'](e['shift']());
        } catch (g) {
            e['push'](e['shift']());
        }
    }
}(a, 0x67833));
const out = [];
function b(c, d) {
    c = c - 0x72;
    const e = a();
    let f = e[c];
    return f;
}
function a() {
    const k = [
        'isInteger',
        '87606RtqvXe',
        '600798RfmltB',
        '256rygZEZ',
        'join',
        '2572700UGMbOy',
        '6ekijfG',
        'toFixed',
        'MAX_SAFE_INTEGER',
        '3gnwBfn',
        'max',
        '103558YUqayw',
        'toString',
        '14698409wuopHr',
        'log',
        '290ThWONk',
        '797385KdTpRg',
        'min',
        '2749515AKtEht',
        'push'
    ];
    a = function () {
        return k;
    };
    return a();
}
out['push'](0.1 + 0.2, (0.1 + 0.2)[j(0x75)](0x2)), out[j(0x81)](0x1 / 0x0, -0x1 / 0x0, 0x0 / 0x0), out[j(0x81)](0x5 % 0x3, -0x5 % 0x3, 0x2 ** 0xa), out[j(0x81)](0x7 & 0x3, 0x7 | 0x8, 0x7 ^ 0x5, ~0x7, 0x1 << 0x5, -0x10 >> 0x2, -0x10 >>> 0x1c), out[j(0x81)]('5' * '2', '5' + 0x2, 0x5 + '2', +'3.5', -'2'), out['push']([] + [], [] + {}, 0x1 + null, 0x1 + undefined), out['push'](null == undefined, null === undefined, NaN === NaN), out['push'](Math[j(0x78)](0x1, 0x9, 0x3), Math[j(0x7f)](...[
    0x4,
    0x2,
    0x8
])), out[j(0x81)](0xff[j(0x7a)](0x10), parseInt('ff', 0x10), Number('0b101')), out[j(0x81)](Number[j(0x82)](0x5), Number[j(0x76)]);
let i = 0x5;
out['push'](i++ + ++i, i), console[j(0x7c)](out[j(0x72)]('|'));