// Cross-runtime: labels, switch fallthrough, try/catch/finally, short-circuit — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (string array + base64 + wrappers + split strings) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
(function (_0x39fddf, _0xc91d47) {
    const _0x42871d = _0x39fddf();
    function _0x31f8fe(_0x3265ad, _0x9f21ce) {
        return _0x1ab3(_0x9f21ce - -0x28a, _0x3265ad);
    }
    function _0x3cde0b(_0x458249, _0x60505d) {
        return _0x1ab3(_0x458249 - -0x319, _0x60505d);
    }
    while (!![]) {
        try {
            const _0x357846 = parseInt(_0x3cde0b(-0x29c, -0x292)) / 0x1 * (-parseInt(_0x31f8fe(-0x207, -0x20b)) / 0x2) + parseInt(_0x3cde0b(-0x2a3, -0x29b)) / 0x3 + parseInt(_0x31f8fe(-0x215, -0x20a)) / 0x4 + parseInt(_0x31f8fe(-0x218, -0x21a)) / 0x5 + -parseInt(_0x3cde0b(-0x2a6, -0x2ac)) / 0x6 + parseInt(_0x31f8fe(-0x216, -0x220)) / 0x7 * (-parseInt(_0x31f8fe(-0x20f, -0x20f)) / 0x8) + parseInt(_0x3cde0b(-0x29b, -0x2a7)) / 0x9 * (parseInt(_0x3cde0b(-0x2a1, -0x2ad)) / 0xa);
            if (_0x357846 === _0xc91d47)
                break;
            else
                _0x42871d['push'](_0x42871d['shift']());
        } catch (_0x5dcc3a) {
            _0x42871d['push'](_0x42871d['shift']());
        }
    }
}(_0xcae1, 0xe5b55));
const out = [];
_0x5c161a:
    for (let i = 0x0; i < 0x4; i++) {
        for (let j = 0x0; j < 0x4; j++) {
            if (j === 0x2)
                continue _0x5c161a;
            if (i === 0x3)
                break _0x5c161a;
            out[_0x4bad8c(-0x182, -0x17d) + 'h'](i + '' + j);
        }
    }
function sw(_0x339de8) {
    let _0xb33f5a = '';
    switch (_0x339de8) {
    case 0x0:
        _0xb33f5a += 'z';
    case 0x1:
        _0xb33f5a += 'o';
        break;
    case 0x2:
        _0xb33f5a += 't';
        break;
    default:
        _0xb33f5a += 'd';
    }
    return _0xb33f5a;
}
out[_0x4bad8c(-0x182, -0x18c) + 'h'](sw(0x0) + sw(0x1) + sw(0x2) + sw(0x9));
function tf(_0x17c43c) {
    function _0x22cc4c(_0x3e2b8e, _0x32ab84) {
        return _0x4bad8c(_0x3e2b8e - 0x50d, _0x32ab84);
    }
    function _0x33dadf(_0x2918f3, _0x2e686) {
        return _0x4bad8c(_0x2e686 - 0x1a2, _0x2918f3);
    }
    try {
        if (_0x17c43c === 0x0)
            throw new RangeError(_0x33dadf(0x33, 0x2a) + 'o');
        return 'ok' + _0x17c43c;
    } catch (_0x368c25) {
        return _0x368c25[_0x22cc4c(0x39f, 0x3a5) + _0x22cc4c(0x39a, 0x39b) + _0x33dadf(0x32, 0x28) + 'or'][_0x22cc4c(0x38c, 0x38b) + 'e'];
    } finally {
        out[_0x22cc4c(0x38b, 0x397) + 'h'](_0x33dadf(0x13, 0x1e) + _0x17c43c);
    }
}
function _0x4bad8c(_0x41f2ac, _0x50e55d) {
    return _0x1ab3(_0x41f2ac - -0x1ef, _0x50e55d);
}
function _0x1ab3(_0x72b27e, _0x1f8d74) {
    _0x72b27e = _0x72b27e - 0x6a;
    const _0xcae151 = _0xcae1();
    let _0x1ab341 = _0xcae151[_0x72b27e];
    if (_0x1ab3['LScLgs'] === undefined) {
        var _0x2eb09a = function (_0x25d5fd) {
            const _0x4736d8 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';
            let _0x5c161a = '', _0x339de8 = '';
            for (let _0xb33f5a = 0x0, _0x17c43c, _0x368c25, _0x591a9d = 0x0; _0x368c25 = _0x25d5fd['charAt'](_0x591a9d++); ~_0x368c25 && (_0x17c43c = _0xb33f5a % 0x4 ? _0x17c43c * 0x40 + _0x368c25 : _0x368c25, _0xb33f5a++ % 0x4) ? _0x5c161a += String['fromCharCode'](0xff & _0x17c43c >> (-0x2 * _0xb33f5a & 0x6)) : 0x0) {
                _0x368c25 = _0x4736d8['indexOf'](_0x368c25);
            }
            for (let _0x161aaf = 0x0, _0x5c38cf = _0x5c161a['length']; _0x161aaf < _0x5c38cf; _0x161aaf++) {
                _0x339de8 += '%' + ('00' + _0x5c161a['charCodeAt'](_0x161aaf)['toString'](0x10))['slice'](-0x2);
            }
            return decodeURIComponent(_0x339de8);
        };
        _0x1ab3['TVBkil'] = _0x2eb09a, _0x1ab3['PzcXik'] = {}, _0x1ab3['LScLgs'] = !![];
    }
    const _0x4a6b7d = _0xcae151[0x0], _0x44e6f3 = _0x72b27e + _0x4a6b7d, _0xd099d1 = _0x1ab3['PzcXik'][_0x44e6f3];
    return !_0xd099d1 ? (_0x1ab341 = _0x1ab3['TVBkil'](_0x1ab341), _0x1ab3['PzcXik'][_0x44e6f3] = _0x1ab341) : _0x1ab341 = _0xd099d1, _0x1ab341;
}
out[_0x3ae9d0(-0xc1, -0xc8) + 'h'](tf(0x0), tf(0x1));
let a = null;
function _0x3ae9d0(_0x243946, _0x5adfa2) {
    return _0x1ab3(_0x5adfa2 - -0x135, _0x243946);
}
out[_0x3ae9d0(-0xc6, -0xc8) + 'h'](a ?? _0x3ae9d0(-0xb7, -0xbc) + 't', a?.[_0x4bad8c(-0x180, -0x17c) + 'p']?.['er'], 0x0 || _0x3ae9d0(-0xc8, -0xc4) + 'sy', 0x1 && _0x3ae9d0(-0xca, -0xc1) + _0x3ae9d0(-0xc2, -0xc9));
function _0xcae1() {
    const _0xb45e9d = [
        'ChvZ',
        'BMfT',
        'zgvL',
        'mta5mZKXmhnct2jivq',
        'zMfS',
        'Bg9N',
        'nZK3ode3nMnpsgv3Aa',
        'Dhj1',
        'Dwn0',
        'nti3mJG3nvrTzhvqDa',
        'EMvY',
        'mtbxrhDsu3O',
        'zgzS',
        'AM9P',
        'mZeYv3Pfvxrk',
        'C3rY',
        'muXRtu5orq',
        'mtq3ote3mJvdExrnsvG',
        'mJaXotq5nfDLseHTuW',
        'mJm0otCWnfDxuM1srW',
        'y29U',
        'mty2mZKWqu94CwXU',
        'zMLU',
        'DgH5'
    ];
    _0xcae1 = function () {
        return _0xb45e9d;
    };
    return _0xcae1();
}
let n = 0x0;
do {
    n += 0x2;
} while (n < 0x7);
out[_0x3ae9d0(-0xcf, -0xc8) + 'h'](n), console[_0x3ae9d0(-0xc5, -0xc3)](out[_0x4bad8c(-0x175, -0x173) + 'n']('|'));