// Cross-runtime: closures, per-iteration bindings, shadowing, IIFE chains — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x249a8f = _0x1617;
(function (_0xd2dbf6, _0x168ca2) {
    const _0x43134f = _0x1617, _0x356294 = _0xd2dbf6();
    while (!![]) {
        try {
            const _0x283486 = -parseInt(_0x43134f(0xec)) / 0x1 + -parseInt(_0x43134f(0xe2)) / 0x2 + parseInt(_0x43134f(0xe9)) / 0x3 * (-parseInt(_0x43134f(0xeb)) / 0x4) + -parseInt(_0x43134f(0xf3)) / 0x5 * (-parseInt(_0x43134f(0xed)) / 0x6) + parseInt(_0x43134f(0xe3)) / 0x7 * (-parseInt(_0x43134f(0xf5)) / 0x8) + parseInt(_0x43134f(0xee)) / 0x9 + parseInt(_0x43134f(0xea)) / 0xa;
            if (_0x283486 === _0x168ca2)
                break;
            else
                _0x356294['push'](_0x356294['shift']());
        } catch (_0x187d8c) {
            _0x356294['push'](_0x356294['shift']());
        }
    }
}(_0x4996, 0x424be));
const out = [], fns = [];
for (let i = 0x0; i < 0x4; i++)
    fns[_0x249a8f(0xf1)](() => i * 0x3);
out[_0x249a8f(0xf1)](fns[_0x249a8f(0xf2)](_0x9d1bf7 => _0x9d1bf7())[_0x249a8f(0xef)](','));
function counter(_0x4c69ae) {
    let _0x1d57fb = _0x4c69ae;
    return {
        'inc': () => ++_0x1d57fb,
        'get': () => _0x1d57fb
    };
}
function _0x4996() {
    const _0x1a3605 = [
        'get',
        'XAhsP',
        'outer',
        'inner',
        '3LrjSpq',
        '7289770FeBzLJ',
        '851068oXJXpN',
        '54019gWPsmd',
        '3324PVrPWQ',
        '2820978TPZNKc',
        'join',
        'ZzwFm',
        'push',
        'map',
        '2515VdaQvV',
        'inc',
        '16deLMOl',
        '513434vSgSei',
        '1841098VuTuAg',
        'log'
    ];
    _0x4996 = function () {
        return _0x1a3605;
    };
    return _0x4996();
}
const c = counter(0xa);
c[_0x249a8f(0xf4)](), c[_0x249a8f(0xf4)](), out[_0x249a8f(0xf1)](c[_0x249a8f(0xe5)]());
let x = _0x249a8f(0xe7);
function _0x1617(_0x55c329, _0x2f8678) {
    _0x55c329 = _0x55c329 - 0xe2;
    const _0x499657 = _0x4996();
    let _0x16176b = _0x499657[_0x55c329];
    return _0x16176b;
}
{
    let x = _0x249a8f(0xe8);
    out[_0x249a8f(0xf1)](x);
}
out[_0x249a8f(0xf1)](x), out[_0x249a8f(0xf1)](function (_0x4ce8f8) {
    return function (_0x57d427) {
        const _0x2ed4ee = _0x1617;
        if (_0x2ed4ee(0xe6) !== _0x2ed4ee(0xf0))
            return _0x4ce8f8 + _0x57d427;
        else {
            const _0x177ce6 = {};
            return _0x5e0308 => _0x177ce6[_0x5e0308] = (_0x177ce6[_0x5e0308] || 0x0) + 0x1;
        }
    }(0x5);
}(0x7));
const memo = ((() => {
    const _0x57fc92 = {};
    return _0x116b8f => _0x57fc92[_0x116b8f] = (_0x57fc92[_0x116b8f] || 0x0) + 0x1;
})());
memo('a'), memo('a'), memo('b'), out[_0x249a8f(0xf1)](memo('a') + ':' + memo('b')), console[_0x249a8f(0xe4)](out[_0x249a8f(0xef)]('|'));