// Cross-runtime: string methods, template literals, regex, replace callbacks — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const j = b;
(function (d, e) {
    const i = b, f = d();
    while (!![]) {
        try {
            const g = parseInt(i(0x11e)) / (-0x6e5 + 0xc16 + -0x530) * (parseInt(i(0x127)) / (-0xb6d + -0x1e7 * 0x3 + 0x1124)) + parseInt(i(0x11a)) / (-0x392 + 0x18aa + -0x1515) * (-parseInt(i(0x122)) / (-0x1cf9 + -0x13f * -0x9 + 0x11c6)) + parseInt(i(0x130)) / (-0x5b * -0x34 + -0x1 * 0x3f + -0x1238) + -parseInt(i(0x12b)) / (-0x83 * -0x2f + -0x2a * -0xbe + -0x3733 * 0x1) * (parseInt(i(0x12e)) / (-0x11aa * -0x1 + 0x1dad * -0x1 + 0x43 * 0x2e)) + parseInt(i(0x131)) / (-0x1 * 0x877 + 0x188b + -0x403 * 0x4) * (-parseInt(i(0x124)) / (-0x1e0 + 0x1 * 0x574 + 0x38b * -0x1)) + -parseInt(i(0x119)) / (0x1 * 0x1bdb + -0x2287 + 0x35b * 0x2) * (-parseInt(i(0x12d)) / (0x2446 + -0x17d * -0x19 + -0x4970)) + parseInt(i(0x125)) / (-0xbef + -0x179f + 0x239a);
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(a, -0x1011b5 + -0x197f * -0xf7 + -0x1 * -0x50277));
const out = [], s = j(0x12c);
out[j(0x129)](s[j(0x11c)]()[j(0x118)](-0xa * -0xbf + -0x173c + 0x5e * 0x2b, 0x17c4 + 0x20d7 + -0x3892)), out[j(0x129)](s[j(0x116)]('\x20')[j(0x12a)](d => d['length'])['join']('-')), out[j(0x129)](s[j(0x12f)](/(\w+) (\w+)/, j(0x126))), out[j(0x129)](s[j(0x12f)](/o/g, (d, e) => '[' + e + ']')), out[j(0x129)](/(?<adj>\w+) fox/[j(0x11f)](s)[j(0x123)]['adj']), out[j(0x129)]([...s[j(0x120)](/[A-Z]/g)][j(0x12a)](d => d[j(0x11b)])[j(0x128)](','));
function b(c, d) {
    c = c - (-0x5ea + -0x425 * -0x7 + 0xf5 * -0x17);
    const e = a();
    let f = e[c];
    return f;
}
const tag = (d, ...e) => d['raw'][j(0x128)]('#') + '/' + e['join']('+');
out[j(0x129)](tag`a${ -0x2335 + 0x1a1 * 0x6 + 0x197 * 0x10 }b${ 0x1bc0 + -0x5 * -0x737 + 0x11 * -0x3c1 }c`), out[j(0x129)](j(0x121)[j(0x11d)](0x3c4 * 0x7 + 0x224f + -0x3ca5, '-') + '|' + 'abc'['at'](-(0xb * -0x371 + 0x25 * 0x5f + 0x1821)));
const c = {};
function a() {
    const k = [
        'padStart',
        '2294PmZUZy',
        'exec',
        'matchAll',
        'abc',
        '28EYDuvy',
        'groups',
        '1431DfDqFf',
        '24789468tyzYnx',
        '$2\x20$1',
        '746lqxGKi',
        'join',
        'push',
        'map',
        '54TqcvBL',
        'The\x20quick\x20Brown\x20fox',
        '11OgPVwE',
        '840049dfkQyB',
        'replace',
        '1113510qgNdUW',
        '40952SSZRmU',
        'split',
        'log',
        'slice',
        '5041730zBeMCC',
        '371559YFbcjQ',
        'index',
        'toUpperCase'
    ];
    a = function () {
        return k;
    };
    return a();
}
c['q'] = 'he\x20said\x20\x22hi\x22', c['n'] = '\x0a', out['push'](JSON['stringify'](c)), console[j(0x117)](out['join']('|'));