// Cross-runtime: generators, yield*, the iterator protocol driven by hand — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const o = b;
function a() {
    const r = [
        'iend',
        '163081GvllWJ',
        '10393341OwtTmY',
        'iterator',
        'genfin',
        'value',
        '10810896JSbATr',
        '260oKrdKJ',
        '10626903AoVqmN',
        '31414570mfHFVw',
        'next',
        '6xrKPfb',
        'done',
        '3998410YPDLIK',
        'pre',
        'push',
        'stringify',
        '10YUDHDm',
        'join',
        'log',
        '26070PUCbND'
    ];
    a = function () {
        return r;
    };
    return a();
}
(function (d, e) {
    const l = b, h = d();
    while (!![]) {
        try {
            const i = parseInt(l(0x14e)) / (-0x1903 + 0x1 * 0x170 + 0x1794) * (-parseInt(l(0x15e)) / (-0xb * 0x1e9 + 0x170b * -0x1 + 0x3c * 0xbc)) + parseInt(l(0x161)) / (0x2 * 0xd33 + -0xeb1 * -0x1 + -0x3bc * 0xb) * (parseInt(l(0x154)) / (-0x47c + 0x5 * 0x7f + 0x205)) + -parseInt(l(0x15a)) / (-0x219 * -0x4 + -0x4b6 * 0x1 + -0x3a9) + -parseInt(l(0x158)) / (0x1fd1 * -0x1 + 0xe6e + 0x1169 * 0x1) * (parseInt(l(0x14f)) / (0x25fe + 0x1c69 + 0x760 * -0x9)) + parseInt(l(0x153)) / (-0x13c5 * 0x1 + 0x5ae + -0x2d3 * -0x5) + -parseInt(l(0x155)) / (0x6 * -0x12 + 0xf40 + -0xecb) + parseInt(l(0x156)) / (-0x8b1 * 0x1 + 0x1d37 + 0x45 * -0x4c);
            if (i === e)
                break;
            else
                h['push'](h['shift']());
        } catch (j) {
            h['push'](h['shift']());
        }
    }
}(a, 0x1 * 0x1639f3 + 0xa028b + -0x26 * 0x894b));
const out = [];
function* inner() {
    const m = b;
    return yield 'i1', yield 'i2', m(0x162);
}
function* outer() {
    const n = b;
    out[n(0x15c)](n(0x15b));
    const d = yield* inner();
    out[n(0x15c)]('got:' + d), yield 'o1';
}
out[o(0x15c)]([...outer()][o(0x15f)](','));
const it = inner();
out[o(0x15c)](JSON[o(0x15d)](it[o(0x157)]()), JSON[o(0x15d)](it['next']())), out[o(0x15c)](JSON[o(0x15d)](it[o(0x157)]()), JSON[o(0x15d)](it[o(0x157)]()));
function* counter() {
    let d = -0x1d03 * -0x1 + -0x5 * -0x745 + 0x1 * -0x415c;
    while (!![]) {
        const e = yield d;
        d += e === undefined ? 0xef7 + -0x1cea * -0x1 + -0x2be0 : e;
        if (d > -0xb * -0x237 + 0x63f * 0x2 + -0x24d5)
            return d;
    }
}
const c = counter();
out['push'](c['next']()[o(0x152)], c[o(0x157)](0xc4b + -0x1 * -0x220 + 0x1 * -0xe68)[o(0x152)], c[o(0x157)](0x1 * 0xb5 + 0x1 * -0x1bd + 0x10b)[o(0x152)]);
function* withFinally() {
    const p = o;
    try {
        yield 0x469 * 0x7 + -0x1 * 0x1b72 + 0x1b6 * -0x2, yield -0x29 * 0x2 + 0x6fc + -0x354 * 0x2;
    } finally {
        out['push'](p(0x151));
    }
}
const g = withFinally();
g[o(0x157)](), out['push'](JSON['stringify'](g['return']('bye')));
function b(c, d) {
    c = c - (-0x1c69 + 0x1 * 0x25e1 + 0x37 * -0x26);
    const e = a();
    let f = e[c];
    return f;
}
const f = {
        [Symbol[o(0x150)]]() {
            const q = o;
            let h = 0x6cb * -0x5 + -0x26ac + 0x48a3 * 0x1;
            const j = {};
            j[q(0x152)] = undefined, j[q(0x159)] = !![];
            const k = {};
            return k[q(0x157)] = () => h < 0x63d + -0xb2 * 0x1e + 0xea2 ? {
                'value': h++,
                'done': ![]
            } : j, k;
        }
    }, manual = f;
out['push']([...manual][o(0x15f)]('+'));
for (const v of manual) {
    if (v === 0x215f + -0x8fa + 0xe * -0x1be)
        break;
    out['push']('m' + v);
}
console[o(0x160)](out['join']('|'));