// Cross-runtime: destructuring, defaults, rest/spread, computed keys — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x119116 = _0x3281;
(function (_0x3cd0d2, _0x41d53e) {
    const _0x6b075b = _0x3281, _0x28ecf4 = _0x3cd0d2();
    while (!![]) {
        try {
            const _0x552dd8 = parseInt(_0x6b075b(0x7e)) / 0x1 + -parseInt(_0x6b075b(0x6c)) / 0x2 * (parseInt(_0x6b075b(0x78)) / 0x3) + -parseInt(_0x6b075b(0x70)) / 0x4 * (-parseInt(_0x6b075b(0x7f)) / 0x5) + parseInt(_0x6b075b(0x7a)) / 0x6 * (parseInt(_0x6b075b(0x76)) / 0x7) + parseInt(_0x6b075b(0x71)) / 0x8 * (parseInt(_0x6b075b(0x73)) / 0x9) + parseInt(_0x6b075b(0x6f)) / 0xa + -parseInt(_0x6b075b(0x74)) / 0xb;
            if (_0x552dd8 === _0x41d53e)
                break;
            else
                _0x28ecf4['push'](_0x28ecf4['shift']());
        } catch (_0x3bc4c3) {
            _0x28ecf4['push'](_0x28ecf4['shift']());
        }
    }
}(_0x5769, 0xcd1b4));
const out = [], {
        a,
        b: bee = 0x9,
        ...rest
    } = {
        'a': 0x1,
        'c': 0x3,
        'd': 0x4
    };
out[_0x119116(0x77)](a, bee, JSON[_0x119116(0x75)](rest));
const [p, , q = 0x7, ...tail] = [
    0x1,
    0x2,
    undefined,
    0x4,
    0x5
];
out[_0x119116(0x77)](p, q, tail[_0x119116(0x6e)](','));
function f({
    x: x = 0x1,
    y: y = 0x2
} = {}, ..._0x55ddf0) {
    const _0x99e326 = _0x119116;
    return x + y + _0x55ddf0[_0x99e326(0x7d)];
}
out[_0x119116(0x77)](f(), f({ 'x': 0xa }, 0x1, 0x2));
const key = _0x119116(0x6d), o = {
        [key + '1']: 'v1',
        [key + '2']: 'v2'
    };
out[_0x119116(0x77)](Object[_0x119116(0x72)](o)[_0x119116(0x6e)](','));
const merged = {
    ...o,
    'extra': !![]
};
out[_0x119116(0x77)](Object[_0x119116(0x72)](merged)[_0x119116(0x7d)]);
function* gen() {
    yield 0x1, yield 0x2, yield 0x3;
}
out[_0x119116(0x77)]([...gen()][_0x119116(0x6e)]('+'));
const [g1, ...grest] = gen();
out[_0x119116(0x77)](g1, grest[_0x119116(0x6e)]('.'));
const m = new Map([
    [
        'k',
        0x1
    ],
    [
        'j',
        0x2
    ]
]);
function _0x3281(_0x4e4283, _0x464b09) {
    _0x4e4283 = _0x4e4283 - 0x6c;
    const _0x5769fd = _0x5769();
    let _0x3281e3 = _0x5769fd[_0x4e4283];
    return _0x3281e3;
}
function _0x5769() {
    const _0x382e41 = [
        'map',
        'length',
        '351299kTIXmu',
        '10kdwRNS',
        '235784odNVUH',
        'dyn',
        'join',
        '7186130UQussG',
        '2579552EKWJhp',
        '3764632USqRBP',
        'keys',
        '18BhdueY',
        '28837281pQpcdG',
        'stringify',
        '7MQufnp',
        'push',
        '33axQXDd',
        'entries',
        '8745918XSVhPl',
        'log'
    ];
    _0x5769 = function () {
        return _0x382e41;
    };
    return _0x5769();
}
out[_0x119116(0x77)]([...m[_0x119116(0x79)]()][_0x119116(0x7c)](([_0x40926f, _0x3af234]) => _0x40926f + _0x3af234)[_0x119116(0x6e)](','));
for (const [k, v] of m)
    out[_0x119116(0x77)](k + '=' + v);
console[_0x119116(0x7b)](out[_0x119116(0x6e)]('|'));