// Cross-runtime: labels, switch fallthrough, try/catch/finally, short-circuit — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const m = c;
(function (d, e) {
    const l = c, f = d();
    while (!![]) {
        try {
            const g = parseInt(l(0x171)) / 0x1 * (-parseInt(l(0x167)) / 0x2) + -parseInt(l(0x165)) / 0x3 + parseInt(l(0x16e)) / 0x4 * (parseInt(l(0x169)) / 0x5) + parseInt(l(0x16d)) / 0x6 + parseInt(l(0x176)) / 0x7 + parseInt(l(0x16c)) / 0x8 + -parseInt(l(0x177)) / 0x9 * (-parseInt(l(0x170)) / 0xa);
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(b, 0xd3ed7));
const out = [];
d:
    for (let i = 0x0; i < 0x4; i++) {
        for (let j = 0x0; j < 0x4; j++) {
            if (j === 0x2)
                continue d;
            if (i === 0x3)
                break d;
            out[m(0x172)](i + '' + j);
        }
    }
function sw(e) {
    let f = '';
    switch (e) {
    case 0x0:
        f += 'z';
    case 0x1:
        f += 'o';
        break;
    case 0x2:
        f += 't';
        break;
    default:
        f += 'd';
    }
    return f;
}
out[m(0x172)](sw(0x0) + sw(0x1) + sw(0x2) + sw(0x9));
function tf(f) {
    const o = m, g = {
            'HAxoO': function (h, k) {
                return h === k;
            },
            'XEcMg': o(0x168),
            'jjaXd': function (h, k) {
                return h + k;
            },
            'qpBXp': o(0x178)
        };
    try {
        if (g[o(0x174)](f, 0x0))
            throw new RangeError(g['XEcMg']);
        return g[o(0x175)]('ok', f);
    } catch (h) {
        return h[o(0x16f)]['name'];
    } finally {
        out[o(0x172)](g[o(0x175)](g[o(0x16b)], f));
    }
}
function c(a, d) {
    a = a - 0x164;
    const e = b();
    let f = e[a];
    return f;
}
out[m(0x172)](tf(0x0), tf(0x1));
let a = null;
out['push'](a ?? 'dflt', a?.[m(0x16a)]?.['er'], 0x0 || m(0x173), 0x1 && 'truthy');
function b() {
    const p = [
        'qpBXp',
        '761032rIdQdy',
        '5619522TJJMmG',
        '44uCNAnj',
        'constructor',
        '110JqThzA',
        '119125KwXRFc',
        'push',
        'falsy',
        'HAxoO',
        'jjaXd',
        '6934417rMhAdu',
        '378747zgihMf',
        'fin',
        'join',
        '4482099GAcQHG',
        'log',
        '20VfJDak',
        'zero',
        '485490HsngYX',
        'deep'
    ];
    b = function () {
        return p;
    };
    return b();
}
let n = 0x0;
do {
    n += 0x2;
} while (n < 0x7);
out[m(0x172)](n), console[m(0x166)](out[m(0x164)]('|'));