// Cross-runtime: destructuring, defaults, rest/spread, computed keys — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const t = c;
(function (i, j) {
    const s = c, l = i();
    while (!![]) {
        try {
            const n = -parseInt(s(0xf3)) / (0x2674 + -0x26a0 + 0x3 * 0xf) * (parseInt(s(0xf0)) / (0x10ae * 0x2 + 0x141a + -0x3574)) + parseInt(s(0xe6)) / (-0x1 * 0x1edf + -0xa14 + 0x28f6) + parseInt(s(0xe9)) / (0x1 * 0x89 + -0x260e + 0x2589) * (-parseInt(s(0xe7)) / (-0x9a3 + 0x1 * -0x260b + 0x2fb3)) + -parseInt(s(0xea)) / (-0xb5 * 0x11 + -0x13fa + -0x1 * -0x2005) + parseInt(s(0xf6)) / (0xaa1 + -0x206 + -0x894) * (-parseInt(s(0xed)) / (0x684 * 0x3 + -0x1 * 0x116 + -0x126e * 0x1)) + parseInt(s(0xef)) / (-0x888 + -0x3 * 0x3fd + -0x6d8 * -0x3) * (parseInt(s(0xee)) / (0x2657 + 0xa40 + -0x308d)) + parseInt(s(0xe5)) / (-0x15fe + -0x2316 + -0x829 * -0x7);
            if (n === j)
                break;
            else
                l['push'](l['shift']());
        } catch (r) {
            l['push'](l['shift']());
        }
    }
}(b, -0x8d65 + -0x64a6e * -0x1 + -0x19192));
const out = [], d = {};
d['a'] = 0x1, d['c'] = 0x3, d['d'] = 0x4;
const {
    a,
    b: bee = -0x1 * 0xacb + 0x1543 * -0x1 + 0x2017,
    ...rest
} = d;
out[t(0xf2)](a, bee, JSON[t(0xf4)](rest));
const [p, , q = 0x430 * -0x1 + 0xb49 + -0x712, ...tail] = [
    -0x38a + 0x10 * -0x17 + 0x1 * 0x4fb,
    -0x1b3b + 0x36d * -0xa + 0xd * 0x4bb,
    undefined,
    0x4d7 + 0x259e + 0x35 * -0xcd,
    0x2041 + -0x1e9f + 0x3b * -0x7
];
function c(a, d) {
    a = a - (-0xf2d + 0x1205 + -0x1f3);
    const e = b();
    let f = e[a];
    return f;
}
out[t(0xf2)](p, q, tail[t(0xf1)](','));
function f({
    x: x = 0xbe9 * 0x1 + 0x20f5 + -0x2cdd,
    y: y = -0x1ef + 0x1be5 + -0x1 * 0x19f4
} = {}, ...i) {
    return x + y + i['length'];
}
const e = {};
e['x'] = 0xa, out[t(0xf2)](f(), f(e, -0xd88 + -0x2a5 + 0x13 * 0xda, 0x1 * -0x18ba + -0x59d + 0x1 * 0x1e59));
const key = 'dyn', g = {
        [key + '1']: 'v1',
        [key + '2']: 'v2'
    }, o = g;
out['push'](Object[t(0xe8)](o)[t(0xf1)](','));
const h = { ...o };
h[t(0xf5)] = !![];
const merged = h;
out['push'](Object[t(0xe8)](merged)['length']);
function* gen() {
    yield -0x207d + -0xc * 0x155 + 0x307a, yield -0x163 + 0xd9f + -0xc3a, yield -0x24dd + 0x2443 + 0x9d;
}
out[t(0xf2)]([...gen()]['join']('+'));
const [g1, ...grest] = gen();
out[t(0xf2)](g1, grest['join']('.'));
function b() {
    const u = [
        'stringify',
        'extra',
        '21hFwoPb',
        '2091144QQUfXI',
        '1095498YCwQjs',
        '405ZNtNch',
        'keys',
        '5452RgpBhI',
        '745338TCsYDq',
        'entries',
        'map',
        '526520VHYJrh',
        '393370THpOzD',
        '117zRfgnc',
        '722618XWxchm',
        'join',
        'push',
        '1mNnRZe'
    ];
    b = function () {
        return u;
    };
    return b();
}
const m = new Map([
    [
        'k',
        -0x101 * 0x22 + 0x1ea6 + -0x13 * -0x2f
    ],
    [
        'j',
        0x955 * 0x2 + 0x634 + 0x4 * -0x637
    ]
]);
out[t(0xf2)]([...m[t(0xeb)]()][t(0xec)](([i, j]) => i + j)['join'](','));
for (const [k, v] of m)
    out['push'](k + '=' + v);
console['log'](out[t(0xf1)]('|'));