// Cross-runtime: classes, prototypes, getters, static, super, instanceof — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const l = b;
(function (d, e) {
    const i = b, f = d();
    while (!![]) {
        try {
            const g = -parseInt(i(0x79)) / (0x4 * 0x236 + 0x3 * -0x64b + 0x101 * 0xa) * (parseInt(i(0x80)) / (0x197 * -0x7 + 0x1301 + 0x6a * -0x13)) + -parseInt(i(0x7a)) / (0x1776 + 0x68f + -0x1e02) + -parseInt(i(0x8e)) / (-0x14d1 * -0x1 + 0x1 * 0x25a7 + -0x3a74) * (-parseInt(i(0x85)) / (0x50b + -0x1 * 0xc43 + 0x73d * 0x1)) + -parseInt(i(0x7c)) / (-0x4d * 0x19 + -0x13db * -0x1 + -0xc50) * (parseInt(i(0x8d)) / (-0x1 * 0x162c + 0xf1 * -0xd + 0x74 * 0x4c)) + -parseInt(i(0x84)) / (0x2b * 0x76 + 0x88c + 0xd * -0x22e) + parseInt(i(0x75)) / (0x1 * 0x23ad + 0x2d1 + -0x37f * 0xb) * (-parseInt(i(0x81)) / (0x1fe3 + -0x6df * -0x1 + -0x26b8)) + -parseInt(i(0x7b)) / (-0x917 * -0x1 + -0x20ff + 0x17f3 * 0x1) * (-parseInt(i(0x86)) / (-0x1126 + -0x2503 + 0x1 * 0x3635));
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(a, -0x4 * 0x1335e + -0x68bd9 + 0xec3b6));
const out = [];
class Shape {
    constructor(d) {
        const j = b;
        this[j(0x78)] = d;
    }
    get [l(0x7f)]() {
        const m = l;
        return m(0x82) + this[m(0x78)];
    }
    static [l(0x8c)]() {
        return 'Shape';
    }
    [l(0x88)]() {
        return this['label'];
    }
}
class Circle extends Shape {
    constructor(d) {
        const n = l;
        super(n(0x74)), this['r'] = d;
    }
    get [l(0x7f)]() {
        const o = l;
        return super[o(0x7f)] + ':' + this['r'];
    }
    static [l(0x8c)]() {
        const p = l;
        return 'C<' + super[p(0x8c)]() + '>';
    }
}
const k = new Circle(-0x779 * 0x1 + -0x1150 + -0xc * -0x211);
function b(c, d) {
    c = c - (0x2 * 0x4fc + -0x264f + 0x1cca);
    const e = a();
    let f = e[c];
    return f;
}
out[l(0x89)](k['describe']()), out[l(0x89)](Circle[l(0x8c)]()), out[l(0x89)](k instanceof Shape, k instanceof Circle), out[l(0x89)](Object[l(0x83)](Circle['prototype']) === Shape[l(0x7d)]);
const c = {};
c['greet'] = function () {
    const q = l;
    return q(0x7e) + this[q(0x76)];
};
const proto = c, obj = Object['create'](proto);
obj[l(0x76)] = l(0x8a), out[l(0x89)](obj[l(0x87)]()), out['push'](Object[l(0x77)](obj)[l(0x8b)](','));
function a() {
    const r = [
        'label',
        '14KdnINi',
        '550NjXMzX',
        'shape:',
        'getPrototypeOf',
        '2532408zjuNgA',
        '138125CFlLUy',
        '2184XherUl',
        'greet',
        'describe',
        'push',
        'you',
        'join',
        'kind',
        '295442WZtwEO',
        '8UZmtLG',
        'twice',
        'circle',
        '32211sXcYGX',
        'who',
        'keys',
        'name',
        '55601RTeuyA',
        '457596ZJBDHc',
        '94369lMUCnQ',
        '48eHhpgn',
        'prototype',
        'hi\x20'
    ];
    a = function () {
        return r;
    };
    return a();
}
function Old(d) {
    this['v'] = d;
}
Old[l(0x7d)][l(0x73)] = function () {
    return this['v'] * (-0x1 * -0x4c7 + -0x6c3 * 0x2 + -0x1 * -0x8c1);
}, out[l(0x89)](new Old(0x1 * -0xdcb + 0x690 + 0xea * 0x8)[l(0x73)]()), console['log'](out['join']('|'));