// Cross-runtime: closures, per-iteration bindings, shadowing, IIFE chains — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (string array + base64 + wrappers + split strings) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
function _0x5c1bea(_0x20cd4a, _0xa50175) {
    return _0x3b81(_0x20cd4a - 0x1a2, _0xa50175);
}
(function (_0x3c4edb, _0x4bcea5) {
    function _0x11c281(_0x20eb58, _0x25d930) {
        return _0x3b81(_0x25d930 - 0x23e, _0x20eb58);
    }
    function _0x16a4f9(_0x276e36, _0x5dd7ef) {
        return _0x3b81(_0x5dd7ef - -0x2d9, _0x276e36);
    }
    const _0x28146f = _0x3c4edb();
    while (!![]) {
        try {
            const _0x33a420 = parseInt(_0x16a4f9(-0xef, -0xec)) / 0x1 + parseInt(_0x11c281(0x431, 0x433)) / 0x2 + -parseInt(_0x11c281(0x429, 0x42f)) / 0x3 + -parseInt(_0x11c281(0x438, 0x434)) / 0x4 * (parseInt(_0x11c281(0x42e, 0x426)) / 0x5) + -parseInt(_0x16a4f9(-0xed, -0xe5)) / 0x6 + -parseInt(_0x11c281(0x434, 0x436)) / 0x7 + parseInt(_0x16a4f9(-0xdf, -0xe6)) / 0x8 * (parseInt(_0x11c281(0x427, 0x430)) / 0x9);
            if (_0x33a420 === _0x4bcea5)
                break;
            else
                _0x28146f['push'](_0x28146f['shift']());
        } catch (_0x47cf9a) {
            _0x28146f['push'](_0x28146f['shift']());
        }
    }
}(_0x3cd0, 0x69120));
const out = [], fns = [];
for (let i = 0x0; i < 0x4; i++)
    fns[_0x5c1bea(0x38d, 0x387) + 'h'](() => i * 0x3);
out[_0x5c79fd(0x41e, 0x41e) + 'h'](fns[_0x5c79fd(0x41e, 0x422)](_0x5479cb => _0x5479cb())[_0x5c79fd(0x423, 0x41c) + 'n'](','));
function counter(_0x56fbbf) {
    let _0x22ced4 = _0x56fbbf;
    return {
        'inc': () => ++_0x22ced4,
        'get': () => _0x22ced4
    };
}
function _0x3cd0() {
    const _0x2eb6f3 = [
        'B3v0',
        'mtq4mZG1mxP2s0Hezq',
        'ntq5DuPnyxzr',
        'mJi5nZzJy2n1wxm',
        'mta2otmYnLL3D1vQsq',
        'nta5ote0t1jyAwDR',
        'ohHlwxDusW',
        'Aw5U',
        'mJy4nJe4z2rWCLjp',
        'mta2odv2t1jmsMC',
        'AM9P',
        'z2v0',
        'ChvZ',
        'Aw5J',
        'nZe1nZa1whn5wu5u',
        'Bg9N',
        'BwfW'
    ];
    _0x3cd0 = function () {
        return _0x2eb6f3;
    };
    return _0x3cd0();
}
const c = counter(0xa);
c[_0x5c79fd(0x422, 0x41f)](), c[_0x5c1bea(0x38e, 0x396)](), out[_0x5c79fd(0x417, 0x41e) + 'h'](c[_0x5c79fd(0x41e, 0x41d)]());
function _0x3b81(_0x12195c, _0x4dc519) {
    _0x12195c = _0x12195c - 0x1e8;
    const _0x3cd06e = _0x3cd0();
    let _0x3b8160 = _0x3cd06e[_0x12195c];
    if (_0x3b81['SlAAlL'] === undefined) {
        var _0x22106d = function (_0xf5d29b) {
            const _0x5ae869 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';
            let _0x5479cb = '', _0x56fbbf = '';
            for (let _0x22ced4 = 0x0, _0x3e1c30, _0x5df8cd, _0x24c09a = 0x0; _0x5df8cd = _0xf5d29b['charAt'](_0x24c09a++); ~_0x5df8cd && (_0x3e1c30 = _0x22ced4 % 0x4 ? _0x3e1c30 * 0x40 + _0x5df8cd : _0x5df8cd, _0x22ced4++ % 0x4) ? _0x5479cb += String['fromCharCode'](0xff & _0x3e1c30 >> (-0x2 * _0x22ced4 & 0x6)) : 0x0) {
                _0x5df8cd = _0x5ae869['indexOf'](_0x5df8cd);
            }
            for (let _0x1d6a19 = 0x0, _0x23035b = _0x5479cb['length']; _0x1d6a19 < _0x23035b; _0x1d6a19++) {
                _0x56fbbf += '%' + ('00' + _0x5479cb['charCodeAt'](_0x1d6a19)['toString'](0x10))['slice'](-0x2);
            }
            return decodeURIComponent(_0x56fbbf);
        };
        _0x3b81['DDGESs'] = _0x22106d, _0x3b81['KfaxWg'] = {}, _0x3b81['SlAAlL'] = !![];
    }
    const _0x148672 = _0x3cd06e[0x0], _0x44d323 = _0x12195c + _0x148672, _0x104f15 = _0x3b81['KfaxWg'][_0x44d323];
    return !_0x104f15 ? (_0x3b8160 = _0x3b81['DDGESs'](_0x3b8160), _0x3b81['KfaxWg'][_0x44d323] = _0x3b8160) : _0x3b8160 = _0x104f15, _0x3b8160;
}
let x = _0x5c1bea(0x392, 0x394) + 'er';
{
    let x = _0x5c79fd(0x432, 0x42a) + 'er';
    out[_0x5c79fd(0x41b, 0x41e) + 'h'](x);
}
out[_0x5c79fd(0x422, 0x41e) + 'h'](x), out[_0x5c1bea(0x38d, 0x385) + 'h'](function (_0x3e1c30) {
    return function (_0x5df8cd) {
        return _0x3e1c30 + _0x5df8cd;
    }(0x5);
}(0x7));
const memo = ((() => {
    const _0x24c09a = {};
    return _0x1d6a19 => _0x24c09a[_0x1d6a19] = (_0x24c09a[_0x1d6a19] || 0x0) + 0x1;
})());
memo('a'), memo('a');
function _0x5c79fd(_0x9a3ffc, _0x534500) {
    return _0x3b81(_0x534500 - 0x233, _0x9a3ffc);
}
memo('b'), out[_0x5c1bea(0x38d, 0x38e) + 'h'](memo('a') + ':' + memo('b')), console[_0x5c1bea(0x390, 0x396)](out[_0x5c1bea(0x38b, 0x391) + 'n']('|'));