// Cross-runtime: closures, per-iteration bindings, shadowing, IIFE chains — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const k = b;
(function (d, e) {
    const j = b, f = d();
    while (!![]) {
        try {
            const g = parseInt(j(0xff)) / 0x1 + -parseInt(j(0x101)) / 0x2 * (parseInt(j(0xf7)) / 0x3) + parseInt(j(0x108)) / 0x4 * (parseInt(j(0xf9)) / 0x5) + parseInt(j(0x106)) / 0x6 * (-parseInt(j(0x104)) / 0x7) + parseInt(j(0xfb)) / 0x8 + -parseInt(j(0x107)) / 0x9 + -parseInt(j(0xf8)) / 0xa * (-parseInt(j(0x100)) / 0xb);
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(a, 0x47799));
const out = [], fns = [];
for (let i = 0x0; i < 0x4; i++)
    fns['push'](() => i * 0x3);
out[k(0x105)](fns[k(0xfc)](d => d())[k(0xfe)](','));
function counter(d) {
    let e = d;
    return {
        'inc': () => ++e,
        'get': () => e
    };
}
const c = counter(0xa);
c['inc'](), c[k(0x102)](), out[k(0x105)](c[k(0x103)]());
let x = k(0xfa);
{
    let x = 'inner';
    out[k(0x105)](x);
}
function b(c, d) {
    c = c - 0xf7;
    const e = a();
    let f = e[c];
    return f;
}
function a() {
    const l = [
        '296206AGDRbK',
        'inc',
        'get',
        '182RNLbEN',
        'push',
        '103548WOgKLO',
        '4100382XQwGXw',
        '69544rcjdMc',
        '9MOkhFH',
        '6210viWqAB',
        '85IxcGRj',
        'outer',
        '798432brobcD',
        'map',
        'log',
        'join',
        '230675KgGwBF',
        '17985mrRkvA'
    ];
    a = function () {
        return l;
    };
    return a();
}
out['push'](x), out[k(0x105)](function (d) {
    const e = {
        'bZGTW': function (f, g) {
            return f + g;
        }
    };
    return function (f) {
        return e['bZGTW'](d, f);
    }(0x5);
}(0x7));
const memo = ((() => {
    const d = {};
    return e => d[e] = (d[e] || 0x0) + 0x1;
})());
memo('a'), memo('a'), memo('b'), out[k(0x105)](memo('a') + ':' + memo('b')), console[k(0xfd)](out['join']('|'));