// Cross-runtime: descriptors, freeze, symbols, enumeration order, JSON — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const i = b;
(function (c, d) {
    const h = b, e = c();
    while (!![]) {
        try {
            const f = parseInt(h(0x8b)) / 0x1 * (parseInt(h(0x85)) / 0x2) + -parseInt(h(0x7f)) / 0x3 * (parseInt(h(0x7e)) / 0x4) + -parseInt(h(0x7b)) / 0x5 * (-parseInt(h(0x8f)) / 0x6) + -parseInt(h(0x86)) / 0x7 * (-parseInt(h(0x7d)) / 0x8) + parseInt(h(0x96)) / 0x9 + parseInt(h(0x95)) / 0xa + parseInt(h(0x88)) / 0xb * (-parseInt(h(0x82)) / 0xc);
            if (f === d)
                break;
            else
                e['push'](e['shift']());
        } catch (g) {
            e['push'](e['shift']());
        }
    }
}(a, 0x743c5));
const out = [], o = {
        'b': 0x2,
        0x2: i(0x8e),
        'a': 0x1,
        0x1: i(0x89)
    };
out['push'](Object[i(0x80)](o)[i(0x92)](',')), Object[i(0x84)](o, 'hidden', {
    'value': 0x9,
    'enumerable': ![]
}), out[i(0x83)](Object[i(0x80)](o)[i(0x92)](','), o[i(0x8c)]), out[i(0x83)](JSON[i(0x91)](Object[i(0x81)](o, i(0x8c))));
const frozen = Object[i(0x94)]({ 'v': 0x1 });
out[i(0x83)](Reflect['set'](frozen, 'v', 0x2), frozen['v'], Object[i(0x8d)](frozen));
function b(c, d) {
    c = c - 0x7b;
    const e = a();
    let f = e[c];
    return f;
}
const sym = Symbol('tag'), withSym = {
        [sym]: 's',
        'plain': 'p'
    };
out['push'](Object[i(0x80)](withSym)[i(0x92)](','), withSym[sym]), out[i(0x83)](Object[i(0x93)](withSym)[i(0x8a)]);
function a() {
    const j = [
        'length',
        '1iSfpnh',
        'hidden',
        'isFrozen',
        'two',
        '30OhRyYq',
        'log',
        'stringify',
        'join',
        'getOwnPropertySymbols',
        'freeze',
        '667750goXhnV',
        '2599875GRWZSG',
        '{\x22n\x22:[1,{\x22d\x22:true}],\x22s\x22:null}',
        'parse',
        '347545EEEIaC',
        'map',
        '3792cOVpjS',
        '4468VltUpH',
        '1203FZaeyg',
        'keys',
        'getOwnPropertyDescriptor',
        '144LuwAAA',
        'push',
        'defineProperty',
        '428938QpSswv',
        '9065ZpqNDN',
        'entries',
        '556853QssYmq',
        'one'
    ];
    a = function () {
        return j;
    };
    return a();
}
class Box {
    constructor() {
        this['v'] = 0x1;
    }
    ['m']() {
    }
}
const bx = new Box(), seen = [];
for (const k in bx)
    seen[i(0x83)](k);
out[i(0x83)](seen[i(0x92)](',')), out[i(0x83)](JSON[i(0x91)](JSON[i(0x98)](i(0x97)))), out[i(0x83)](Object[i(0x87)]({
    'z': 0x1,
    'y': 0x2
})[i(0x7c)](([c, d]) => c + d)[i(0x92)]('')), console[i(0x90)](out[i(0x92)]('|'));