// Cross-runtime: string methods, template literals, regex, replace callbacks — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x266291 = _0x15a5;
(function (_0x2cf094, _0x53e9c8) {
    const _0x2a7848 = _0x15a5, _0x14c62a = _0x2cf094();
    while (!![]) {
        try {
            const _0x591140 = -parseInt(_0x2a7848(0x1d7)) / 0x1 * (parseInt(_0x2a7848(0x1cd)) / 0x2) + -parseInt(_0x2a7848(0x1d1)) / 0x3 + parseInt(_0x2a7848(0x1d6)) / 0x4 + parseInt(_0x2a7848(0x1dd)) / 0x5 * (-parseInt(_0x2a7848(0x1e9)) / 0x6) + parseInt(_0x2a7848(0x1e6)) / 0x7 + parseInt(_0x2a7848(0x1db)) / 0x8 * (-parseInt(_0x2a7848(0x1e8)) / 0x9) + parseInt(_0x2a7848(0x1e2)) / 0xa;
            if (_0x591140 === _0x53e9c8)
                break;
            else
                _0x14c62a['push'](_0x14c62a['shift']());
        } catch (_0x75ec66) {
            _0x14c62a['push'](_0x14c62a['shift']());
        }
    }
}(_0x1ef8, 0xbebd0));
const out = [], s = _0x266291(0x1d3);
out[_0x266291(0x1e3)](s[_0x266291(0x1ce)]()[_0x266291(0x1d8)](0x4, 0x9)), out[_0x266291(0x1e3)](s[_0x266291(0x1da)]('\x20')[_0x266291(0x1e7)](_0x16cfe3 => _0x16cfe3[_0x266291(0x1d0)])[_0x266291(0x1df)]('-')), out[_0x266291(0x1e3)](s[_0x266291(0x1d9)](/(\w+) (\w+)/, _0x266291(0x1cb))), out[_0x266291(0x1e3)](s[_0x266291(0x1d9)](/o/g, (_0x3eb17c, _0x6c6fbd) => '[' + _0x6c6fbd + ']')), out[_0x266291(0x1e3)](/(?<adj>\w+) fox/[_0x266291(0x1d5)](s)[_0x266291(0x1e5)][_0x266291(0x1de)]), out[_0x266291(0x1e3)]([...s[_0x266291(0x1d4)](/[A-Z]/g)][_0x266291(0x1e7)](_0x49dc9c => _0x49dc9c[_0x266291(0x1e0)])[_0x266291(0x1df)](','));
function _0x15a5(_0x7d2976, _0x599e42) {
    _0x7d2976 = _0x7d2976 - 0x1cb;
    const _0x1ef827 = _0x1ef8();
    let _0x15a5a3 = _0x1ef827[_0x7d2976];
    return _0x15a5a3;
}
const tag = (_0x30e0f5, ..._0x313feb) => _0x30e0f5[_0x266291(0x1d2)][_0x266291(0x1df)]('#') + '/' + _0x313feb[_0x266291(0x1df)]('+');
function _0x1ef8() {
    const _0x551168 = [
        'replace',
        'split',
        '16ZulEDs',
        'he\x20said\x20\x22hi\x22',
        '739655WjLvdd',
        'adj',
        'join',
        'index',
        'log',
        '12071870odRUlr',
        'push',
        'stringify',
        'groups',
        '7585424imImIi',
        'map',
        '3122226nAXOaQ',
        '18zlmSkD',
        '$2\x20$1',
        'abc',
        '1791158WkmYsF',
        'toUpperCase',
        'padStart',
        'length',
        '654345KjpNRI',
        'raw',
        'The\x20quick\x20Brown\x20fox',
        'matchAll',
        'exec',
        '2967040JftirG',
        '1aaARuk',
        'slice'
    ];
    _0x1ef8 = function () {
        return _0x551168;
    };
    return _0x1ef8();
}
out[_0x266291(0x1e3)](tag`a${ 0x1 }b${ 0x2 }c`), out[_0x266291(0x1e3)](_0x266291(0x1cc)[_0x266291(0x1cf)](0x6, '-') + '|' + _0x266291(0x1cc)['at'](-0x1)), out[_0x266291(0x1e3)](JSON[_0x266291(0x1e4)]({
    'q': _0x266291(0x1dc),
    'n': '\x0a'
})), console[_0x266291(0x1e1)](out[_0x266291(0x1df)]('|'));