// Cross-runtime: error hierarchy, rethrow, nested try, custom errors, cause — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0x4c8755 = _0x37e6;
(function (_0x4908e7, _0x18dc04) {
    const _0x3f4c1f = _0x37e6, _0x1faf86 = _0x4908e7();
    while (!![]) {
        try {
            const _0x46843b = -parseInt(_0x3f4c1f(0x78)) / 0x1 + parseInt(_0x3f4c1f(0x84)) / 0x2 + parseInt(_0x3f4c1f(0x8b)) / 0x3 + parseInt(_0x3f4c1f(0x91)) / 0x4 * (-parseInt(_0x3f4c1f(0x96)) / 0x5) + parseInt(_0x3f4c1f(0x8d)) / 0x6 + parseInt(_0x3f4c1f(0x76)) / 0x7 * (parseInt(_0x3f4c1f(0x8f)) / 0x8) + parseInt(_0x3f4c1f(0x7e)) / 0x9 * (-parseInt(_0x3f4c1f(0x8a)) / 0xa);
            if (_0x46843b === _0x18dc04)
                break;
            else
                _0x1faf86['push'](_0x1faf86['shift']());
        } catch (_0x395d1e) {
            _0x1faf86['push'](_0x1faf86['shift']());
        }
    }
}(_0x588b, 0x541b2));
const out = [];
function _0x588b() {
    const _0x4b7179 = [
        '28665WYgmbS',
        'rEOxT',
        '489185EfSiwu',
        'join',
        'YZINd',
        'inner',
        'IWIrt',
        'parse',
        '31599rOjfmR',
        'XzHoM',
        'ITknM',
        'lxldW',
        'name',
        'root',
        '562118LEBVrK',
        'constructor',
        'kexVp',
        'wrapped:',
        'log',
        '{bad',
        '370iKKnoi',
        '1888830RnLqLi',
        'cause',
        '972876nPFLyK',
        'bad',
        '216OQMLIa',
        'caught',
        '4zgjkLq',
        'push',
        'code',
        'AppError',
        'LmHIU',
        '1098950QWNVnc',
        'qJALx',
        'outer',
        'map',
        'MrnAI',
        'LTusn',
        'zuOkz',
        'message'
    ];
    _0x588b = function () {
        return _0x4b7179;
    };
    return _0x588b();
}
class AppError extends Error {
    constructor(_0x3f9caa, _0x5dd5ea) {
        const _0x225f4d = _0x37e6;
        super(_0x3f9caa), this[_0x225f4d(0x82)] = _0x225f4d(0x94), this[_0x225f4d(0x93)] = _0x5dd5ea;
    }
}
try {
    throw new AppError(_0x4c8755(0x8e), 0x2a);
} catch (_0xc42728) {
    out[_0x4c8755(0x92)](_0xc42728[_0x4c8755(0x82)], _0xc42728[_0x4c8755(0x75)], _0xc42728[_0x4c8755(0x93)], _0xc42728 instanceof Error, _0xc42728 instanceof AppError);
}
function nested(_0x41b4a4) {
    const _0x544a23 = _0x4c8755;
    try {
        if (_0x544a23(0x77) !== _0x544a23(0x7c))
            try {
                if (_0x544a23(0x80) === _0x544a23(0x7a))
                    _0x15d6a9[_0x544a23(0x92)](_0x1d107e[_0x544a23(0x85)][_0x544a23(0x82)]);
                else {
                    if (_0x41b4a4)
                        throw new TypeError(_0x544a23(0x7b));
                    return 'no';
                }
            } catch (_0x4d7a19) {
                if (_0x544a23(0x73) === _0x544a23(0x97))
                    try {
                        if (_0x2f514d === 0x1)
                            throw new _0x40a688('s');
                        return 'ok';
                    } catch {
                        return _0x544a23(0x90);
                    }
                else
                    throw new RangeError(_0x544a23(0x87) + _0x4d7a19[_0x544a23(0x75)]);
            } finally {
                if (_0x544a23(0x81) === _0x544a23(0x81))
                    out[_0x544a23(0x92)]('f1');
                else
                    throw new _0x56b428(_0x544a23(0x87) + _0x53e435[_0x544a23(0x75)]);
            }
        else {
            if (_0xb201bb)
                throw new _0x157ad9(_0x544a23(0x7b));
            return 'no';
        }
    } catch (_0x594858) {
        return _0x544a23(0x74) !== _0x544a23(0x74) ? _0x275c9b[_0x544a23(0x82)] + ':' + _0x381416[_0x544a23(0x75)] : _0x594858[_0x544a23(0x82)] + ':' + _0x594858[_0x544a23(0x75)];
    } finally {
        if (_0x544a23(0x95) === _0x544a23(0x7f))
            try {
                if (_0x391117)
                    throw new _0x228df6(_0x544a23(0x7b));
                return 'no';
            } catch (_0x475e85) {
                throw new _0x1fde71(_0x544a23(0x87) + _0x475e85[_0x544a23(0x75)]);
            } finally {
                _0x109544[_0x544a23(0x92)]('f1');
            }
        else
            out[_0x544a23(0x92)]('f2');
    }
}
out[_0x4c8755(0x92)](nested(0x1), nested(0x0));
function _0x37e6(_0x31f590, _0x237c76) {
    _0x31f590 = _0x31f590 - 0x73;
    const _0x588b39 = _0x588b();
    let _0x37e62f = _0x588b39[_0x31f590];
    return _0x37e62f;
}
const withCause = new Error(_0x4c8755(0x98), { 'cause': new Error(_0x4c8755(0x83)) });
out[_0x4c8755(0x92)](withCause[_0x4c8755(0x8c)][_0x4c8755(0x75)]);
try {
    null['x'];
} catch (_0x56a7da) {
    out[_0x4c8755(0x92)](_0x56a7da[_0x4c8755(0x85)][_0x4c8755(0x82)]);
}
try {
    undefined();
} catch (_0x336adf) {
    out[_0x4c8755(0x92)](_0x336adf[_0x4c8755(0x85)][_0x4c8755(0x82)]);
}
try {
    JSON[_0x4c8755(0x7d)](_0x4c8755(0x89));
} catch (_0x156155) {
    out[_0x4c8755(0x92)](_0x156155[_0x4c8755(0x85)][_0x4c8755(0x82)]);
}
out[_0x4c8755(0x92)]([
    0x1,
    0x2
][_0x4c8755(0x99)](_0x7c0788 => {
    const _0x3b19b7 = _0x4c8755;
    try {
        if (_0x3b19b7(0x86) !== _0x3b19b7(0x86))
            _0xa42873();
        else {
            if (_0x7c0788 === 0x1)
                throw new Error('s');
            return 'ok';
        }
    } catch {
        if (_0x3b19b7(0x9a) !== _0x3b19b7(0x9a))
            _0x1fd9e7[_0x3b19b7(0x92)](_0x2d74c8[_0x3b19b7(0x85)][_0x3b19b7(0x82)]);
        else
            return _0x3b19b7(0x90);
    }
})[_0x4c8755(0x79)](',')), console[_0x4c8755(0x88)](out[_0x4c8755(0x79)]('|'));