// Cross-runtime: accessors, defineProperty, Proxy traps, Reflect, symbol keys — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const m = b;
(function (c, e) {
    const k = b, f = c();
    while (!![]) {
        try {
            const g = -parseInt(k(0xd7)) / 0x1 + parseInt(k(0xe0)) / 0x2 + parseInt(k(0xe6)) / 0x3 * (-parseInt(k(0xd5)) / 0x4) + -parseInt(k(0xd0)) / 0x5 + parseInt(k(0xd2)) / 0x6 + -parseInt(k(0xd8)) / 0x7 * (-parseInt(k(0xda)) / 0x8) + -parseInt(k(0xdd)) / 0x9 * (-parseInt(k(0xee)) / 0xa);
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(a, 0x32cec));
const out = [], o = {
        '_v': 0x1,
        get 'v'() {
            const l = b, c = {
                    'zBNgG': function (e, f) {
                        return e * f;
                    }
                };
            return c[l(0xd9)](this['_v'], 0xa);
        },
        set 'v'(c) {
            this['_v'] = c;
        }
    };
o['v'] = 0x5, out['push'](o['v'], o['_v']), out[m(0xd3)](Object[m(0xe5)](o)[m(0xcf)](','));
function a() {
    const s = [
        'get',
        'here',
        'create',
        'ownKeys',
        'defineProperty',
        'FjJnY',
        'getPrototypeOf',
        '430980TxSSPS',
        'log',
        'string',
        'Zvtls',
        'join',
        '686450GlmMjU',
        'Cbrpb',
        '198132azKPyt',
        'push',
        'MusnW',
        '220396DwGKAj',
        'oxApD',
        '170285GHHFCX',
        '155183mHXDPX',
        'zBNgG',
        '64GcVTsO',
        'enumerable',
        'inherited',
        '72wffavl',
        'has',
        'getOwnPropertyDescriptor',
        '31248VTmAvI',
        'own',
        'next',
        'set',
        'FDBIh',
        'keys',
        '3wvhwcL'
    ];
    a = function () {
        return s;
    };
    return a();
}
const d = Object[m(0xdf)](o, 'v');
function b(c, d) {
    c = c - 0xcc;
    const e = a();
    let f = e[c];
    return f;
}
out[m(0xd3)](typeof d[m(0xe7)], typeof d['set'], d[m(0xdb)]);
const target = { 'a': 0x1 }, log = [], p = new Proxy(target, {
        'get'(c, e, f) {
            const n = m, g = {
                    'oxApD': function (h, i) {
                        return h === i;
                    },
                    'Zvtls': n(0xcd),
                    'MusnW': function (h, i) {
                        return h + i;
                    }
                };
            if (g[n(0xd6)](typeof e, g[n(0xce)]))
                log['push'](g[n(0xd4)]('g:', e));
            return Reflect[n(0xe7)](c, e, f);
        },
        'set'(c, e, f, g) {
            const q = m, h = {
                    'Cbrpb': function (i, j) {
                        return i + j;
                    },
                    'FDBIh': function (i, j) {
                        return i(j);
                    }
                };
            return log[q(0xd3)](h[q(0xd1)]('s:', h[q(0xe4)](String, e))), Reflect[q(0xe3)](c, e, f, g);
        },
        'has'(c, e) {
            const r = m, f = {
                    'FjJnY': function (g, h) {
                        return g + h;
                    },
                    'JGptv': function (g, h) {
                        return g(h);
                    }
                };
            return log[r(0xd3)](f[r(0xec)]('h:', f['JGptv'](String, e))), Reflect[r(0xde)](c, e);
        }
    });
p['a'], p['b'] = 0x2, 'a' in p, out[m(0xd3)](log[m(0xcf)](','), target['b']), out[m(0xd3)](Reflect[m(0xea)]({
    'z': 0x1,
    0x2: 0x2,
    'a': 0x3
})['join'](','));
const chained = Object[m(0xe9)]({ 'inherited': 'up' });
chained[m(0xe1)] = m(0xe8), out[m(0xd3)](chained[m(0xdc)], Object[m(0xe5)](chained)[m(0xcf)](',')), out[m(0xd3)](Reflect[m(0xed)](chained)[m(0xdc)]);
const counter = { 'n': 0x0 };
Object[m(0xeb)](counter, 'next', {
    'get'() {
        return ++this['n'];
    }
}), out[m(0xd3)](counter[m(0xe2)], counter['next'], counter['n']), console[m(0xcc)](out[m(0xcf)]('|'));