// Cross-runtime: generators, yield*, the iterator protocol driven by hand — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (dead-code injection into every branch) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const _0xe092ae = _0x5010;
(function (_0x4e6e38, _0x343eaa) {
    const _0x39f40c = _0x5010, _0x31a238 = _0x4e6e38();
    while (!![]) {
        try {
            const _0x5147c1 = parseInt(_0x39f40c(0xca)) / 0x1 * (-parseInt(_0x39f40c(0xcd)) / 0x2) + -parseInt(_0x39f40c(0xc2)) / 0x3 + -parseInt(_0x39f40c(0xbd)) / 0x4 * (-parseInt(_0x39f40c(0xcb)) / 0x5) + -parseInt(_0x39f40c(0xb7)) / 0x6 + -parseInt(_0x39f40c(0xbe)) / 0x7 + -parseInt(_0x39f40c(0xc7)) / 0x8 * (-parseInt(_0x39f40c(0xc4)) / 0x9) + parseInt(_0x39f40c(0xcc)) / 0xa * (parseInt(_0x39f40c(0xb8)) / 0xb);
            if (_0x5147c1 === _0x343eaa)
                break;
            else
                _0x31a238['push'](_0x31a238['shift']());
        } catch (_0x29fc10) {
            _0x31a238['push'](_0x31a238['shift']());
        }
    }
}(_0x5de7, 0x1e8ad));
const out = [];
function* inner() {
    const _0x201173 = _0x5010;
    return yield 'i1', yield 'i2', _0x201173(0xb9);
}
function* outer() {
    const _0x1a57d0 = _0x5010;
    out[_0x1a57d0(0xc6)](_0x1a57d0(0xba));
    const _0x8f526c = yield* inner();
    out[_0x1a57d0(0xc6)](_0x1a57d0(0xc5) + _0x8f526c), yield 'o1';
}
out[_0xe092ae(0xc6)]([...outer()][_0xe092ae(0xbb)](','));
const it = inner();
out[_0xe092ae(0xc6)](JSON[_0xe092ae(0xc1)](it[_0xe092ae(0xc9)]()), JSON[_0xe092ae(0xc1)](it[_0xe092ae(0xc9)]())), out[_0xe092ae(0xc6)](JSON[_0xe092ae(0xc1)](it[_0xe092ae(0xc9)]()), JSON[_0xe092ae(0xc1)](it[_0xe092ae(0xc9)]()));
function _0x5de7() {
    const _0x3201bb = [
        '116882Mfpqtv',
        'genfin',
        '667584uBfXqt',
        '2033636dYWoNw',
        'iend',
        'pre',
        'join',
        'iterator',
        '11116fjCfIz',
        '698327GnJpAt',
        'value',
        'bye',
        'stringify',
        '64620lBogSk',
        'log',
        '30366lPPTJl',
        'got:',
        'push',
        '344OrjtBx',
        'return',
        'next',
        '1mkPLAP',
        '155IKMsmj',
        '10ipjPaO'
    ];
    _0x5de7 = function () {
        return _0x3201bb;
    };
    return _0x5de7();
}
function _0x5010(_0x6efed9, _0x1a5d02) {
    _0x6efed9 = _0x6efed9 - 0xb7;
    const _0x5de727 = _0x5de7();
    let _0x501060 = _0x5de727[_0x6efed9];
    return _0x501060;
}
function* counter() {
    let _0x5524c8 = 0x0;
    while (!![]) {
        const _0xb41dca = yield _0x5524c8;
        _0x5524c8 += _0xb41dca === undefined ? 0x1 : _0xb41dca;
        if (_0x5524c8 > 0x6)
            return _0x5524c8;
    }
}
const c = counter();
out[_0xe092ae(0xc6)](c[_0xe092ae(0xc9)]()[_0xe092ae(0xbf)], c[_0xe092ae(0xc9)](0x3)[_0xe092ae(0xbf)], c[_0xe092ae(0xc9)](0x3)[_0xe092ae(0xbf)]);
function* withFinally() {
    const _0x29d597 = _0xe092ae;
    try {
        yield 0x1, yield 0x2;
    } finally {
        out[_0x29d597(0xc6)](_0x29d597(0xce));
    }
}
const g = withFinally();
g[_0xe092ae(0xc9)](), out[_0xe092ae(0xc6)](JSON[_0xe092ae(0xc1)](g[_0xe092ae(0xc8)](_0xe092ae(0xc0))));
const manual = {
    [Symbol[_0xe092ae(0xbc)]]() {
        let _0x2e2297 = 0x0;
        return {
            'next': () => _0x2e2297 < 0x3 ? {
                'value': _0x2e2297++,
                'done': ![]
            } : {
                'value': undefined,
                'done': !![]
            }
        };
    }
};
out[_0xe092ae(0xc6)]([...manual][_0xe092ae(0xbb)]('+'));
for (const v of manual) {
    if (v === 0x1)
        break;
    out[_0xe092ae(0xc6)]('m' + v);
}
console[_0xe092ae(0xc3)](out[_0xe092ae(0xbb)]('|'));