// Cross-runtime: string methods, template literals, regex, replace callbacks — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (control-flow flattening, every function) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const i = b;
function b(c, d) {
    c = c - 0xbb;
    const e = a();
    let f = e[c];
    return f;
}
(function (c, d) {
    const h = b, e = c();
    while (!![]) {
        try {
            const f = -parseInt(h(0xcb)) / 0x1 + parseInt(h(0xca)) / 0x2 + parseInt(h(0xbf)) / 0x3 * (-parseInt(h(0xc7)) / 0x4) + parseInt(h(0xbc)) / 0x5 * (parseInt(h(0xce)) / 0x6) + parseInt(h(0xc9)) / 0x7 + parseInt(h(0xc4)) / 0x8 * (parseInt(h(0xd0)) / 0x9) + -parseInt(h(0xc3)) / 0xa;
            if (f === d)
                break;
            else
                e['push'](e['shift']());
        } catch (g) {
            e['push'](e['shift']());
        }
    }
}(a, 0xb4012));
const out = [], s = i(0xc2);
out[i(0xc6)](s[i(0xbe)]()['slice'](0x4, 0x9)), out[i(0xc6)](s[i(0xc1)]('\x20')[i(0xbb)](c => c[i(0xcd)])[i(0xd4)]('-')), out[i(0xc6)](s[i(0xcf)](/(\w+) (\w+)/, '$2\x20$1')), out[i(0xc6)](s[i(0xcf)](/o/g, (c, d) => '[' + d + ']')), out[i(0xc6)](/(?<adj>\w+) fox/['exec'](s)[i(0xd2)][i(0xd1)]), out[i(0xc6)]([...s[i(0xc5)](/[A-Z]/g)][i(0xbb)](c => c[i(0xc8)])[i(0xd4)](','));
const tag = (c, ...d) => c[i(0xd3)][i(0xd4)]('#') + '/' + d['join']('+');
out[i(0xc6)](tag`a${ 0x1 }b${ 0x2 }c`), out[i(0xc6)](i(0xbd)['padStart'](0x6, '-') + '|' + i(0xbd)['at'](-0x1)), out[i(0xc6)](JSON['stringify']({
    'q': i(0xc0),
    'n': '\x0a'
})), console[i(0xcc)](out[i(0xd4)]('|'));
function a() {
    const j = [
        '8416520WUbBuo',
        '1184696oyMGUx',
        '1070073XnNVRp',
        'log',
        'length',
        '4137864RubDRA',
        'replace',
        '2810844Ubnriz',
        'adj',
        'groups',
        'raw',
        'join',
        'map',
        '5uutpwe',
        'abc',
        'toUpperCase',
        '3SkMOnG',
        'he\x20said\x20\x22hi\x22',
        'split',
        'The\x20quick\x20Brown\x20fox',
        '10901060AQmVSF',
        '32JOZwsd',
        'matchAll',
        'push',
        '3344556fmpBtD',
        'index'
    ];
    a = function () {
        return j;
    };
    return a();
}