// Cross-runtime: error hierarchy, rethrow, nested try, custom errors, cause — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const o = b;
(function (c, d) {
    const m = b, g = c();
    while (!![]) {
        try {
            const k = -parseInt(m(0xb5)) / (0xd * 0x119 + 0x1 * 0x1333 + 0x293 * -0xd) * (-parseInt(m(0xb2)) / (-0x1b06 + -0x3 * 0x493 + 0x28c1)) + parseInt(m(0xbd)) / (0x139a + -0x487 + -0xf10 * 0x1) + parseInt(m(0xb1)) / (0x1747 * 0x1 + -0x1 * 0x20b0 + 0x96d) + -parseInt(m(0xc4)) / (0xef * 0x21 + 0x2 * 0x6b9 + 0x161e * -0x2) + -parseInt(m(0xb6)) / (-0x1919 + -0xafb * 0x1 + 0x241a) * (parseInt(m(0xbc)) / (0x1f1c + 0x1554 + -0x3469)) + -parseInt(m(0xb9)) / (0x1cf5 + 0x142a * -0x1 + -0x8c3) * (parseInt(m(0xc3)) / (-0xd * -0x1af + 0xa2a + -0x4 * 0x801)) + parseInt(m(0xb3)) / (0x22c6 + -0xc2c + -0x2 * 0xb48) * (parseInt(m(0xb4)) / (-0x153f + 0x3 * 0x5b3 + -0x1d * -0x25));
            if (k === d)
                break;
            else
                g['push'](g['shift']());
        } catch (l) {
            g['push'](g['shift']());
        }
    }
}(a, 0x596c + 0x4f56a + -0x2456d));
function b(c, d) {
    c = c - (-0x28 * -0xd + -0xad0 + 0x977);
    const e = a();
    let f = e[c];
    return f;
}
const out = [];
function a() {
    const r = [
        'message',
        'parse',
        'wrapped:',
        'cause',
        'caught',
        '11457XTEkFe',
        '402630KUHovg',
        'log',
        'inner',
        'push',
        '{bad',
        'bad',
        '987504cizyGa',
        '20428WcgNez',
        '1810JuMhPE',
        '55rpWEbu',
        '6wXPDAs',
        '48OBScvF',
        'code',
        'constructor',
        '1152GHZWQS',
        'join',
        'name',
        '60228DzJouR',
        '667866dnGxYJ'
    ];
    a = function () {
        return r;
    };
    return a();
}
class AppError extends Error {
    constructor(c, d) {
        const n = b;
        super(c), this[n(0xbb)] = 'AppError', this[n(0xb7)] = d;
    }
}
try {
    throw new AppError(o(0xb0), 0x1eab + 0xfe3 + -0x1 * 0x2e64);
} catch (f) {
    out[o(0xc7)](f[o(0xbb)], f[o(0xbe)], f[o(0xb7)], f instanceof Error, f instanceof AppError);
}
function nested(c) {
    const p = o;
    try {
        try {
            if (c)
                throw new TypeError(p(0xc6));
            return 'no';
        } catch (d) {
            throw new RangeError(p(0xc0) + d[p(0xbe)]);
        } finally {
            out[p(0xc7)]('f1');
        }
    } catch (g) {
        return g[p(0xbb)] + ':' + g[p(0xbe)];
    } finally {
        out[p(0xc7)]('f2');
    }
}
out[o(0xc7)](nested(0x76e + 0x79b + -0x1a * 0x94), nested(-0x45d * 0x8 + -0x55 * 0x2 + 0x2392));
const withCause = new Error('outer', { 'cause': new Error('root') });
out['push'](withCause[o(0xc1)]['message']);
try {
    null['x'];
} catch (h) {
    out[o(0xc7)](h['constructor']['name']);
}
try {
    undefined();
} catch (i) {
    out[o(0xc7)](i[o(0xb8)]['name']);
}
try {
    JSON[o(0xbf)](o(0xaf));
} catch (j) {
    out[o(0xc7)](j[o(0xb8)][o(0xbb)]);
}
out[o(0xc7)]([
    -0x1a07 + -0x1406 + 0x2e0e,
    0x1 * -0x207a + -0x172 * -0x11 + 0x7ea
]['map'](c => {
    const q = o;
    try {
        if (c === -0x175c + -0xad0 + -0x1 * -0x222d)
            throw new Error('s');
        return 'ok';
    } catch {
        return q(0xc2);
    }
})[o(0xba)](',')), console[o(0xc5)](out['join']('|'));