// Cross-runtime: destructuring, defaults, rest/spread, computed keys — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (string array + base64 + wrappers + split strings) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
function _0xfed9(_0x44ecc8, _0x15f365) {
    _0x44ecc8 = _0x44ecc8 - 0x73;
    const _0x43558f = _0x4355();
    let _0xfed9f2 = _0x43558f[_0x44ecc8];
    if (_0xfed9['adlEwN'] === undefined) {
        var _0x53edb0 = function (_0x33ee25) {
            const _0x508448 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';
            let _0x3cd0c2 = '', _0x285d5e = '';
            for (let _0x5c6a73 = 0x0, _0x2f8cad, _0x29323e, _0x13f0a0 = 0x0; _0x29323e = _0x33ee25['charAt'](_0x13f0a0++); ~_0x29323e && (_0x2f8cad = _0x5c6a73 % 0x4 ? _0x2f8cad * 0x40 + _0x29323e : _0x29323e, _0x5c6a73++ % 0x4) ? _0x3cd0c2 += String['fromCharCode'](0xff & _0x2f8cad >> (-0x2 * _0x5c6a73 & 0x6)) : 0x0) {
                _0x29323e = _0x508448['indexOf'](_0x29323e);
            }
            for (let _0x291bbb = 0x0, _0x1c1b2f = _0x3cd0c2['length']; _0x291bbb < _0x1c1b2f; _0x291bbb++) {
                _0x285d5e += '%' + ('00' + _0x3cd0c2['charCodeAt'](_0x291bbb)['toString'](0x10))['slice'](-0x2);
            }
            return decodeURIComponent(_0x285d5e);
        };
        _0xfed9['HRbWja'] = _0x53edb0, _0xfed9['xpcfWN'] = {}, _0xfed9['adlEwN'] = !![];
    }
    const _0x449cc8 = _0x43558f[0x0], _0x528262 = _0x44ecc8 + _0x449cc8, _0x259bc8 = _0xfed9['xpcfWN'][_0x528262];
    return !_0x259bc8 ? (_0xfed9f2 = _0xfed9['HRbWja'](_0xfed9f2), _0xfed9['xpcfWN'][_0x528262] = _0xfed9f2) : _0xfed9f2 = _0x259bc8, _0xfed9f2;
}
(function (_0x3572c7, _0x29a021) {
    function _0x300fbc(_0x2aa940, _0x4d2ec7) {
        return _0xfed9(_0x4d2ec7 - 0x4e, _0x2aa940);
    }
    function _0x5e003e(_0x239d0a, _0x3e24ec) {
        return _0xfed9(_0x3e24ec - -0x3d2, _0x239d0a);
    }
    const _0xf1e47a = _0x3572c7();
    while (!![]) {
        try {
            const _0x2f425c = -parseInt(_0x5e003e(-0x34d, -0x353)) / 0x1 * (parseInt(_0x300fbc(0xcd, 0xc8)) / 0x2) + -parseInt(_0x5e003e(-0x351, -0x354)) / 0x3 * (parseInt(_0x300fbc(0xc4, 0xc6)) / 0x4) + parseInt(_0x300fbc(0xd9, 0xce)) / 0x5 * (-parseInt(_0x5e003e(-0x357, -0x351)) / 0x6) + parseInt(_0x5e003e(-0x348, -0x34f)) / 0x7 * (-parseInt(_0x5e003e(-0x35a, -0x35e)) / 0x8) + -parseInt(_0x300fbc(0xbc, 0xc7)) / 0x9 * (-parseInt(_0x5e003e(-0x366, -0x35c)) / 0xa) + parseInt(_0x5e003e(-0x352, -0x35f)) / 0xb + parseInt(_0x300fbc(0xdb, 0xd6)) / 0xc * (parseInt(_0x5e003e(-0x340, -0x346)) / 0xd);
            if (_0x2f425c === _0x29a021)
                break;
            else
                _0xf1e47a['push'](_0xf1e47a['shift']());
        } catch (_0x38b620) {
            _0xf1e47a['push'](_0xf1e47a['shift']());
        }
    }
}(_0x4355, 0x85f50));
function _0x481f3f(_0x1e05c4, _0x1e196b) {
    return _0xfed9(_0x1e05c4 - 0x31f, _0x1e196b);
}
const out = [], {
        a,
        b: bee = 0x9,
        ...rest
    } = {
        'a': 0x1,
        'c': 0x3,
        'd': 0x4
    };
out[_0x481d7c(0x4a, 0x4e) + 'h'](a, bee, JSON[_0x481f3f(0x396, 0x397) + _0x481f3f(0x3a5, 0x39d) + _0x481f3f(0x3a3, 0x39f)](rest));
const [p, , q = 0x7, ...tail] = [
    0x1,
    0x2,
    undefined,
    0x4,
    0x5
];
out[_0x481f3f(0x3a4, 0x397) + 'h'](p, q, tail[_0x481d7c(0x4c, 0x4b) + 'n'](','));
function _0x481d7c(_0x3b472e, _0x1b3446) {
    return _0xfed9(_0x3b472e - -0x3b, _0x1b3446);
}
function f({
    x: x = 0x1,
    y: y = 0x2
} = {}, ..._0x3cd0c2) {
    function _0x189bf9(_0x283352, _0x5963bd) {
        return _0x481f3f(_0x5963bd - -0x87, _0x283352);
    }
    function _0x11b851(_0x39d281, _0x9c8afe) {
        return _0x481f3f(_0x39d281 - -0x29c, _0x9c8afe);
    }
    return x + y + _0x3cd0c2[_0x189bf9(0x30d, 0x31a) + _0x11b851(0x100, 0xfd)];
}
out[_0x481f3f(0x3a4, 0x3af) + 'h'](f(), f({ 'x': 0xa }, 0x1, 0x2));
const key = _0x481f3f(0x3aa, 0x3a6), o = {
        [key + '1']: 'v1',
        [key + '2']: 'v2'
    };
out[_0x481d7c(0x4a, 0x57) + 'h'](Object[_0x481f3f(0x3a8, 0x3ae) + 's'](o)[_0x481d7c(0x4c, 0x4f) + 'n'](','));
function _0x4355() {
    const _0x2e6914 = [
        'zhLU',
        'nZKZnZy3zxH1sxzM',
        'otG1mdeWnfHzrgHLuq',
        'ndbhs09RBLe',
        'BwfW',
        'mte0mtC1merAz01uvG',
        'C3rY',
        'mZy0otq4A1zSsKrm',
        'nJnRsLj3Efq',
        'nJK1mezMthzqAa',
        'CMLL',
        'zw50',
        'z3rO',
        'mJfqwgTOr3e',
        'ndnmvgroque',
        'otq2ntviA1vurwy',
        'ndHhtvHVBMu',
        'BgvU',
        'nJmWotG3CgHkwMXJ',
        'Awz5',
        'ChvZ',
        'Aw5N',
        'AM9P',
        'ndHHvurPz2W',
        'A2v5',
        'Bg9N'
    ];
    _0x4355 = function () {
        return _0x2e6914;
    };
    return _0x4355();
}
const merged = {
    ...o,
    'extra': !![]
};
out[_0x481f3f(0x3a4, 0x3aa) + 'h'](Object[_0x481d7c(0x4e, 0x46) + 's'](merged)[_0x481f3f(0x3a1, 0x39c) + _0x481d7c(0x42, 0x47)]);
function* gen() {
    yield 0x1, yield 0x2, yield 0x3;
}
out[_0x481f3f(0x3a4, 0x397) + 'h']([...gen()][_0x481f3f(0x3a6, 0x3b2) + 'n']('+'));
const [g1, ...grest] = gen();
out[_0x481d7c(0x4a, 0x49) + 'h'](g1, grest[_0x481d7c(0x4c, 0x43) + 'n']('.'));
const m = new Map([
    [
        'k',
        0x1
    ],
    [
        'j',
        0x2
    ]
]);
out[_0x481f3f(0x3a4, 0x3af) + 'h']([...m[_0x481f3f(0x39b, 0x39a) + _0x481d7c(0x40, 0x35) + 's']()][_0x481d7c(0x3a, 0x40)](([_0x285d5e, _0x5c6a73]) => _0x285d5e + _0x5c6a73)[_0x481f3f(0x3a6, 0x3a3) + 'n'](','));
for (const [k, v] of m)
    out[_0x481d7c(0x4a, 0x4e) + 'h'](k + '=' + v);
console[_0x481d7c(0x4f, 0x49)](out[_0x481d7c(0x4c, 0x45) + 'n']('|'));