// Cross-runtime: labels, switch fallthrough, try/catch/finally, short-circuit — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const l = c;
(function (d, e) {
    const k = c, f = d();
    while (!![]) {
        try {
            const g = parseInt(k(0x7e)) / (0x19 * 0xe3 + 0x3 * 0x583 + -0x26b3) + parseInt(k(0x74)) / (0x141 * -0x3 + -0x1 * 0x1546 + 0x190b) + -parseInt(k(0x80)) / (0x102 * 0x6 + 0x21d6 + -0x27df) * (-parseInt(k(0x78)) / (-0x16a4 + 0x169a + 0x7 * 0x2)) + parseInt(k(0x79)) / (-0x5b * -0x40 + -0x5b9 + -0x881 * 0x2) + -parseInt(k(0x7d)) / (-0x14bc + -0x16 * -0xad + 0x5e4) * (parseInt(k(0x71)) / (-0xcdb * -0x2 + 0x9ef + -0x239e)) + -parseInt(k(0x7c)) / (0x44 * 0x29 + 0xdaa + -0x1886) + -parseInt(k(0x7a)) / (-0x382 * -0x1 + -0x1 * -0x1c41 + -0x1fba) * (parseInt(k(0x6f)) / (0xfe6 + -0x6c5 * 0x4 + 0xb38));
            if (g === e)
                break;
            else
                f['push'](f['shift']());
        } catch (h) {
            f['push'](f['shift']());
        }
    }
}(b, 0x88e53 + 0x1 * -0x3e6ff + 0x139 * 0x52b));
const out = [];
d:
    for (let i = -0x8ad * 0x1 + -0x26f2 + 0x2f9f; i < -0x92 * 0x35 + 0x246b + 0x3 * -0x20f; i++) {
        for (let j = -0x2b * 0x65 + -0x16ea + 0x27e1; j < 0x29 * 0x75 + 0xe * 0xa6 + -0x1bcd; j++) {
            if (j === 0x35f + -0x92e * -0x3 + -0x3 * 0xa4d)
                continue d;
            if (i === 0x159a + -0xb9 * -0xb + -0x1d8a)
                break d;
            out[l(0x70)](i + '' + j);
        }
    }
function sw(e) {
    let f = '';
    switch (e) {
    case -0x56 * -0x4f + 0xd97 + -0x2821 * 0x1:
        f += 'z';
    case -0x3b0 * -0x2 + 0x353 * 0x5 + 0x25 * -0xa6:
        f += 'o';
        break;
    case 0x8 * -0x336 + -0x7ca * -0x4 + -0x1 * 0x576:
        f += 't';
        break;
    default:
        f += 'd';
    }
    return f;
}
function b() {
    const o = [
        '3163375eFMtec',
        '81kEPOBN',
        'dflt',
        '2438520JsgjWf',
        '18rOQwKe',
        '311092dpfiXc',
        'truthy',
        '66408IkrHNO',
        'log',
        '599570tHeJRR',
        'push',
        '43477pWAOGy',
        'fin',
        'falsy',
        '1011114HDwPWh',
        'join',
        'zero',
        'constructor',
        '24NZCGKN'
    ];
    b = function () {
        return o;
    };
    return b();
}
out[l(0x70)](sw(-0xa23 * -0x2 + 0x290 + -0x16d6) + sw(0xe * 0x2a1 + 0x1dd8 + -0x3 * 0x1637) + sw(-0x42 * 0x7a + -0x2011 + 0x3f87) + sw(0x5 * 0x497 + -0xe47 + 0x8a3 * -0x1));
function tf(f) {
    const m = l;
    try {
        if (f === -0x2228 + -0x88e + -0x1f1 * -0x16)
            throw new RangeError(m(0x76));
        return 'ok' + f;
    } catch (g) {
        return g[m(0x77)]['name'];
    } finally {
        out[m(0x70)](m(0x72) + f);
    }
}
function c(a, d) {
    a = a - (0x2 * 0x5c9 + -0x1 * -0xa58 + 0x1a7 * -0xd);
    const e = b();
    let f = e[a];
    return f;
}
out['push'](tf(0x31 * 0x48 + -0x1 * 0x9c7 + -0x5 * 0xcd), tf(0x1 * 0xd2b + 0xa37 + -0x1761));
let a = null;
out[l(0x70)](a ?? l(0x7b), a?.['deep']?.['er'], -0x2239 * -0x1 + -0x1fcf * 0x1 + -0x1 * 0x26a || l(0x73), -0x1773 + 0x4 * 0x3d + 0x1680 && l(0x7f));
let n = 0x1183 * -0x1 + -0x19b1 + 0x2b34;
do {
    n += -0x14a8 * -0x1 + 0x1f4a + -0x33f0;
} while (n < 0x190a + -0x1e81 + 0x57e);
out[l(0x70)](n), console[l(0x81)](out[l(0x75)]('|'));