// Cross-runtime: descriptors, freeze, symbols, enumeration order, JSON — OBFUSCATED.
//
// Generated by `javascript-obfuscator` (numbers as expressions + object keys transformed) from a seed that
// exercises the area named above. The point is the SHAPE, not the source: an
// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a
// loop condition, `super[e]` where the source said `super.m`, a method whose
// key is computed — and that is exactly the syntax a hand-written corpus
// never reaches.
//
// Kept only because Bun and Node agree with each other AND with the
// un-obfuscated seed. The second check is the one that matters: an obfuscator
// that changed the program's meaning would otherwise hand over a fixture
// pinning ITS bug rather than the language.
const p = b;
(function (h, i) {
    const n = b, j = h();
    while (!![]) {
        try {
            const l = -parseInt(n(0x1ff)) / (-0x10b6 * 0x2 + -0x11 * 0x8f + 0x1576 * 0x2) + parseInt(n(0x202)) / (0x1bc9 + 0xdd + 0x27 * -0xbc) + -parseInt(n(0x209)) / (-0x25e7 * -0x1 + 0x2362 * 0x1 + -0x4946) + parseInt(n(0x1f5)) / (0x24c4 + -0x3 * -0x2d7 + -0x2d45) + -parseInt(n(0x204)) / (0x5 * -0x4b9 + -0x1c44 + 0x2 * 0x19f3) * (parseInt(n(0x207)) / (0x6c * -0x1b + -0x1069 + 0x1bd3)) + parseInt(n(0x1f3)) / (-0x1 * 0xcce + -0xd * -0x18d + -0x754) * (-parseInt(n(0x206)) / (0xc84 + 0x238 * -0xc + 0xe24)) + parseInt(n(0x1f1)) / (0x1b49 + -0x133c + -0x804) * (parseInt(n(0x1f4)) / (0x1d24 + 0x55 * -0x4f + -0x2df));
            if (l === i)
                break;
            else
                j['push'](j['shift']());
        } catch (m) {
            j['push'](j['shift']());
        }
    }
}(a, 0x57c7e + 0x4aa36 + 0x1 * -0x6f6cf));
function a() {
    const q = [
        '67278qCDYGz',
        'getOwnPropertySymbols',
        '1165629oPHowk',
        'tag',
        'join',
        '225knCogd',
        'value',
        '67662GmtOxZ',
        '288590caUXhw',
        '1218660clXGuC',
        'one',
        '{\x22n\x22:[1,{\x22d\x22:true}],\x22s\x22:null}',
        'push',
        'parse',
        'set',
        'map',
        'defineProperty',
        'isFrozen',
        'getOwnPropertyDescriptor',
        '404983fkzMoi',
        'freeze',
        'entries',
        '450512jaJYhW',
        'keys',
        '55wSXncG',
        'hidden',
        '104mjwNah'
    ];
    a = function () {
        return q;
    };
    return a();
}
const out = [], c = {};
c['b'] = 0x2, c['2'] = 'two', c['a'] = 0x1, c['1'] = p(0x1f6);
const o = c;
out[p(0x1f8)](Object[p(0x203)](o)[p(0x20b)](','));
const d = {};
function b(c, d) {
    c = c - (0x2b * 0xab + 0x1f7f + -0x3a47);
    const e = a();
    let f = e[c];
    return f;
}
d[p(0x1f2)] = 0x9, d['enumerable'] = ![], Object[p(0x1fc)](o, p(0x205), d), out[p(0x1f8)](Object[p(0x203)](o)[p(0x20b)](','), o[p(0x205)]), out[p(0x1f8)](JSON['stringify'](Object[p(0x1fe)](o, 'hidden')));
const e = {};
e['v'] = 0x1;
const frozen = Object[p(0x200)](e);
out[p(0x1f8)](Reflect[p(0x1fa)](frozen, 'v', -0xc4f * -0x1 + -0x4c9 + -0x784), frozen['v'], Object[p(0x1fd)](frozen));
const sym = Symbol(p(0x20a)), f = {};
f[sym] = 's', f['plain'] = 'p';
const withSym = f;
out[p(0x1f8)](Object['keys'](withSym)[p(0x20b)](','), withSym[sym]), out[p(0x1f8)](Object[p(0x208)](withSym)['length']);
class Box {
    constructor() {
        this['v'] = -0x2 * -0x4f + -0x1900 + 0x1863;
    }
    ['m']() {
    }
}
const bx = new Box(), seen = [];
for (const k in bx)
    seen['push'](k);
out[p(0x1f8)](seen[p(0x20b)](',')), out[p(0x1f8)](JSON['stringify'](JSON[p(0x1f9)](p(0x1f7))));
const g = {};
g['z'] = 0x1, g['y'] = 0x2, out[p(0x1f8)](Object[p(0x201)](g)[p(0x1fb)](([h, i]) => h + i)[p(0x20b)]('')), console['log'](out[p(0x20b)]('|'));