//! `ptr` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "null",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_NULL",
        args: &[],
        returns: AbiType::I64,
        doc: "Retorna ponteiro nulo (0).",
        ts_signature: "null(): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "is_null",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_IS_NULL",
        args: &[AbiType::I64],
        returns: AbiType::Bool,
        doc: "True se ptr == 0.",
        ts_signature: "is_null(p: number): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_READ_I64",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Le i64 do endereco. UNSAFE: caller garante validade/alinhamento.",
        ts_signature: "read_i64(p: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_i32",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_READ_I32",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Le i32 do endereco e estende para i64.",
        ts_signature: "read_i32(p: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_u8",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_READ_U8",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Le u8 do endereco e estende para i64 (0..255).",
        ts_signature: "read_u8(p: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_READ_F64",
        args: &[AbiType::I64],
        returns: AbiType::F64,
        doc: "Le f64 do endereco.",
        ts_signature: "read_f64(p: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_WRITE_I64",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Escreve i64 no endereco.",
        ts_signature: "write_i64(p: number, value: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_i32",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_WRITE_I32",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Escreve i32 (low 32 bits) no endereco.",
        ts_signature: "write_i32(p: number, value: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_u8",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_WRITE_U8",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Escreve u8 (low 8 bits) no endereco.",
        ts_signature: "write_u8(p: number, value: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_WRITE_F64",
        args: &[AbiType::I64, AbiType::F64],
        returns: AbiType::Void,
        doc: "Escreve f64 no endereco.",
        ts_signature: "write_f64(p: number, value: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "copy",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_COPY",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "memmove: copia n bytes de src para dst (overlapping ok).",
        ts_signature: "copy(dst: number, src: number, n: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "copy_nonoverlapping",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_COPY_NONOVERLAPPING",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "memcpy: copia n bytes (regioes nao podem se sobrepor).",
        ts_signature: "copy_nonoverlapping(dst: number, src: number, n: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_WRITE_BYTES",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "memset: preenche n bytes com value (low 8 bits).",
        ts_signature: "write_bytes(dst: number, value: number, n: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "offset",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PTR_OFFSET",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Adiciona n bytes ao ptr.",
        ts_signature: "offset(p: number, n: number): number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "ptr",
    doc: "Operacoes raw sobre ponteiros (std::ptr). UNSAFE — caller verifica validez.",
    members: MEMBERS,
};
