#[path = "gc/rt.rs"]
pub mod gc;
#[path = "io/rt.rs"]
pub mod io;
#[path = "json/rt.rs"]
pub mod json;
#[path = "date/rt.rs"]
pub mod date;
#[path = "fs/rt.rs"]
pub mod fs;
#[path = "math/rt.rs"]
pub mod math;
#[path = "num/rt.rs"]
pub mod num;
#[path = "mem/rt.rs"]
pub mod mem;
#[path = "net/rt.rs"]
pub mod net;
#[path = "trace/rt.rs"]
pub mod trace;
#[path = "alloc/rt.rs"]
pub mod alloc;
#[path = "bigfloat/rt.rs"]
pub mod bigfloat;
#[path = "time/rt.rs"]
pub mod time;
#[path = "env/rt.rs"]
pub mod env;
#[path = "path/rt.rs"]
pub mod path;
#[path = "buffer/rt.rs"]
pub mod buffer;
#[path = "string/rt.rs"]
pub mod string;
#[path = "process/rt.rs"]
pub mod process;
#[path = "ptr/rt.rs"]
pub mod ptr;
#[path = "os/rt.rs"]
pub mod os;
#[path = "collections/rt.rs"]
pub mod collections;
#[path = "hash/rt.rs"]
pub mod hash;
#[path = "hint/rt.rs"]
pub mod hint;
#[path = "fmt/rt.rs"]
pub mod fmt;
#[path = "crypto/rt.rs"]
pub mod crypto;
#[path = "regex/rt.rs"]
pub mod regex;
#[path = "atomic/rt.rs"]
pub mod atomic;
#[path = "sync/rt.rs"]
pub mod sync;
#[path = "thread/rt.rs"]
pub mod thread;
#[path = "parallel/rt.rs"]
pub mod parallel;
#[path = "tls/rt.rs"]
pub mod tls;
#[path = "ui/rt.rs"]
pub mod ui;
#[path = "runtime/rt.rs"]
pub mod runtime;

// rt_all.rs is compiled as a standalone crate by build.rs. Some namespace
// modules reference `crate::namespaces::...`, so we expose a compatibility
// shim with the subset they need in runtime_support.
pub mod namespaces {
    pub use crate::gc;
    pub use crate::trace;
}
