#[path = "gc/rt.rs"]
pub mod gc;
#[path = "io/rt.rs"]
pub mod io;
#[path = "fs/rt.rs"]
pub mod fs;
#[path = "math/rt.rs"]
pub mod math;
#[path = "bigfloat/rt.rs"]
pub mod bigfloat;
#[path = "time/rt.rs"]
pub mod time;
#[path = "env/rt.rs"]
pub mod env;
#[path = "path/rt.rs"]
pub mod path;
#[path = "buffer/rt.rs"]
pub mod buffer;
#[path = "string/rt.rs"]
pub mod string;
#[path = "process/rt.rs"]
pub mod process;
#[path = "os/rt.rs"]
pub mod os;
#[path = "collections/rt.rs"]
pub mod collections;
#[path = "hash/rt.rs"]
pub mod hash;
#[path = "fmt/rt.rs"]
pub mod fmt;
#[path = "crypto/rt.rs"]
pub mod crypto;
// ui namespace is excluded from runtime_support.a — fltk requires cargo
// dependency resolution. JIT registers symbols directly via jit.rs.
