//! `events` namespace registration on the new ABI.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "emitter_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_EMITTER_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Aloca um EventEmitter e retorna o handle.",
        ts_signature: "emitter_new(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "emitter_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_EMITTER_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Libera o EventEmitter.",
        ts_signature: "emitter_free(h: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "on",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_ON",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::U64],
        returns: AbiType::Void,
        doc: "Registra um listener (function pointer raw) para o evento.",
        ts_signature: "on(h: number, name: string, fnPtr: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "off",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_OFF",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::U64],
        returns: AbiType::Void,
        doc: "Remove o primeiro listener com o ponteiro especificado.",
        ts_signature: "off(h: number, name: string, fnPtr: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "remove_all_listeners",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_REMOVE_ALL",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Remove todos os listeners do evento.",
        ts_signature: "remove_all_listeners(h: number, name: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "listener_count",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_LISTENER_COUNT",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Numero de listeners registrados para o evento.",
        ts_signature: "listener_count(h: number, name: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "emit0",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_EMIT0",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Dispara `name` sem argumentos. Retorna 1 se havia listeners, 0 caso contrario.",
        ts_signature: "emit0(h: number, name: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "emit1",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_EVENTS_EMIT1",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::I64],
        returns: AbiType::I64,
        doc: "Dispara `name` com 1 argumento i64. Retorna 1 se havia listeners.",
        ts_signature: "emit1(h: number, name: string, arg0: number): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "events",
    doc: "Sistema de eventos primitivo. Listeners sao function pointers raw, invocados via transmute para extern \"C\" fn.",
    members: MEMBERS,
};
