// Copies the validated obfuscator output into the corpus, with a header that
// says where each file came from and what it is for.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const here = import.meta.dirname;
const out = join(here, "out");
const target = "C:/Users/danie/Documents/GitHub/rts/tests/cross-runtime/obfuscated";
mkdirSync(target, { recursive: true });

const what = {
  strings: "string array + base64 + wrappers + split strings",
  flatten: "control-flow flattening, every function",
  deadcode: "dead-code injection into every branch",
  numbers: "numbers as expressions + object keys transformed",
  everything: "all of the above at once, plus rc4 string encoding",
};

const area = {
  arrays_higher_order: "array methods, sort, holes, reduce chains, groupBy",
  errors_throw: "error hierarchy, rethrow, nested try, custom errors, cause",
  generators_async: "generators, yield*, the iterator protocol driven by hand",
  getters_proxy: "accessors, defineProperty, Proxy traps, Reflect, symbol keys",
  closures_scope: "closures, per-iteration bindings, shadowing, IIFE chains",
  control_flow: "labels, switch fallthrough, try/catch/finally, short-circuit",
  destructure_spread: "destructuring, defaults, rest/spread, computed keys",
  numbers_ops: "numeric coercion, bitwise, precedence, comparison",
  objects_meta: "descriptors, freeze, symbols, enumeration order, JSON",
  proto_classes: "classes, prototypes, getters, static, super, instanceof",
  strings_regex: "string methods, template literals, regex, replace callbacks",
};

let written = 0;
// Only what is NOT already in the corpus. Obfuscation is randomised, so
// re-emitting a name that already exists replaces one program with a different
// one under the same name — and a per-file comparison then reads a corpus
// change as an engine regression. Measured: a regenerated fixture came back as
// one LOST entry that no code change had caused.
const already = new Set(readdirSync(target));
for (const name of readdirSync(out).filter((n) => n.endsWith(".ts"))) {
  const [seed, profile] = name.replace(/\.ts$/, "").split("__");
  const header = [
    `// Cross-runtime: ${area[seed]} — OBFUSCATED.`,
    "//",
    `// Generated by \`javascript-obfuscator\` (${what[profile]}) from a seed that`,
    "// exercises the area named above. The point is the SHAPE, not the source: an",
    "// obfuscator emits legal JavaScript nobody writes by hand — an assignment in a",
    "// loop condition, `super[e]` where the source said `super.m`, a method whose",
    "// key is computed — and that is exactly the syntax a hand-written corpus",
    "// never reaches.",
    "//",
    "// Kept only because Bun and Node agree with each other AND with the",
    "// un-obfuscated seed. The second check is the one that matters: an obfuscator",
    "// that changed the program's meaning would otherwise hand over a fixture",
    "// pinning ITS bug rather than the language.",
    "",
  ].join("\n");
  const file = `obf_${seed}_${profile}.ts`;
  if (already.has(file)) {
    continue;
  }
  writeFileSync(join(target, file), header + readFileSync(join(out, name), "utf8"));
  written += 1;
}
console.log(`escritos: ${written}`);
