//! `crypto` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "random_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_BYTES",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Fills ptr..ptr+len with CSPRNG bytes. 0 ok, -1 err.",
        ts_signature: "random_bytes(ptr: number, len: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "random_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_I64",
        args: &[],
        returns: AbiType::I64,
        doc: "Cryptographically secure i64.",
        ts_signature: "random_i64(): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "random_buffer",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_RANDOM_BUFFER",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Allocates a buffer of `len` random bytes. Handle 0 on error.",
        ts_signature: "random_buffer(len: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "sha256_str",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_SHA256_STR",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "SHA-256 of a UTF-8 string, returned as a 64-char hex string handle.",
        ts_signature: "sha256_str(s: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "sha256_bytes",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_SHA256_BYTES",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "SHA-256 of a raw memory region. Use with buffer.ptr(h).",
        ts_signature: "sha256_bytes(ptr: number, len: number): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "hex_encode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HEX_ENCODE",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Lowercase hex of a memory region.",
        ts_signature: "hex_encode(ptr: number, len: number): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "hex_decode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_HEX_DECODE",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Decodes hex into a buffer handle. 0 on malformed input.",
        ts_signature: "hex_decode(s: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "base64_encode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_BASE64_ENCODE",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Base64 (RFC 4648 padded) of a memory region.",
        ts_signature: "base64_encode(ptr: number, len: number): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "base64_decode",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_CRYPTO_BASE64_DECODE",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Decodes base64 into a buffer handle. 0 on malformed input.",
        ts_signature: "base64_decode(s: string): number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "crypto",
    doc: "Cryptographic primitives: SHA-256, CSPRNG, hex, base64.",
    members: MEMBERS,
};
