use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

// ── Response ──────────────────────────────────────────────────────────────────

pub const RESPONSE_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "status",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_STATUS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "response.status — HTTP status code (number).",
        ts_signature: "readonly status: number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "ok",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_OK",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "response.ok — true se status 200-299.",
        ts_signature: "readonly ok: boolean",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "statusText",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_STATUS_TEXT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.statusText — 'OK', 'Not Found', etc.",
        ts_signature: "readonly statusText: string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "url",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_URL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.url — URL final (após redirects).",
        ts_signature: "readonly url: string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "text",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_TEXT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.text() → string (RTS sync, sem Promise).",
        ts_signature: "text(): Promise<string>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "json",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_JSON",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.json() → JSON handle (RTS sync, sem Promise).",
        ts_signature: "json(): Promise<any>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "blob",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_ARRAY_BUFFER",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.blob() → Buffer handle (RTS sync).",
        ts_signature: "blob(): Promise<Blob>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "arrayBuffer",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_ARRAY_BUFFER",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.arrayBuffer() → Buffer handle (RTS sync).",
        ts_signature: "arrayBuffer(): Promise<ArrayBuffer>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "then",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_THEN",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "response.then(fn) → fn(response). Compatibilidade com Promise.then().",
        ts_signature: "then<T>(fn: (response: Response) => T): T",
        intrinsic: None,
        pure: false,
    },
];

pub const RESPONSE_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Response",
    doc: "Fetch API Response — status/ok/statusText/url/text()/json()/blob()/arrayBuffer().",
    members: RESPONSE_MEMBERS,
};

// ── Promise ───────────────────────────────────────────────────────────────────

pub const PROMISE_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "then",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_PROMISE_THEN",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.then(onFul) — chama onFul(value) ao resolve. Suporta PromiseAsync (#411) com encadeamento real.",
        ts_signature: "then<T>(onFulfilled: (value: any) => T): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "catch",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_PROMISE_CATCH",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.catch(onRej) — captura rejection. Recovers se callback retornar valor.",
        ts_signature: "catch(onRejected: (err: any) => any): Promise<any>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "finally",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_PROMISE_FINALLY",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.finally(fn) — chama fn() ao settle. Mantem state/value original.",
        ts_signature: "finally(onFinally: () => void): Promise<any>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "resolve",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_PROMISE_RESOLVE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Promise.resolve(v) — cria Promise já resolvida.",
        ts_signature: "static resolve<T>(value: T): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    // (cross-runtime #285) Promise.resolve() sem args — equivalente a
    // Promise.resolve(undefined). Reusa o impl passando 0 (null/undefined).
    NamespaceMember {
        name: "resolve",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_PROMISE_RESOLVE_EMPTY",
        args: &[],
        returns: AbiType::I64,
        doc: "Promise.resolve() — cria Promise já resolvida com undefined.",
        ts_signature: "static resolve(): Promise<undefined>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "reject",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_PROMISE_REJECT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Promise.reject(reason) — cria PromiseAsync rejected. Distingue de resolve para .catch/.any/.allSettled.",
        ts_signature: "static reject<T>(reason?: any): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    // (cross-runtime #779/#806) Promise.all/race/any/allSettled — reusam
    // as fns do namespace `promise` que ja sao expostas via SPECS.
    NamespaceMember {
        name: "all",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_ALL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Promise.all(promises) — aguarda todas; fail-fast em rejection.",
        ts_signature: "static all<T>(values: Promise<T>[]): Promise<T[]>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "race",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_RACE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Promise.race(promises) — settle com o resultado da primeira.",
        ts_signature: "static race<T>(values: Promise<T>[]): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "any",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_ANY",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Promise.any(promises) — primeira a fulfill; reject so' se todas falharem.",
        ts_signature: "static any<T>(values: Promise<T>[]): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "allSettled",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_PROMISE_ALL_SETTLED",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Promise.allSettled(promises) — aguarda todas; sempre resolve com Vec de descriptors.",
        ts_signature: "static allSettled<T>(values: Promise<T>[]): Promise<any[]>",
        intrinsic: None,
        pure: false,
    },
];

pub const PROMISE_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Promise",
    doc: "Promise síncrona — then/catch/finally executam imediatamente. await = resolve().",
    members: PROMISE_MEMBERS,
};
