//! `fmt` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "parse_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_PARSE_I64",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Parses an integer. Returns i64::MIN on error.",
        ts_signature: "parse_i64(s: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "parse_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_PARSE_F64",
        args: &[AbiType::StrPtr],
        returns: AbiType::F64,
        doc: "Parses a float. Returns NaN on error.",
        ts_signature: "parse_f64(s: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "parse_bool",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_PARSE_BOOL",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Parses 'true'/'false'/'1'/'0' (case-insensitive). Returns -1 on error.",
        ts_signature: "parse_bool(s: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_I64",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Decimal string of an integer.",
        ts_signature: "fmt_i64(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_F64",
        args: &[AbiType::F64],
        returns: AbiType::Handle,
        doc: "Shortest round-trippable decimal of a float.",
        ts_signature: "fmt_f64(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_bool",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_BOOL",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "'true' when value is non-zero, 'false' otherwise.",
        ts_signature: "fmt_bool(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_hex",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_HEX",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Lowercase hex with `0x` prefix (bits as u64).",
        ts_signature: "fmt_hex(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_bin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_BIN",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Binary with `0b` prefix.",
        ts_signature: "fmt_bin(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_oct",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_OCT",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Octal with `0o` prefix.",
        ts_signature: "fmt_oct(value: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fmt_f64_prec",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FMT_FMT_F64_PREC",
        args: &[AbiType::F64, AbiType::I32],
        returns: AbiType::Handle,
        doc: "Float formatted with a fixed number of decimal places.",
        ts_signature: "fmt_f64_prec(value: number, precision: number): string",
        intrinsic: None,
        pure: true,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "fmt",
    doc: "Parse and format primitives (string <-> number).",
    members: MEMBERS,
};
