//! `string` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── Search ────────────────────────────────────────────────────────
    NamespaceMember {
        name: "contains",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CONTAINS",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when `haystack` contains `needle`.",
        ts_signature: "contains(haystack: string, needle: string): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "starts_with",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_STARTS_WITH",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when `s` starts with `prefix`.",
        ts_signature: "starts_with(s: string, prefix: string): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "ends_with",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_ENDS_WITH",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when `s` ends with `suffix`.",
        ts_signature: "ends_with(s: string, suffix: string): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "find",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_FIND",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Byte index of first occurrence of `needle`, or -1 when absent.",
        ts_signature: "find(s: string, needle: string): number",
        intrinsic: None,
    },

    // ── Transform ─────────────────────────────────────────────────────
    NamespaceMember {
        name: "to_upper",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TO_UPPER",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Uppercase copy (Unicode-aware).",
        ts_signature: "to_upper(s: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "to_lower",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TO_LOWER",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Lowercase copy (Unicode-aware).",
        ts_signature: "to_lower(s: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "trim",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TRIM",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Removes ASCII + Unicode whitespace from both ends.",
        ts_signature: "trim(s: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "trim_start",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TRIM_START",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Removes whitespace from the start.",
        ts_signature: "trim_start(s: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "trim_end",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TRIM_END",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Removes whitespace from the end.",
        ts_signature: "trim_end(s: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "repeat",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_REPEAT",
        args: &[AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Concatenates `s` with itself `n` times.",
        ts_signature: "repeat(s: string, n: number): string",
        intrinsic: None,
    },

    // ── Replace ───────────────────────────────────────────────────────
    NamespaceMember {
        name: "replace",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_REPLACE",
        args: &[AbiType::StrPtr, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Replaces every occurrence of `from` with `to`.",
        ts_signature: "replace(s: string, from: string, to: string): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "replacen",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_REPLACEN",
        args: &[
            AbiType::StrPtr,
            AbiType::StrPtr,
            AbiType::StrPtr,
            AbiType::I64,
        ],
        returns: AbiType::Handle,
        doc: "Replaces the first `n` occurrences of `from` with `to`.",
        ts_signature: "replacen(s: string, from: string, to: string, n: number): string",
        intrinsic: None,
    },

    // ── Split / count / indexing ──────────────────────────────────────
    NamespaceMember {
        name: "char_count",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CHAR_COUNT",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Unicode codepoint count (chars).",
        ts_signature: "char_count(s: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "byte_len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_BYTE_LEN",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Length in UTF-8 bytes.",
        ts_signature: "byte_len(s: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "char_at",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CHAR_AT",
        args: &[AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Character at Unicode index `idx` as a single-char string handle, or 0 out of range.",
        ts_signature: "char_at(s: string, idx: number): string",
        intrinsic: None,
    },
    NamespaceMember {
        name: "char_code_at",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CHAR_CODE_AT",
        args: &[AbiType::StrPtr, AbiType::I64],
        returns: AbiType::I64,
        doc: "Unicode code point at `idx`, or -1 out of range.",
        ts_signature: "char_code_at(s: string, idx: number): number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "string",
    doc: "Rich string operations beyond the basic gc pool.",
    members: MEMBERS,
};
