//! `fs` namespace registration on the new ABI.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "read",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_READ",
        args: &[AbiType::StrPtr, AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Reads up to `bufLen` bytes from `path` into buffer. Returns byte count or -1.",
        ts_signature: "read(path: string, bufPtr: number, bufLen: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "read_all",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_READ_ALL",
        args: &[AbiType::StrPtr, AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Reads entire file into buffer, truncating if needed. Returns bytes written or -1.",
        ts_signature: "read_all(path: string, bufPtr: number, bufLen: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "write",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_WRITE",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Writes data to `path`, truncating existing contents. Returns bytes written or -1.",
        ts_signature: "write(path: string, data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "append",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_APPEND",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Appends data to `path`, creating it when missing. Returns bytes written or -1.",
        ts_signature: "append(path: string, data: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "exists",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_EXISTS",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Returns 1 if the path exists, 0 otherwise.",
        ts_signature: "exists(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "is_file",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_IS_FILE",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Returns 1 if `path` is a regular file.",
        ts_signature: "is_file(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "is_dir",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_IS_DIR",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Returns 1 if `path` is a directory.",
        ts_signature: "is_dir(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "size",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_SIZE",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Returns file size in bytes, or -1 on error.",
        ts_signature: "size(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "modified_ms",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_MODIFIED_MS",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Returns last-modified milliseconds since UNIX epoch, or -1 on error.",
        ts_signature: "modified_ms(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "create_dir",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_CREATE_DIR",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Creates the directory at `path`. Returns 0 on success, -1 on error.",
        ts_signature: "create_dir(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "create_dir_all",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_CREATE_DIR_ALL",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Creates the directory and any missing parents.",
        ts_signature: "create_dir_all(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "remove_dir",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_REMOVE_DIR",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Removes an empty directory.",
        ts_signature: "remove_dir(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "remove_dir_all",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_REMOVE_DIR_ALL",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Removes a directory and all of its contents.",
        ts_signature: "remove_dir_all(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "remove_file",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_REMOVE_FILE",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Removes a file.",
        ts_signature: "remove_file(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "rename",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_RENAME",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Renames `from` to `to`. Returns 0 on success, -1 on error.",
        ts_signature: "rename(from: string, to: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "readdir",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_READDIR",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Lê o conteúdo do diretório e retorna handle de Vec<string-handle> com os nomes (file_name, sem path). Retorna 0 em erro.",
        ts_signature: "readdir(path: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "copy",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_FS_COPY",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Copies file contents. Returns bytes copied or -1.",
        ts_signature: "copy(from: string, to: string): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "fs",
    doc: "Filesystem operations backed by std::fs.",
    members: MEMBERS,
};
