//! THE BOX TREE: what CSS says exists, between the DOM and layout.
//!
//! It exists because CSS generates boxes no element owns — the anonymous boxes
//! of CSS 2.1 §9.2.1.1 and §17.2.1 — and elements that own several, such as an
//! inline that wraps across three lines. While a box's identity was the
//! `NodeIdx`, neither was expressible: `record_node_rect` kept the last one
//! silently, and `union_rect` collapsed the others into their envelope at the
//! very moment they were computed.
//!
//! **This module is the ONLY place that translates between node and box.** If
//! that translation appears in another consumer, `NodeIdx` becomes the identity
//! again through a side door, which is exactly what lot BT-1 exists to close.
//!
//! In this lot the tree is close to a MIRROR: one box per element, and
//! `boxes_of` always returns a slice of length one — that part is still exact,
//! because an anonymous box is never entered into `by_node`. What is no longer
//! true is "none anonymous": `boxes::build` now splits an inline box around a
//! block-level child (CSS 2.1 §9.2.1.1, the first anonymous-box family), so the
//! tree may hold anonymous block boxes a `<div>` inside a `<span>` produces.
//! No generated boxes yet, and no table fixups. Nothing consumes any of this
//! yet — layout still runs over the DOM. The next step of BT-1 swaps the
//! geometry and cache keys.
//!
//! The design, the measured evidence and the nine invariants that break
//! silently are in `docs/ui/html-engine/box-tree.md`. The executable plan is in
//! `docs/superpowers/plans/2026-09-16-box-tree-bt1.md`.

use crate::dom::NodeIdx;
use crate::style::ComputedStyle;
use std::rc::Rc;

mod build;
pub use build::build_mirror;

pub(crate) mod context;
pub use context::{FormattingContext, InnerDisplay, OuterDisplay};

#[cfg(test)]
mod tests;

/// An index into a contiguous arena, the way `NodeIdx` already is for nodes —
/// **plus the generation of the tree that issued it**.
///
/// The generation is not decoration. A `BoxId` is only ever valid in the tree
/// that made it: the tree is rebuilt whole when the document revision changes,
/// and every index then points somewhere else. That is not a hypothesis — it
/// was an out-of-bounds read in `node_of`, caught by the cache-equivalence
/// tests, because cached fragments outlive a rebuild by design.
///
/// Without this field the same mistake compiles and, when the new arena happens
/// to be at least as long, answers the geometry of an unrelated box in silence.
/// With it, every accessor refuses. The cost is one comparison and four bytes.
///
/// `u32` for each half rather than `usize`: a real page has tens of thousands
/// of boxes, not billions, and the pair still fits in one register.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BoxId {
    generation: u32,
    index: u32,
}

impl BoxId {
    /// The position in the arena. Only meaningful together with the generation,
    /// which is why the fields are private and this is the only way out.
    pub fn index(self) -> u32 {
        self.index
    }

    pub fn generation(self) -> u32 {
        self.generation
    }
}
/// Where a box came from — and, with it, where its STYLE comes from.
///
/// **A box does not store a style; it stores the node whose style is its own.**
/// That distinction is the whole reason this enum carries a `NodeIdx` in both
/// variants, and it was not the first design: the box used to hold an
/// `Rc<ComputedStyle>` taken at build time.
///
/// **Why that was wrong.** The tree is memoised by `(revision, style_epoch)`
/// and deliberately NOT by `anim_epoch` — rebuilding the whole tree on every
/// frame of every transition would undo the reason the style memo splits those
/// two apart (see `dom/box_tree.rs`). But `computed_style_idx` DOES include
/// `anim_epoch`. A style captured at build time is therefore stale for the
/// whole duration of an animation, and every consumer reading it would be one
/// frame behind with nothing to say so. Asking the document each time costs a
/// memo hit and an `Rc` clone, and is never stale.
///
/// It is also smaller: no `Rc` per box, and the arena stays two words wider
/// than a plain index instead of four.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxKind {
    /// An element that generates a box. Its style is that element's.
    Element(NodeIdx),
    /// Generated by the CSS rules, with no element behind it.
    ///
    /// It carries the node it INHERITS FROM — the element whose box the CSS
    /// rules split or wrapped to produce it. That is exactly what the spec
    /// asks for: an anonymous box has no declarations of its own and takes the
    /// inherited properties of its generating element.
    Anonymous { inherits_from: NodeIdx },
    /// A run of text. Its style is the enclosing inline element's, which is
    /// also what `collect_runs` already threads down as parameters.
    ///
    /// The text node itself is named so the layout can reach the string, and
    /// `inherits_from` is named separately because a text node HAS NO STYLE of
    /// its own: `computed_style_idx` answers `None` for one, matching only
    /// elements. Storing both is what lets a text box answer the style question
    /// without a special case at every reader.
    Text {
        node: NodeIdx,
        inherits_from: NodeIdx,
    },
}

/// Named `LayoutBox` and not `Box` because `Box` is `std::boxed::Box` — a name
/// collision in every file that touches both.
#[derive(Debug)]
pub struct LayoutBox {
    pub kind: BoxKind,
    pub parent: Option<BoxId>,
    pub children: Vec<BoxId>,
}
#[derive(Debug, Default)]
pub struct BoxTree {
    /// Which build of the tree this is. Every `BoxId` it hands out carries it,
    /// and every accessor refuses one that does not match — see `BoxId`.
    generation: u32,
    arena: Vec<LayoutBox>,
    /// The translation, and the only place it lives.
    ///
    /// `Vec` and not `SmallVec`: in this lot every slice has length one, and
    /// adding a dependency for an allocation that may never be hot is a
    /// measurement nobody has taken. The structure admits several so the
    /// anonymous-box lot does not have to come back here.
    by_node: crate::fasthash::FastMap<NodeIdx, Vec<BoxId>>,
}

impl BoxTree {
    pub fn push_element(&mut self, node: NodeIdx, parent: Option<BoxId>) -> BoxId {
        let id = self.push(BoxKind::Element(node), parent);
        self.by_node.entry(node).or_default().push(id);
        id
    }

    /// A box CSS generates and the document does not have.
    ///
    /// It does not enter `by_node`: that is what makes `node_of` answer `None`,
    /// and what tells it apart from an element. `inherits_from` is the element
    /// whose box was split or wrapped to produce it, and therefore the source
    /// of its style — not an owner, and not reachable through `boxes_of`.
    pub fn push_anonymous(&mut self, inherits_from: NodeIdx, parent: BoxId) -> BoxId {
        self.push(BoxKind::Anonymous { inherits_from }, Some(parent))
    }

    /// A tree for a given build. `build_mirror` passes the document revision,
    /// so two trees of the same document at different revisions never share a
    /// generation, and an id from one is refused by the other.
    pub fn with_generation(generation: u32) -> Self {
        BoxTree {
            generation,
            ..Default::default()
        }
    }

    /// The box behind an id, refusing one issued by another build of the tree.
    ///
    /// Panics rather than answering wrongly: a stale id is a bug at the call
    /// site, and the alternative — reading whatever now sits at that index — is
    /// the silent class this repository refuses. The message names both
    /// generations so the caller knows which tree it kept.
    fn get(&self, id: BoxId) -> &LayoutBox {
        assert_eq!(
            id.generation, self.generation,
            "BoxId from generation {} used on a tree of generation {}: the tree was rebuilt and this id points elsewhere now",
            id.generation, self.generation
        );
        &self.arena[id.index as usize]
    }

    /// A run of text, which inherits the style of the inline element that
    /// encloses it. Enters `by_node` like an element: a text node is a real
    /// node and its geometry is a legitimate question.
    pub fn push_text(&mut self, node: NodeIdx, inherits_from: NodeIdx, parent: BoxId) -> BoxId {
        let id = self.push(
            BoxKind::Text {
                node,
                inherits_from,
            },
            Some(parent),
        );
        self.by_node.entry(node).or_default().push(id);
        id
    }

    fn push(&mut self, kind: BoxKind, parent: Option<BoxId>) -> BoxId {
        let id = BoxId {
            generation: self.generation,
            index: self.arena.len() as u32,
        };
        self.arena.push(LayoutBox {
            kind,
            parent,
            children: Vec::new(),
        });
        if let Some(p) = parent {
            self.arena[p.index as usize].children.push(id);
        }
        id
    }

    /// The boxes a node generated, in creation order.
    ///
    /// Empty for a node that generates none (text, comment, `display:none`),
    /// and of length one for every element while the tree is the mirror.
    pub fn boxes_of(&self, node: NodeIdx) -> &[BoxId] {
        self.by_node.get(&node).map(Vec::as_slice).unwrap_or(&[])
    }

    /// What KIND of box this is. The one accessor that does not translate to a
    /// node, and the reason it exists: a caller that asks "is this anonymous"
    /// by testing `node_of(id).is_none()` gets the right answer today and the
    /// wrong one the day a second kind stops naming a node.
    pub fn kind(&self, id: BoxId) -> BoxKind {
        self.get(id).kind
    }

    /// The node a box belongs to, or `None` when the box is anonymous.
    pub fn node_of(&self, id: BoxId) -> Option<NodeIdx> {
        match self.get(id).kind {
            BoxKind::Element(n) => Some(n),
            // Uma caixa de TEXTO nomeia o seu no, e por isso e consultavel:
            // `getBoundingClientRect` de um no de texto e uma pergunta legitima
            // do DOM, e responde-la precisa de saber que caixas ele gerou.
            BoxKind::Text { node, .. } => Some(node),
            BoxKind::Anonymous { .. } => None,
        }
    }

    /// The node this box takes its style from: the element itself, or — for an
    /// anonymous box — the element whose box the CSS rules split to make it.
    pub fn style_source(&self, id: BoxId) -> NodeIdx {
        match self.get(id).kind {
            BoxKind::Element(n) => n,
            BoxKind::Anonymous { inherits_from } | BoxKind::Text { inherits_from, .. } => {
                inherits_from
            }
        }
    }

    /// The computed style of a box, asked of the document EACH TIME.
    ///
    /// Never cached in the box, and the reason is in `BoxKind`: the tree is
    /// memoised without `anim_epoch` on purpose, so a style captured when the
    /// tree was built is stale for the whole of an animation. This costs a memo
    /// hit and an `Rc` clone, and is never wrong.
    ///
    /// `None` only when the source node has no computed style — which the
    /// cascade answers for a non-element, and `build_mirror` already refuses to
    /// make a box for one.
    pub fn style(&self, dom: &crate::dom::Dom, id: BoxId) -> Option<Rc<ComputedStyle>> {
        dom.computed_style_idx(self.style_source(id))
    }

    pub fn children(&self, id: BoxId) -> &[BoxId] {
        &self.get(id).children
    }

    pub fn parent(&self, id: BoxId) -> Option<BoxId> {
        self.get(id).parent
    }

    /// The top-level boxes — those with no parent. They are the document's
    /// children, and where a traversal starts, as `layout_document` already
    /// does.
    pub fn roots(&self) -> impl Iterator<Item = BoxId> + '_ {
        self.arena
            .iter()
            .enumerate()
            .filter(|(_, b)| b.parent.is_none())
            .map(|(i, _)| BoxId {
                generation: self.generation,
                index: i as u32,
            })
    }

    pub fn len(&self) -> usize {
        self.arena.len()
    }

    pub fn is_empty(&self) -> bool {
        self.arena.is_empty()
    }
}
