//! THE BOX TREE: what CSS says exists, between the DOM and layout.
//!
//! It exists because CSS generates boxes no element owns — the anonymous boxes
//! of CSS 2.1 §9.2.1.1 and §17.2.1 — and elements that own several, such as an
//! inline that wraps across three lines. While a box's identity was the
//! `NodeIdx`, neither was expressible: `record_node_rect` kept the last one
//! silently, and `union_rect` collapsed the others into their envelope at the
//! very moment they were computed.
//!
//! **This module is the ONLY place that translates between node and box.** If
//! that translation appears in another consumer, `NodeIdx` becomes the identity
//! again through a side door, which is exactly what lot BT-1 exists to close.
//!
//! In this lot the tree is close to a MIRROR: one box per element, and
//! `boxes_of` always returns a slice of length one — that part is still exact,
//! because an anonymous box is never entered into `by_node`. What is no longer
//! true is "none anonymous": `boxes::build` now splits an inline box around a
//! block-level child (CSS 2.1 §9.2.1.1, the first anonymous-box family), so the
//! tree may hold anonymous block boxes a `<div>` inside a `<span>` produces.
//! No generated boxes yet, and no table fixups. Nothing consumes any of this
//! yet — layout still runs over the DOM. The next step of BT-1 swaps the
//! geometry and cache keys.
//!
//! The design, the measured evidence and the nine invariants that break
//! silently are in `docs/ui/html-engine/box-tree.md`. The executable plan is in
//! `docs/superpowers/plans/2026-09-16-box-tree-bt1.md`.

use crate::dom::NodeIdx;
use crate::style::ComputedStyle;
use std::rc::Rc;

mod build;
pub use build::build_mirror;

#[cfg(test)]
mod tests;

/// An index into a contiguous arena, the way `NodeIdx` already is for nodes.
///
/// Not `Rc<RefCell<LayoutBox>>`: the tree is built in one pass, read many
/// times, and dropped whole. It is also what lets the cache key stay `Copy` and
/// cheap to compare, which is what `FragmentKey` needs.
///
/// `u32` rather than `usize`: a real page has tens of thousands of boxes, not
/// billions, and the cache key is compared millions of times per frame — half
/// the size is half the cache line.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BoxId(pub u32);

/// Where a box came from — and, with it, where its STYLE comes from.
///
/// **A box does not store a style; it stores the node whose style is its own.**
/// That distinction is the whole reason this enum carries a `NodeIdx` in both
/// variants, and it was not the first design: the box used to hold an
/// `Rc<ComputedStyle>` taken at build time.
///
/// **Why that was wrong.** The tree is memoised by `(revision, style_epoch)`
/// and deliberately NOT by `anim_epoch` — rebuilding the whole tree on every
/// frame of every transition would undo the reason the style memo splits those
/// two apart (see `dom/box_tree.rs`). But `computed_style_idx` DOES include
/// `anim_epoch`. A style captured at build time is therefore stale for the
/// whole duration of an animation, and every consumer reading it would be one
/// frame behind with nothing to say so. Asking the document each time costs a
/// memo hit and an `Rc` clone, and is never stale.
///
/// It is also smaller: no `Rc` per box, and the arena stays two words wider
/// than a plain index instead of four.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxKind {
    /// An element that generates a box. Its style is that element's.
    Element(NodeIdx),
    /// Generated by the CSS rules, with no element behind it.
    ///
    /// It carries the node it INHERITS FROM — the element whose box the CSS
    /// rules split or wrapped to produce it. That is exactly what the spec
    /// asks for: an anonymous box has no declarations of its own and takes the
    /// inherited properties of its generating element.
    Anonymous { inherits_from: NodeIdx },
}

/// Named `LayoutBox` and not `Box` because `Box` is `std::boxed::Box` — a name
/// collision in every file that touches both.
#[derive(Debug)]
pub struct LayoutBox {
    pub kind: BoxKind,
    pub parent: Option<BoxId>,
    pub children: Vec<BoxId>,
}
#[derive(Debug, Default)]
pub struct BoxTree {
    arena: Vec<LayoutBox>,
    /// The translation, and the only place it lives.
    ///
    /// `Vec` and not `SmallVec`: in this lot every slice has length one, and
    /// adding a dependency for an allocation that may never be hot is a
    /// measurement nobody has taken. The structure admits several so the
    /// anonymous-box lot does not have to come back here.
    by_node: crate::fasthash::FastMap<NodeIdx, Vec<BoxId>>,
}

impl BoxTree {
    pub fn push_element(&mut self, node: NodeIdx, parent: Option<BoxId>) -> BoxId {
        let id = self.push(BoxKind::Element(node), parent);
        self.by_node.entry(node).or_default().push(id);
        id
    }

    /// A box CSS generates and the document does not have.
    ///
    /// It does not enter `by_node`: that is what makes `node_of` answer `None`,
    /// and what tells it apart from an element. `inherits_from` is the element
    /// whose box was split or wrapped to produce it, and therefore the source
    /// of its style — not an owner, and not reachable through `boxes_of`.
    pub fn push_anonymous(&mut self, inherits_from: NodeIdx, parent: BoxId) -> BoxId {
        self.push(BoxKind::Anonymous { inherits_from }, Some(parent))
    }

    fn push(&mut self, kind: BoxKind, parent: Option<BoxId>) -> BoxId {
        let id = BoxId(self.arena.len() as u32);
        self.arena.push(LayoutBox {
            kind,
            parent,
            children: Vec::new(),
        });
        if let Some(p) = parent {
            self.arena[p.0 as usize].children.push(id);
        }
        id
    }

    /// The boxes a node generated, in creation order.
    ///
    /// Empty for a node that generates none (text, comment, `display:none`),
    /// and of length one for every element while the tree is the mirror.
    pub fn boxes_of(&self, node: NodeIdx) -> &[BoxId] {
        self.by_node.get(&node).map(Vec::as_slice).unwrap_or(&[])
    }

    /// The node a box belongs to, or `None` when the box is anonymous.
    pub fn node_of(&self, id: BoxId) -> Option<NodeIdx> {
        match self.arena[id.0 as usize].kind {
            BoxKind::Element(n) => Some(n),
            BoxKind::Anonymous { .. } => None,
        }
    }

    /// The node this box takes its style from: the element itself, or — for an
    /// anonymous box — the element whose box the CSS rules split to make it.
    pub fn style_source(&self, id: BoxId) -> NodeIdx {
        match self.arena[id.0 as usize].kind {
            BoxKind::Element(n) => n,
            BoxKind::Anonymous { inherits_from } => inherits_from,
        }
    }

    /// The computed style of a box, asked of the document EACH TIME.
    ///
    /// Never cached in the box, and the reason is in `BoxKind`: the tree is
    /// memoised without `anim_epoch` on purpose, so a style captured when the
    /// tree was built is stale for the whole of an animation. This costs a memo
    /// hit and an `Rc` clone, and is never wrong.
    ///
    /// `None` only when the source node has no computed style — which the
    /// cascade answers for a non-element, and `build_mirror` already refuses to
    /// make a box for one.
    pub fn style(&self, dom: &crate::dom::Dom, id: BoxId) -> Option<Rc<ComputedStyle>> {
        dom.computed_style_idx(self.style_source(id))
    }

    pub fn children(&self, id: BoxId) -> &[BoxId] {
        &self.arena[id.0 as usize].children
    }

    pub fn parent(&self, id: BoxId) -> Option<BoxId> {
        self.arena[id.0 as usize].parent
    }

    /// The top-level boxes — those with no parent. They are the document's
    /// children, and where a traversal starts, as `layout_document` already
    /// does.
    pub fn roots(&self) -> impl Iterator<Item = BoxId> + '_ {
        self.arena
            .iter()
            .enumerate()
            .filter(|(_, b)| b.parent.is_none())
            .map(|(i, _)| BoxId(i as u32))
    }

    pub fn len(&self) -> usize {
        self.arena.len()
    }

    pub fn is_empty(&self) -> bool {
        self.arena.is_empty()
    }
}
