//! THE BOX TREE: what CSS says exists, between the DOM and layout.
//!
//! It exists because CSS generates boxes no element owns — the anonymous boxes
//! of CSS 2.1 §9.2.1.1 and §17.2.1 — and elements that own several, such as an
//! inline that wraps across three lines. While a box's identity was the
//! `NodeIdx`, neither was expressible: `record_node_rect` kept the last one
//! silently, and `union_rect` collapsed the others into their envelope at the
//! very moment they were computed.
//!
//! **This module is the ONLY place that translates between node and box.** If
//! that translation appears in another consumer, `NodeIdx` becomes the identity
//! again through a side door, which is exactly what lot BT-1 exists to close.
//!
//! In this lot the tree is a MIRROR: one box per element, none anonymous, none
//! generated, and `boxes_of` always returns a slice of length one. Nothing
//! consumes it yet — layout still runs over the DOM. The next step of BT-1
//! swaps the geometry and cache keys, and it is because this is a mirror that
//! the swap cannot change any answer.
//!
//! The design, the measured evidence and the nine invariants that break
//! silently are in `docs/ui/html-engine/box-tree.md`. The executable plan is in
//! `docs/superpowers/plans/2026-09-16-box-tree-bt1.md`.

use crate::dom::NodeIdx;
use crate::style::ComputedStyle;
use std::rc::Rc;

mod build;
pub use build::build_mirror;

#[cfg(test)]
mod tests;

/// An index into a contiguous arena, the way `NodeIdx` already is for nodes.
///
/// Not `Rc<RefCell<LayoutBox>>`: the tree is built in one pass, read many
/// times, and dropped whole. It is also what lets the cache key stay `Copy` and
/// cheap to compare, which is what `FragmentKey` needs.
///
/// `u32` rather than `usize`: a real page has tens of thousands of boxes, not
/// billions, and the cache key is compared millions of times per frame — half
/// the size is half the cache line.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BoxId(pub u32);

/// Where a box came from.
///
/// The anonymous variant is not produced by `build_mirror` yet, and it is here
/// on purpose: without it, the anonymous-box lot would have to come back and
/// change the type, the tests and everyone reading them. The test
/// `an_anonymous_box_answers_no_node` pins the difference that matters.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoxKind {
    /// An element that generates a box.
    Element(NodeIdx),
    /// Generated by the CSS rules, with no element behind it.
    Anonymous,
}

/// Named `LayoutBox` and not `Box` because `Box` is `std::boxed::Box` — a name
/// collision in every file that touches both.
#[derive(Debug)]
pub struct LayoutBox {
    pub kind: BoxKind,
    /// The COMPUTED style, shared.
    ///
    /// `computed_style_idx` already returns an `Rc` and shares it when there is
    /// no animation; a `ComputedStyle` is about a kilobyte. Several boxes of
    /// one element therefore share the allocation rather than cloning it — and
    /// that is what makes it cheap for an element to own N boxes, which is the
    /// point of the lot.
    ///
    /// An ANONYMOUS box inherits the `Rc` of whoever generated it, which is
    /// what the CSS rules ask for: an anonymous box has no declarations of its
    /// own.
    pub style: Rc<ComputedStyle>,
    pub parent: Option<BoxId>,
    pub children: Vec<BoxId>,
}

#[derive(Debug, Default)]
pub struct BoxTree {
    arena: Vec<LayoutBox>,
    /// The translation, and the only place it lives.
    ///
    /// `Vec` and not `SmallVec`: in this lot every slice has length one, and
    /// adding a dependency for an allocation that may never be hot is a
    /// measurement nobody has taken. The structure admits several so the
    /// anonymous-box lot does not have to come back here.
    by_node: crate::fasthash::FastMap<NodeIdx, Vec<BoxId>>,
}

impl BoxTree {
    pub fn push_element(
        &mut self,
        node: NodeIdx,
        style: Rc<ComputedStyle>,
        parent: Option<BoxId>,
    ) -> BoxId {
        let id = self.push(BoxKind::Element(node), style, parent);
        self.by_node.entry(node).or_default().push(id);
        id
    }

    /// A box CSS generates and the document does not have. It does not enter
    /// `by_node`: that is what makes `node_of` answer `None`, and what tells it
    /// apart from an element.
    pub fn push_anonymous(&mut self, style: Rc<ComputedStyle>, parent: BoxId) -> BoxId {
        self.push(BoxKind::Anonymous, style, Some(parent))
    }

    fn push(&mut self, kind: BoxKind, style: Rc<ComputedStyle>, parent: Option<BoxId>) -> BoxId {
        let id = BoxId(self.arena.len() as u32);
        self.arena.push(LayoutBox {
            kind,
            style,
            parent,
            children: Vec::new(),
        });
        if let Some(p) = parent {
            self.arena[p.0 as usize].children.push(id);
        }
        id
    }

    /// The boxes a node generated, in creation order.
    ///
    /// Empty for a node that generates none (text, comment, `display:none`),
    /// and of length one for every element while the tree is the mirror.
    pub fn boxes_of(&self, node: NodeIdx) -> &[BoxId] {
        self.by_node.get(&node).map(Vec::as_slice).unwrap_or(&[])
    }

    /// The node a box belongs to, or `None` when the box is anonymous.
    pub fn node_of(&self, id: BoxId) -> Option<NodeIdx> {
        match self.arena[id.0 as usize].kind {
            BoxKind::Element(n) => Some(n),
            BoxKind::Anonymous => None,
        }
    }

    pub fn style(&self, id: BoxId) -> &Rc<ComputedStyle> {
        &self.arena[id.0 as usize].style
    }

    pub fn children(&self, id: BoxId) -> &[BoxId] {
        &self.arena[id.0 as usize].children
    }

    pub fn parent(&self, id: BoxId) -> Option<BoxId> {
        self.arena[id.0 as usize].parent
    }

    /// The top-level boxes — those with no parent. They are the document's
    /// children, and where a traversal starts, as `layout_document` already
    /// does.
    pub fn roots(&self) -> impl Iterator<Item = BoxId> + '_ {
        self.arena
            .iter()
            .enumerate()
            .filter(|(_, b)| b.parent.is_none())
            .map(|(i, _)| BoxId(i as u32))
    }

    pub fn len(&self) -> usize {
        self.arena.len()
    }

    pub fn is_empty(&self) -> bool {
        self.arena.is_empty()
    }
}
