pub use rts_abi::*;

pub mod signature;

pub const GLOBAL_CLASS_SPECS: &[&GlobalClassSpec] = &[
    &crate::namespaces::globals::string::abi::STRING_CLASS_SPEC,
    &crate::namespaces::globals::number::NUMBER_CLASS_SPEC,
    &crate::namespaces::globals::date::abi::CLASS_SPEC,
    &crate::namespaces::globals::regexp::REGEXP_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::CLASS_SPEC,
    &crate::namespaces::globals::error::abi::TYPE_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::RANGE_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::REF_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::SYNTAX_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::URI_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::EVAL_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::error::abi::AGGREGATE_ERROR_CLASS_SPEC,
    &crate::namespaces::globals::events::CLASS_SPEC,
    &crate::namespaces::globals::text_encoding::class_spec::TEXT_ENCODER_CLASS_SPEC,
    &crate::namespaces::globals::text_encoding::class_spec::TEXT_DECODER_CLASS_SPEC,
    &crate::namespaces::globals::fetch::class_spec::RESPONSE_CLASS_SPEC,
    &crate::namespaces::globals::fetch::class_spec::REQUEST_CLASS_SPEC,
    &crate::namespaces::globals::fetch::class_spec::PROMISE_CLASS_SPEC,
    &crate::namespaces::globals::url::class_spec::URL_CLASS_SPEC,
    &crate::namespaces::globals::url::class_spec::URLSP_CLASS_SPEC,
    &crate::namespaces::globals::function::FUNCTION_CLASS_SPEC,
    &crate::namespaces::globals::symbol::SYMBOL_CLASS_SPEC,
    &crate::namespaces::globals::boolean::BOOLEAN_CLASS_SPEC,
    &crate::namespaces::globals::bigint::BIGINT_CLASS_SPEC,
    &crate::namespaces::globals::weakmap::WEAKMAP_CLASS_SPEC,
    &crate::namespaces::globals::weakset::WEAKSET_CLASS_SPEC,
    &crate::namespaces::globals::weakref::WEAKREF_CLASS_SPEC,
    &crate::namespaces::globals::finalization_registry::FINALIZATION_REGISTRY_CLASS_SPEC,
    &crate::namespaces::globals::headers::HEADERS_CLASS_SPEC,
    &crate::namespaces::globals::abort::ABORT_CONTROLLER_CLASS_SPEC,
    &crate::namespaces::globals::abort::ABORT_SIGNAL_CLASS_SPEC,
    &crate::namespaces::globals::event_target::EVENT_TARGET_CLASS_SPEC,
    &crate::namespaces::globals::event_target::EVENT_CLASS_SPEC,
    &crate::namespaces::globals::dom_exception::DOM_EXCEPTION_CLASS_SPEC,
    &crate::namespaces::globals::blob::BLOB_CLASS_SPEC,
    &crate::namespaces::globals::blob::FILE_CLASS_SPEC,
    &crate::namespaces::globals::form_data::FORM_DATA_CLASS_SPEC,
    &crate::namespaces::globals::dataview::abi::ARRAY_BUFFER_CLASS_SPEC,
    &crate::namespaces::globals::dataview::abi::DATA_VIEW_CLASS_SPEC,
    &crate::namespaces::globals::intl::NUMBER_FORMAT_CLASS_SPEC,
    &crate::namespaces::globals::intl::DATE_TIME_FORMAT_CLASS_SPEC,
    &crate::namespaces::globals::intl::COLLATOR_CLASS_SPEC,
    &crate::namespaces::globals::intl::SEGMENTER_CLASS_SPEC,
    &crate::namespaces::globals::intl::PLURAL_RULES_CLASS_SPEC,
    &crate::namespaces::globals::intl::LIST_FORMAT_CLASS_SPEC,
    &crate::namespaces::globals::intl::RELATIVE_TIME_FORMAT_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::READABLE_STREAM_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::READER_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::CONTROLLER_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::TRANSFORM_STREAM_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::WRITABLE_STREAM_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::WRITER_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::TEXT_ENCODER_STREAM_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::TEXT_DECODER_STREAM_CLASS_SPEC,
    &crate::namespaces::globals::readable_stream::abi::COMPRESSION_STREAM_CLASS_SPEC,
    &crate::namespaces::globals::message_channel::MESSAGE_CHANNEL_CLASS_SPEC,
    &crate::namespaces::globals::message_channel::MESSAGE_PORT_CLASS_SPEC,
];

pub fn global_class_lookup(name: &str) -> Option<&'static GlobalClassSpec> {
    GLOBAL_CLASS_SPECS.iter().copied().find(|s| s.name == name)
}

pub const SPECS: &[&NamespaceSpec] = &[
    &crate::namespaces::gc::abi::SPEC,
    &crate::namespaces::io::SPEC,
    &crate::namespaces::json::SPEC,
    &crate::namespaces::date::SPEC,
    &crate::namespaces::fs::SPEC,
    &crate::namespaces::math::SPEC,
    &crate::namespaces::net::SPEC,
    &crate::namespaces::num::SPEC,
    &crate::namespaces::mem::SPEC,
    &crate::namespaces::trace::SPEC,
    &crate::namespaces::alloc::SPEC,
    &crate::namespaces::bigfloat::SPEC,
    &crate::namespaces::time::SPEC,
    &crate::namespaces::env::SPEC,
    &crate::namespaces::path::SPEC,
    &crate::namespaces::buffer::SPEC,
    &crate::namespaces::ffi::SPEC,
    &crate::namespaces::atomic::SPEC,
    &crate::namespaces::sync::SPEC,
    &crate::namespaces::globals::string::abi::SPEC,
    &crate::namespaces::process::SPEC,
    &crate::namespaces::promise::SPEC,
    &crate::namespaces::ptr::SPEC,
    &crate::namespaces::os::SPEC,
    &crate::namespaces::collections::SPEC,
    &crate::namespaces::hash::SPEC,
    &crate::namespaces::hint::SPEC,
    &crate::namespaces::http_server::SPEC,
    &crate::namespaces::fmt::SPEC,
    &crate::namespaces::crypto::SPEC,
    &crate::namespaces::regex::SPEC,
    &crate::namespaces::audio::SPEC,
    #[cfg(feature = "asio")]
    &crate::namespaces::asio_audio::abi::SPEC,
    &crate::namespaces::runtime::SPEC,
    &crate::namespaces::test::SPEC,
    &crate::namespaces::thread::SPEC,
    &crate::namespaces::parallel::SPEC,
    &crate::namespaces::tls::SPEC,
    &crate::namespaces::globals::json::abi::SPEC,
    &crate::namespaces::globals::json5::abi::SPEC,
    &crate::namespaces::globals::console::abi::SPEC,
    &crate::namespaces::globals::timers::abi::SPEC,
    &crate::namespaces::globals::fetch::abi::SPEC,
    &crate::namespaces::globals::text_encoding::abi::SPEC,
    &crate::namespaces::globals::performance::abi::SPEC,
    &crate::namespaces::globals::url::abi::SPEC,
    &crate::namespaces::globals::global_this::abi::SPEC,
    &crate::namespaces::events::SPEC,
];

pub fn lookup(qualified: &str) -> Option<(&'static NamespaceSpec, &'static NamespaceMember)> {
    let (ns_name, fn_name) = qualified.split_once('.')?;
    let spec = SPECS.iter().copied().find(|spec| spec.name == ns_name)?;
    let member = spec.members.iter().find(|m| m.name == fn_name)?;
    Some((spec, member))
}
