use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "setTimeout",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TIMERS_SET_TIMEOUT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Chama callback(0) após delay_ms milissegundos. Retorna timer handle.",
        ts_signature: "setTimeout(callback: () => void, ms: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "clearTimeout",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TIMERS_CLEAR_TIMEOUT",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Cancela um timer criado por setTimeout.",
        ts_signature: "clearTimeout(handle: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setInterval",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TIMERS_SET_INTERVAL",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Chama callback(0) repetidamente a cada interval_ms. Retorna timer handle.",
        ts_signature: "setInterval(callback: () => void, ms: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "clearInterval",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TIMERS_CLEAR_INTERVAL",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Para um intervalo criado por setInterval.",
        ts_signature: "clearInterval(handle: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "setImmediate",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TIMERS_SET_IMMEDIATE",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Chama callback(0) o mais rápido possível (delay=0). Retorna timer handle.",
        ts_signature: "setImmediate(callback: () => void): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "clearImmediate",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_TIMERS_CLEAR_IMMEDIATE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Cancela um setImmediate pendente.",
        ts_signature: "clearImmediate(handle: number): void",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "timers",
    doc: "setTimeout / clearTimeout / setInterval / clearInterval / setImmediate / clearImmediate.",
    members: MEMBERS,
};
