use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const FORM_DATA_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_FORM_DATA_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "new FormData()",
        ts_signature: "new FormData()",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "append",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_APPEND",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "fd.append(name, value)",
        ts_signature: "append(name: string, value: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "set",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_SET",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "fd.set(name, value)",
        ts_signature: "set(name: string, value: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "delete",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_DELETE",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "fd.delete(name)",
        ts_signature: "delete(name: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "get",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_GET",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "fd.get(name) — primeiro valor.",
        ts_signature: "get(name: string): string | null",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "getAll",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_GET_ALL",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "fd.getAll(name) — todos os valores.",
        ts_signature: "getAll(name: string): string[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "has",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_HAS",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "fd.has(name)",
        ts_signature: "has(name: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "entries",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_ENTRIES",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "fd.entries()",
        ts_signature: "entries(): IterableIterator<[string, string]>",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "keys",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_KEYS",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "fd.keys()",
        ts_signature: "keys(): IterableIterator<string>",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "values",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FORM_DATA_VALUES",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "fd.values()",
        ts_signature: "values(): IterableIterator<string>",
        intrinsic: None,
        pure: true,
    },
];

pub const FORM_DATA_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "FormData",
    doc: "FormData — multimap case-sensitive de form fields.",
    members: FORM_DATA_MEMBERS,
};
