//! `math` namespace — registration on the new ABI.
//!
//! Minimal surface to unblock numeric benchmarks (e.g. Monte Carlo pi):
//! a seeded xorshift PRNG plus the usual f64 intrinsics wrapped as thin
//! `extern "C"` shims.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "random",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_RANDOM",
        args: &[],
        returns: AbiType::F64,
        doc: "Returns a uniformly distributed f64 in [0, 1) from a thread-local xorshift64 PRNG.",
        ts_signature: "random(): number",
    },
    NamespaceMember {
        name: "seed",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_SEED",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Seeds the PRNG. Zero is replaced by the default seed.",
        ts_signature: "seed(s: number): void",
    },
    NamespaceMember {
        name: "sqrt",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_SQRT",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Square root.",
        ts_signature: "sqrt(x: number): number",
    },
    NamespaceMember {
        name: "floor",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_FLOOR",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Largest integer <= x.",
        ts_signature: "floor(x: number): number",
    },
    NamespaceMember {
        name: "ceil",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_CEIL",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Smallest integer >= x.",
        ts_signature: "ceil(x: number): number",
    },
    NamespaceMember {
        name: "round",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ROUND",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Rounds to nearest; ties go to +Infinity to match JS semantics.",
        ts_signature: "round(x: number): number",
    },
    NamespaceMember {
        name: "abs",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ABS",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Absolute value.",
        ts_signature: "abs(x: number): number",
    },
    NamespaceMember {
        name: "pow",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_POW",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "base raised to exp.",
        ts_signature: "pow(base: number, exp: number): number",
    },
    NamespaceMember {
        name: "min",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_MIN",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "Minimum of two values.",
        ts_signature: "min(a: number, b: number): number",
    },
    NamespaceMember {
        name: "max",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_MAX",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "Maximum of two values.",
        ts_signature: "max(a: number, b: number): number",
    },
    NamespaceMember {
        name: "sin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_SIN",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Sine (radians).",
        ts_signature: "sin(x: number): number",
    },
    NamespaceMember {
        name: "cos",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_COS",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Cosine (radians).",
        ts_signature: "cos(x: number): number",
    },
    NamespaceMember {
        name: "log",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_LOG",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Natural logarithm.",
        ts_signature: "log(x: number): number",
    },
    NamespaceMember {
        name: "exp",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_EXP",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "e^x.",
        ts_signature: "exp(x: number): number",
    },
    NamespaceMember {
        name: "pi",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_PI",
        args: &[],
        returns: AbiType::F64,
        doc: "Archimedes' constant.",
        ts_signature: "pi(): number",
    },
    NamespaceMember {
        name: "e",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_E",
        args: &[],
        returns: AbiType::F64,
        doc: "Euler's number.",
        ts_signature: "e(): number",
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "math",
    doc: "Floating-point intrinsics and a seeded PRNG.",
    members: MEMBERS,
};
