//! `math` namespace — registration on the new ABI.
//!
//! Completa #20: f64 e i64 primitives, trigonometria, min/max/clamp,
//! constantes e xorshift PRNG. Constantes são expostas como fns
//! zero-arg até o codegen aprender `MemberKind::Constant` real.

use crate::abi::{AbiType, Intrinsic, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── Basic ─────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "floor",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_FLOOR",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Largest integer <= x.",
        ts_signature: "floor(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "ceil",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_CEIL",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Smallest integer >= x.",
        ts_signature: "ceil(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "round",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ROUND",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Rounds to nearest; ties go to +Infinity to match JS semantics.",
        ts_signature: "round(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "trunc",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_TRUNC",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Truncates fractional part (rounds toward zero).",
        ts_signature: "trunc(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "sqrt",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_SQRT",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Square root.",
        ts_signature: "sqrt(x: number): number",
        intrinsic: Some(Intrinsic::Sqrt),
    },
    NamespaceMember {
        name: "cbrt",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_CBRT",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Cube root.",
        ts_signature: "cbrt(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "pow",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_POW",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "base raised to exp.",
        ts_signature: "pow(base: number, exp: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "exp",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_EXP",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "e^x.",
        ts_signature: "exp(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "ln",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_LN",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Natural logarithm (base e).",
        ts_signature: "ln(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "log2",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_LOG2",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Base-2 logarithm.",
        ts_signature: "log2(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "log10",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_LOG10",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Base-10 logarithm.",
        ts_signature: "log10(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "abs_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ABS_F64",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Absolute value (f64).",
        ts_signature: "abs_f64(x: number): number",
        intrinsic: Some(Intrinsic::AbsF64),
    },
    NamespaceMember {
        name: "abs_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ABS_I64",
        args: &[AbiType::I64],
        returns: AbiType::I64,
        doc: "Absolute value (i64); i64::MIN maps to itself (wrapping).",
        ts_signature: "abs_i64(x: number): number",
        intrinsic: Some(Intrinsic::AbsI64),
    },
    // ── Trig ──────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "sin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_SIN",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Sine (radians).",
        ts_signature: "sin(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "cos",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_COS",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Cosine (radians).",
        ts_signature: "cos(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "tan",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_TAN",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Tangent (radians).",
        ts_signature: "tan(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "asin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ASIN",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Arc sine (returns radians).",
        ts_signature: "asin(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "acos",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ACOS",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Arc cosine (returns radians).",
        ts_signature: "acos(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "atan",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ATAN",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Arc tangent (returns radians).",
        ts_signature: "atan(x: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "atan2",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_ATAN2",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "atan2(y, x) — angle (radians) of the 2D vector (x, y).",
        ts_signature: "atan2(y: number, x: number): number",
        intrinsic: None,
    },
    // ── Min / max / clamp ─────────────────────────────────────────────────
    NamespaceMember {
        name: "min_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_MIN_F64",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "Minimum of two f64 values (NaN-aware).",
        ts_signature: "min_f64(a: number, b: number): number",
        intrinsic: Some(Intrinsic::MinF64),
    },
    NamespaceMember {
        name: "max_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_MAX_F64",
        args: &[AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "Maximum of two f64 values (NaN-aware).",
        ts_signature: "max_f64(a: number, b: number): number",
        intrinsic: Some(Intrinsic::MaxF64),
    },
    NamespaceMember {
        name: "min_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_MIN_I64",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Minimum of two i64 values.",
        ts_signature: "min_i64(a: number, b: number): number",
        intrinsic: Some(Intrinsic::MinI64),
    },
    NamespaceMember {
        name: "max_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_MAX_I64",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Maximum of two i64 values.",
        ts_signature: "max_i64(a: number, b: number): number",
        intrinsic: Some(Intrinsic::MaxI64),
    },
    NamespaceMember {
        name: "clamp_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_CLAMP_F64",
        args: &[AbiType::F64, AbiType::F64, AbiType::F64],
        returns: AbiType::F64,
        doc: "Clamps x into [lo, hi]. NaN propagates.",
        ts_signature: "clamp_f64(x: number, lo: number, hi: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "clamp_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_CLAMP_I64",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Clamps x into [lo, hi].",
        ts_signature: "clamp_i64(x: number, lo: number, hi: number): number",
        intrinsic: None,
    },
    // ── Random ────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "random_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_RANDOM_F64",
        args: &[],
        returns: AbiType::F64,
        doc: "Uniform f64 in [0, 1) from a thread-local xorshift64 PRNG.",
        ts_signature: "random_f64(): number",
        intrinsic: Some(Intrinsic::RandomF64),
    },
    NamespaceMember {
        name: "random_i64_range",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_RANDOM_I64_RANGE",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Uniform i64 in [lo, hi). Returns lo when lo >= hi.",
        ts_signature: "random_i64_range(lo: number, hi: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "seed",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_MATH_SEED",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Seeds the PRNG. Zero is replaced by the default seed.",
        ts_signature: "seed(s: number): void",
        intrinsic: None,
    },
    // ── Constants ─────────────────────────────────────────────────────────
    // Backed by zero-arg extern "C" fns in consts.rs; codegen resolves
    // bare `math.PI` (MemberExpr) into a direct call.
    NamespaceMember {
        name: "PI",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MATH_PI",
        args: &[],
        returns: AbiType::F64,
        doc: "Archimedes' constant.",
        ts_signature: "readonly PI: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "E",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MATH_E",
        args: &[],
        returns: AbiType::F64,
        doc: "Euler's number.",
        ts_signature: "readonly E: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "INFINITY",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MATH_INFINITY",
        args: &[],
        returns: AbiType::F64,
        doc: "Positive infinity.",
        ts_signature: "readonly INFINITY: number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "NAN",
        kind: MemberKind::Constant,
        symbol: "__RTS_FN_NS_MATH_NAN",
        args: &[],
        returns: AbiType::F64,
        doc: "Quiet NaN.",
        ts_signature: "readonly NAN: number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "math",
    doc: "Floating-point / integer intrinsics and a seeded xorshift PRNG.",
    members: MEMBERS,
};
