const a = [10, 20, 30, 40, 50];
console.log(a.at(1.9));
console.log(a.at(-1));
console.log(a.at(-2.7));
console.log(a.at(-6));
console.log(a.at(5));
console.log(a.at(NaN));
console.log(a.at(-0));
console.log(a.at("2" as any));
console.log(a.at(true as any));
