//! Array — ABI registration: GlobalClassSpec (JS Array class).
//!
//! Static methods: from(), isArray().
//! Instance methods: length (getter), push(), pop(), shift(), unshift(),
//! indexOf(), includes(), join(), reverse(), slice(), concat(), flat(),
//! sort(), find(), findIndex(), every(), some(), map(), filter(), reduce(), forEach().

use crate::abi::{AbiType, MemberKind, NamespaceMember};
use crate::abi::global_class::GlobalClassSpec;

pub const ARRAY_CLASS_MEMBERS: &[NamespaceMember] = &[
    // ── Constructors ─────────────────────────────────────────────────────
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_ARRAY_NEW_EMPTY",
        args: &[],
        returns: AbiType::Handle,
        doc: "Array() — creates an empty array.",
        ts_signature: "new(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_ARRAY_NEW_FROM_HANDLE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Array(handle) — creates array from iterable handle.",
        ts_signature: "new(elements: number): number",
        intrinsic: None,
        pure: false,
    },
    // ── Static methods ───────────────────────────────────────────────────
    NamespaceMember {
        name: "from",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_ARRAY_FROM",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Array.from(iterable) — creates a new array from an iterable.",
        ts_signature: "from(iterable: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "isArray",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_ARRAY_IS_ARRAY",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "Array.isArray(value) — returns true if value is an array.",
        ts_signature: "isArray(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    // ── Instance getters ─────────────────────────────────────────────────
    NamespaceMember {
        name: "length",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_LEN",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Returns the length of the array.",
        ts_signature: "length: number",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods - mutation ──────────────────────────────────────
    NamespaceMember {
        name: "push",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_PUSH",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Appends element to the end of the array.",
        ts_signature: "push(value: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "pop",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_POP",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Removes and returns the last element.",
        ts_signature: "pop(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "shift",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_SHIFT",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Removes and returns the first element.",
        ts_signature: "shift(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "unshift",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_UNSHIFT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Inserts element at the beginning.",
        ts_signature: "unshift(value: number): void",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods - search ────────────────────────────────────────
    NamespaceMember {
        name: "indexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_INDEX_OF",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Returns index of element or -1 if not found.",
        ts_signature: "indexOf(value: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "includes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_INCLUDES",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Bool,
        doc: "Returns true if array includes the value.",
        ts_signature: "includes(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods - transformation ────────────────────────────────
    NamespaceMember {
        name: "join",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_JOIN",
        args: &[AbiType::U64, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Joins elements with separator string.",
        ts_signature: "join(sep: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "reverse",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_REVERSE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Reverses the array in place.",
        ts_signature: "reverse(): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "slice",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_SLICE",
        args: &[AbiType::U64, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Returns a shallow copy from start to end.",
        ts_signature: "slice(start: number, end: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "concat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_CONCAT",
        args: &[AbiType::U64, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Concatenates another array.",
        ts_signature: "concat(other: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "flat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_FLAT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Flattens nested arrays up to depth.",
        ts_signature: "flat(depth: number): number",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods - sorting ───────────────────────────────────────
    NamespaceMember {
        name: "sort",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_SORT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sorts array. comparator is fn-ptr or 0 for natural sort.",
        ts_signature: "sort(comparator: number): void",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods - iteration with callbacks ──────────────────────
    NamespaceMember {
        name: "find",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_FIND",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Returns first element matching predicate fn-ptr.",
        ts_signature: "find(predicate: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "findIndex",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_FIND_INDEX",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Returns index of first element matching predicate fn-ptr.",
        ts_signature: "findIndex(predicate: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "every",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_EVERY",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Bool,
        doc: "Returns true if all elements match predicate fn-ptr.",
        ts_signature: "every(predicate: number): boolean",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "some",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_ARRAY_SOME",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Bool,
        doc: "Returns true if any element matches predicate fn-ptr.",
        ts_signature: "some(predicate: number): boolean",
        intrinsic: None,
        pure: false,
    },
    // ── Instance methods - delegation to parallel.* ──────────────────────
    NamespaceMember {
        name: "map",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_PARALLEL_MAP",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Maps over array using parallel runtime.",
        ts_signature: "map(fn: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "filter",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_PARALLEL_FILTER",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Filters array using parallel runtime.",
        ts_signature: "filter(fn: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "reduce",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_PARALLEL_REDUCE",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Reduces array using parallel runtime.",
        ts_signature: "reduce(fn: number, initial: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "forEach",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_PARALLEL_FOR_EACH",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Void,
        doc: "Iterates array using parallel runtime.",
        ts_signature: "forEach(fn: number): void",
        intrinsic: None,
        pure: false,
    },
];

pub const ARRAY_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Array",
    doc: "JS Array class — Array.from(), arr.push(), arr.map(), etc.",
    members: ARRAY_CLASS_MEMBERS,
};
