//! Array — ABI registration as GlobalClassSpec.
//!
//! Cobre métodos estáticos como `Array.isArray`, `Array.from`,
//! e métodos de instância como `push`, `pop`, `map`, `filter`, etc.

use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

/// Membros estáticos do Array (métodos de classe).
pub const STATIC_MEMBERS: &[NamespaceMember] = &[
    // Array.isArray(arr) — verifica se é array
    NamespaceMember {
        name: "isArray",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_ARRAY_IS_ARRAY",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "Array.isArray(arr) — retorna true se arr é um Array.",
        ts_signature: "isArray(value: any): value is any[]",
        intrinsic: None,
        pure: true,
    },
    // Array.from(iterable) — cria array a partir de iterável
    NamespaceMember {
        name: "from",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FROM",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Array.from(iterable) — cria novo Array a partir de objeto iterável ou array-like.",
        ts_signature: "from<T>(arrayLike: ArrayLike<T>): T[]",
        intrinsic: None,
        pure: false,
    },
];

/// Métodos de instância do Array.
pub const INSTANCE_MEMBERS: &[NamespaceMember] = &[
    // push(element) — adiciona elemento ao final
    NamespaceMember {
        name: "push",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_PUSH",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.push(element) — adiciona elemento ao final e retorna novo length.",
        ts_signature: "push(...items: any[]): number",
        intrinsic: None,
        pure: false,
    },
    // pop() — remove e retorna último elemento
    NamespaceMember {
        name: "pop",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_POP",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.pop() — remove e retorna o último elemento.",
        ts_signature: "pop(): any",
        intrinsic: None,
        pure: false,
    },
    // at(index) — acessa elemento por índice (suporta negativos)
    NamespaceMember {
        name: "at",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_AT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.at(index) — retorna elemento no índice (suporta negativos).",
        ts_signature: "at(index: number): any",
        intrinsic: None,
        pure: true,
    },
    // join(separator) — concatena elementos em string
    NamespaceMember {
        name: "join",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_JOIN",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.join(separator) — concatena elementos em uma string.",
        ts_signature: "join(separator?: string): string",
        intrinsic: None,
        pure: true,
    },
    // clear() — limpa o array
    NamespaceMember {
        name: "clear",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_CLEAR",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "arr.clear() — remove todos os elementos.",
        ts_signature: "clear(): void",
        intrinsic: None,
        pure: false,
    },
    // indexOf(element) — encontra índice do elemento
    NamespaceMember {
        name: "indexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_INDEX_OF",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.indexOf(element) — retorna primeiro índice do elemento ou -1.",
        ts_signature: "indexOf(searchElement: any, fromIndex?: number): number",
        intrinsic: None,
        pure: true,
    },
    // lastIndexOf(element) — encontra último índice
    NamespaceMember {
        name: "lastIndexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_LAST_INDEX_OF",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.lastIndexOf(element) — retorna último índice do elemento ou -1.",
        ts_signature: "lastIndexOf(searchElement: any, fromIndex?: number): number",
        intrinsic: None,
        pure: true,
    },
    // includes(element) — verifica se contém elemento
    NamespaceMember {
        name: "includes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_INCLUDES",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Bool,
        doc: "arr.includes(element) — retorna true se array contém elemento.",
        ts_signature: "includes(searchElement: any, fromIndex?: number): boolean",
        intrinsic: None,
        pure: true,
    },
    // reverse() — inverte o array
    NamespaceMember {
        name: "reverse",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_REVERSE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.reverse() — inverte a ordem dos elementos.",
        ts_signature: "reverse(): any[]",
        intrinsic: None,
        pure: false,
    },
    // flat() — achatamento superficial
    NamespaceMember {
        name: "flat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FLAT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.flat() — retorna novo array com elementos aninhados achatados (depth=1).",
        ts_signature: "flat(depth?: number): any[]",
        intrinsic: None,
        pure: true,
    },
    // shift() — remove primeiro elemento
    NamespaceMember {
        name: "shift",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SHIFT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.shift() — remove e retorna o primeiro elemento.",
        ts_signature: "shift(): any",
        intrinsic: None,
        pure: false,
    },
    // unshift(element) — adiciona elemento no início
    NamespaceMember {
        name: "unshift",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_UNSHIFT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.unshift(element) — adiciona elemento no início e retorna novo length.",
        ts_signature: "unshift(...items: any[]): number",
        intrinsic: None,
        pure: false,
    },
    // slice(start, end) — fatia do array
    NamespaceMember {
        name: "slice",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SLICE",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.slice(start, end) — retorna cópia superficial de parte do array.",
        ts_signature: "slice(start?: number, end?: number): any[]",
        intrinsic: None,
        pure: true,
    },
    // concat(other) — concatena arrays
    NamespaceMember {
        name: "concat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_CONCAT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.concat(other) — retorna novo array concatenando com other.",
        ts_signature: "concat(...items: ConcatArray<any>[]): any[]",
        intrinsic: None,
        pure: true,
    },
    // fill(value, start, end) — preenche array com valor
    NamespaceMember {
        name: "fill",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FILL",
        args: &[AbiType::Handle, AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.fill(value, start, end) — preenche array com valor estático.",
        ts_signature: "fill(value: any, start?: number, end?: number): any[]",
        intrinsic: None,
        pure: false,
    },
    // splice(start, deleteCount) — remove/insere elementos
    NamespaceMember {
        name: "splice",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SPLICE_REMOVE",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.splice(start, deleteCount) — remove elementos e retorna array removido.",
        ts_signature: "splice(start: number, deleteCount?: number): any[]",
        intrinsic: None,
        pure: false,
    },
    // Getters de instância
    NamespaceMember {
        name: "length",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_LEN",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.length — número de elementos no array.",
        ts_signature: "readonly length: number",
        intrinsic: None,
        pure: true,
    },
];

// Combina todos os membros para o GlobalClassSpec
const ALL_MEMBERS: &[NamespaceMember] = {
    // Em tempo de compilação, precisamos concatenar manualmente
    // Usamos um truque com const fn ou simplesmente listamos tudo junto
    // Para simplificar, vamos apenas referenciar as duas listas no spec
    &[]
};

pub const ARRAY_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Array",
    doc: "Array — JS primitive class. Métodos estáticos e de instância para manipulação de arrays.",
    members: &[], // Será preenchido dinamicamente ou via macro
};

// Alternativa: lista combinada explícita
pub const COMBINED_MEMBERS: &[NamespaceMember] = &[
    // Static
    NamespaceMember {
        name: "isArray",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_ARRAY_IS_ARRAY",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "Array.isArray(arr) — retorna true se arr é um Array.",
        ts_signature: "isArray(value: any): value is any[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "from",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FROM",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Array.from(iterable) — cria novo Array a partir de objeto iterável ou array-like.",
        ts_signature: "from<T>(arrayLike: ArrayLike<T>): T[]",
        intrinsic: None,
        pure: false,
    },
    // Instance methods (repetidos para clareza)
    NamespaceMember {
        name: "push",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_PUSH",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.push(element) — adiciona elemento ao final e retorna novo length.",
        ts_signature: "push(...items: any[]): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "pop",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_POP",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.pop() — remove e retorna o último elemento.",
        ts_signature: "pop(): any",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "at",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_AT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.at(index) — retorna elemento no índice (suporta negativos).",
        ts_signature: "at(index: number): any",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "join",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_JOIN",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.join(separator) — concatena elementos em uma string.",
        ts_signature: "join(separator?: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "clear",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_CLEAR",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "arr.clear() — remove todos os elementos.",
        ts_signature: "clear(): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "indexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_INDEX_OF",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.indexOf(element) — retorna primeiro índice do elemento ou -1.",
        ts_signature: "indexOf(searchElement: any, fromIndex?: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "lastIndexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_LAST_INDEX_OF",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.lastIndexOf(element) — retorna último índice do elemento ou -1.",
        ts_signature: "lastIndexOf(searchElement: any, fromIndex?: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "includes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_INCLUDES",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Bool,
        doc: "arr.includes(element) — retorna true se array contém elemento.",
        ts_signature: "includes(searchElement: any, fromIndex?: number): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "reverse",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_REVERSE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.reverse() — inverte a ordem dos elementos.",
        ts_signature: "reverse(): any[]",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "flat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FLAT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.flat() — retorna novo array com elementos aninhados achatados (depth=1).",
        ts_signature: "flat(depth?: number): any[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "shift",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SHIFT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.shift() — remove e retorna o primeiro elemento.",
        ts_signature: "shift(): any",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "unshift",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_UNSHIFT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.unshift(element) — adiciona elemento no início e retorna novo length.",
        ts_signature: "unshift(...items: any[]): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "slice",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SLICE",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.slice(start, end) — retorna cópia superficial de parte do array.",
        ts_signature: "slice(start?: number, end?: number): any[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "concat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_CONCAT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "arr.concat(other) — retorna novo array concatenando com other.",
        ts_signature: "concat(...items: ConcatArray<any>[]): any[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fill",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FILL",
        args: &[AbiType::Handle, AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.fill(value, start, end) — preenche array com valor estático.",
        ts_signature: "fill(value: any, start?: number, end?: number): any[]",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "splice",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SPLICE_REMOVE",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "arr.splice(start, deleteCount) — remove elementos e retorna array removido.",
        ts_signature: "splice(start: number, deleteCount?: number): any[]",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "length",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_LEN",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "arr.length — número de elementos no array.",
        ts_signature: "readonly length: number",
        intrinsic: None,
        pure: true,
    },
];

pub const ARRAY_CLASS_SPEC_FINAL: GlobalClassSpec = GlobalClassSpec {
    name: "Array",
    doc: "Array — JS primitive class. Métodos estáticos e de instância para manipulação de arrays.",
    members: COMBINED_MEMBERS,
};
