//! `buffer` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "alloc",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_ALLOC",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Allocates a zero-initialised byte buffer of `size` bytes.",
        ts_signature: "alloc(size: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "alloc_zeroed",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_ALLOC_ZEROED",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "Alias for alloc — Rust Vec::new already zeroes.",
        ts_signature: "alloc_zeroed(size: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_FREE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Releases the buffer handle. Subsequent reads/writes are no-ops.",
        ts_signature: "free(handle: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_LEN",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Buffer length in bytes, or -1 if the handle is invalid.",
        ts_signature: "len(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "ptr",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_PTR",
        args: &[AbiType::U64],
        returns: AbiType::U64,
        doc: "Raw pointer to the buffer start, or 0 when invalid. Unsafe — callers must not outlive the handle.",
        ts_signature: "ptr(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_u8",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_READ_U8",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I32,
        doc: "Reads the byte at `offset`. Returns 0 out of bounds.",
        ts_signature: "read_u8(handle: number, offset: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_i32",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_READ_I32",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I32,
        doc: "Reads a little-endian i32 at `offset`.",
        ts_signature: "read_i32(handle: number, offset: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_READ_I64",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Reads a little-endian i64 at `offset`.",
        ts_signature: "read_i64(handle: number, offset: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "read_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_READ_F64",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::F64,
        doc: "Reads a little-endian f64 at `offset`. NaN out of bounds.",
        ts_signature: "read_f64(handle: number, offset: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_u8",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_WRITE_U8",
        args: &[AbiType::U64, AbiType::I64, AbiType::I32],
        returns: AbiType::Void,
        doc: "Writes `val` as u8 at `offset`. No-op out of bounds.",
        ts_signature: "write_u8(handle: number, offset: number, val: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_i32",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_WRITE_I32",
        args: &[AbiType::U64, AbiType::I64, AbiType::I32],
        returns: AbiType::Void,
        doc: "Writes a little-endian i32 at `offset`.",
        ts_signature: "write_i32(handle: number, offset: number, val: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_i64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_WRITE_I64",
        args: &[AbiType::U64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Writes a little-endian i64 at `offset`.",
        ts_signature: "write_i64(handle: number, offset: number, val: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "write_f64",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_WRITE_F64",
        args: &[AbiType::U64, AbiType::I64, AbiType::F64],
        returns: AbiType::Void,
        doc: "Writes a little-endian f64 at `offset`.",
        ts_signature: "write_f64(handle: number, offset: number, val: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "copy",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_COPY",
        args: &[
            AbiType::U64,
            AbiType::I64,
            AbiType::U64,
            AbiType::I64,
            AbiType::I64,
        ],
        returns: AbiType::Void,
        doc: "Copies `len` bytes from src+srcOff to dst+dstOff. Safe with overlapping src/dst.",
        ts_signature: "copy(dst: number, dstOff: number, src: number, srcOff: number, len: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "fill",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_FILL",
        args: &[AbiType::U64, AbiType::I32, AbiType::I64],
        returns: AbiType::Void,
        doc: "Fills the first `len` bytes with `byte`.",
        ts_signature: "fill(handle: number, byte: number, len: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "to_string",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_BUFFER_TO_STRING",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Interprets buffer contents as UTF-8 and returns a string handle.",
        ts_signature: "to_string(handle: number): string",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "buffer",
    doc: "Binary buffers backed by Vec<u8> in the handle table.",
    members: MEMBERS,
};
