//! Number — ABI registration: GlobalClassSpec (JS Number class).
//!
//! Constantes: MAX_SAFE_INTEGER, MIN_SAFE_INTEGER, MAX_VALUE, MIN_VALUE,
//!             EPSILON, POSITIVE_INFINITY, NEGATIVE_INFINITY, NaN.
//! Metodos estaticos: isNaN, isFinite, isInteger, isSafeInteger,
//!                    parseInt, parseFloat.
//! Metodos de instancia: toFixed, toString, valueOf.

use crate::abi::{AbiType, MemberKind, NamespaceMember};
use crate::abi::global_class::GlobalClassSpec;

pub const NUMBER_CLASS_MEMBERS: &[NamespaceMember] = &[
    // ── Constructors ─────────────────────────────────────────────────────
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_NUMBER_NEW_FROM",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "Number(value) — coerce value to number.",
        ts_signature: "new(value: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_NUMBER_NEW_EMPTY",
        args: &[],
        returns: AbiType::F64,
        doc: "Number() — returns 0.",
        ts_signature: "new(): number",
        intrinsic: None,
        pure: true,
    },
    // ── Internal helpers ──────────────────────────────────────────────────
    NamespaceMember {
        name: "fromStr",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_NUMBER_FROM_STR",
        args: &[AbiType::Handle],
        returns: AbiType::F64,
        doc: "Internal: parse string handle to f64 (used by Number() coercion).",
        ts_signature: "fromStr(s: string): number",
        intrinsic: None,
        pure: true,
    },
    // ── Constants ─────────────────────────────────────────────────────────
    NamespaceMember {
        name: "MAX_SAFE_INTEGER",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_MAX_SAFE_INTEGER",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.MAX_SAFE_INTEGER — 2^53 - 1.",
        ts_signature: "MAX_SAFE_INTEGER: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "MIN_SAFE_INTEGER",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_MIN_SAFE_INTEGER",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.MIN_SAFE_INTEGER — -(2^53 - 1).",
        ts_signature: "MIN_SAFE_INTEGER: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "MAX_VALUE",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_MAX_VALUE",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.MAX_VALUE — largest finite f64.",
        ts_signature: "MAX_VALUE: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "MIN_VALUE",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_MIN_VALUE",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.MIN_VALUE — smallest positive f64.",
        ts_signature: "MIN_VALUE: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "EPSILON",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_EPSILON",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.EPSILON — 2^-52.",
        ts_signature: "EPSILON: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "POSITIVE_INFINITY",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_POS_INF",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.POSITIVE_INFINITY.",
        ts_signature: "POSITIVE_INFINITY: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "NEGATIVE_INFINITY",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_NEG_INF",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.NEGATIVE_INFINITY.",
        ts_signature: "NEGATIVE_INFINITY: number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "NaN",
        kind: MemberKind::Constant,
        symbol: "__RTS_DATA_GL_NUMBER_NAN",
        args: &[],
        returns: AbiType::F64,
        doc: "Number.NaN.",
        ts_signature: "NaN: number",
        intrinsic: None,
        pure: true,
    },
    // ── Static methods ────────────────────────────────────────────────────
    NamespaceMember {
        name: "isNaN",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_NUMBER_IS_NAN",
        args: &[AbiType::F64],
        returns: AbiType::Bool,
        doc: "Number.isNaN(value) — true only for actual NaN, unlike global isNaN.",
        ts_signature: "isNaN(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "isFinite",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_NUMBER_IS_FINITE",
        args: &[AbiType::F64],
        returns: AbiType::Bool,
        doc: "Number.isFinite(value) — true when finite (not NaN, not Infinity).",
        ts_signature: "isFinite(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "isInteger",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_NUMBER_IS_INTEGER",
        args: &[AbiType::F64],
        returns: AbiType::Bool,
        doc: "Number.isInteger(value) — true when finite and integer.",
        ts_signature: "isInteger(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "isSafeInteger",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_NUMBER_IS_SAFE_INT",
        args: &[AbiType::F64],
        returns: AbiType::Bool,
        doc: "Number.isSafeInteger(value) — true when |value| <= 2^53-1.",
        ts_signature: "isSafeInteger(value: number): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "parseInt",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_NS_FMT_PARSE_I64",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Number.parseInt(s) — delegate to fmt.parse_i64.",
        ts_signature: "parseInt(s: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "parseFloat",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_NS_FMT_PARSE_F64",
        args: &[AbiType::StrPtr],
        returns: AbiType::F64,
        doc: "Number.parseFloat(s) — delegate to fmt.parse_f64.",
        ts_signature: "parseFloat(s: string): number",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods ──────────────────────────────────────────────────
    NamespaceMember {
        name: "toFixed",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_NUMBER_TO_FIXED",
        args: &[AbiType::F64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "n.toFixed(digits) — fixed-point string with `digits` decimal places.",
        ts_signature: "toFixed(digits?: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_NS_GC_STRING_FROM_F64",
        args: &[AbiType::F64],
        returns: AbiType::Handle,
        doc: "n.toString() — decimal string representation.",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "valueOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_NUMBER_VALUE_OF",
        args: &[AbiType::F64],
        returns: AbiType::F64,
        doc: "n.valueOf() — identity, returns the number.",
        ts_signature: "valueOf(): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toPrecision",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_NUMBER_TO_PRECISION",
        args: &[AbiType::F64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "n.toPrecision(digits) — significant digits string.",
        ts_signature: "toPrecision(digits?: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toExponential",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_NUMBER_TO_EXPONENTIAL",
        args: &[AbiType::F64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "n.toExponential(digits) — exponential notation string.",
        ts_signature: "toExponential(digits?: number): string",
        intrinsic: None,
        pure: true,
    },
];

pub const NUMBER_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Number",
    doc: "JS Number primitive class — Number.isNaN(), Number.MAX_SAFE_INTEGER, n.toFixed() etc.",
    members: NUMBER_CLASS_MEMBERS,
};

/// Returns the f64 value for a `Number.*` constant property by name.
/// Used by codegen to emit `f64const` inline without hardcoding in members.rs.
pub fn number_const_value(name: &str) -> Option<f64> {
    match name {
        "MAX_SAFE_INTEGER" => Some(9_007_199_254_740_991.0_f64),
        "MIN_SAFE_INTEGER" => Some(-9_007_199_254_740_991.0_f64),
        "MAX_VALUE" => Some(f64::MAX),
        "MIN_VALUE" => Some(f64::MIN_POSITIVE),
        "EPSILON" => Some(f64::EPSILON),
        "POSITIVE_INFINITY" => Some(f64::INFINITY),
        "NEGATIVE_INFINITY" => Some(f64::NEG_INFINITY),
        "NaN" => Some(f64::NAN),
        _ => None,
    }
}
