const m=require(require('path').resolve(process.argv[3] ?? 'avancos.json'));
const fmt=(a)=>{const l=[];for(let i=0;i<a.length;i+=20)l.push('    '+a.slice(i,i+20).join(', ')+',');return l.join('\n');};
let s=`//! GENERATED by \`bun scripts/fonte_avancos_medir_edge.mjs\` + \`scripts/fonte_avancos_gera.cjs\`
//! — do not edit by hand; re-measure and regenerate.
//!
//! The \`hmtx\` ADVANCE of each character, in font units of a 2048 em, for the
//! four fonts Blink resolves the generic families to on Windows, regular and
//! bold — measured in ${m.ua.match(/Edg\/[0-9.]+/)?.[0] ?? 'Edge'} by \`canvas.measureText\` at 2048px, where
//! a character's width IS its advance. \`fonte_metricas.rs\` owns the lookup
//! and says what the tables do not cover (kerning, italics, other scripts).

/// The code points the tables cover, ascending — the index into every table.
pub(super) const CHARS: [u32; ${m.chars.length}] = [
${fmt(m.chars)}
];
`;
for (const [nome,rust] of [['serif','TIMES'],['sans','ARIAL'],['mono','CONSOLAS'],['sistema','SEGOE_UI']]) {
  s+=`\n/// \`[regular, bold]\`.\npub(super) const ${rust}: [[u16; ${m.chars.length}]; 2] = [\n    [\n${fmt(m.fontes[nome+'-normal']).replace(/^/gm,'    ')}\n    ],\n    [\n${fmt(m.fontes[nome+'-bold']).replace(/^/gm,'    ')}\n    ],\n];\n`;
}
require('fs').writeFileSync(process.argv[2], s);
