#!/usr/bin/env python3
"""Generate `crates/rts-dom/src/dom/entities.rs` from the WHATWG named
character reference table (https://html.spec.whatwg.org/entities.json).

Run manually when the spec's table changes (it hasn't, in practice, since
HTML5 shipped it). No build-time network access: the generated file is
checked in and read like any other source file.

Usage:
    python scripts/gen_html_entities.py path/to/entities.json > \
        crates/rts-dom/src/dom/entities.rs

The JSON maps a reference INCLUDING its leading `&` (and, for most, a
trailing `;`) to `{"codepoints": [...], "characters": "..."}`. A reference
without a trailing `;` is one of the ~106 legacy names the spec grandfathers
in for compatibility with pre-HTML5 pages (`&amp`, `&lt`, `&copy`, ...) --
every other name is invalid without the semicolon and must NOT be decoded
bare, so the two forms need separate tables.
"""
import io
import json
import sys

# Windows consoles default to a legacy codepage; every entity name is ASCII
# but many decoded characters are not, so stdout must be forced to UTF-8
# regardless of the terminal's own codepage.
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')


def rust_escape(s: str) -> str:
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif cp < 0x20 or cp == 0x7f:
            # Control characters (NewLine/Tab/... map to these): a raw byte
            # in the generated source would be invisible/fragile across
            # editors and line-ending conversions, so escape explicitly.
            out.append(f'\\u{{{cp:x}}}')
        else:
            out.append(ch)
    return ''.join(out)


def main() -> None:
    path = sys.argv[1] if len(sys.argv) > 1 else 'entities.json'
    with open(path, encoding='utf-8') as f:
        data = json.load(f)

    with_semi = {}
    legacy_no_semi = {}
    for key, val in data.items():
        assert key.startswith('&')
        chars = val['characters']
        name = key[1:]
        if name.endswith(';'):
            with_semi[name[:-1]] = chars
        else:
            legacy_no_semi[name] = chars

    print('//! GENERATED by `scripts/gen_html_entities.py` from')
    print('//! <https://html.spec.whatwg.org/entities.json> -- do not hand-edit.')
    print(f'//! {len(with_semi)} names require the trailing `;`; {len(legacy_no_semi)}')
    print('//! legacy names (HTML §13.5, pre-HTML5 compatibility) are recognised')
    print('//! without one too. Regenerate with the script above if the spec table')
    print('//! ever changes.')
    print()
    print('/// Named character references that REQUIRE the trailing `;` (HTML')
    print('/// §13.2.5.72). `body` is the name with neither `&` nor `;`.')
    print('pub(crate) fn decode_named_with_semicolon(body: &str) -> Option<&\'static str> {')
    print('    Some(match body {')
    for name in sorted(with_semi):
        print(f'        "{rust_escape(name)}" => "{rust_escape(with_semi[name])}",')
    print('        _ => return None,')
    print('    })')
    print('}')
    print()
    print('/// The ~106 legacy names the spec still recognises WITHOUT a trailing')
    print('/// `;` (`&amp`, `&lt`, `&copy`, ...) for compatibility with pages')
    print('/// written before HTML5 defined the full table. Every other name is')
    print('/// only valid with the semicolon.')
    print('pub(crate) fn decode_named_legacy_no_semicolon(body: &str) -> Option<&\'static str> {')
    print('    Some(match body {')
    for name in sorted(legacy_no_semi):
        print(f'        "{rust_escape(name)}" => "{rust_escape(legacy_no_semi[name])}",')
    print('        _ => return None,')
    print('    })')
    print('}')


if __name__ == '__main__':
    main()
