use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

// ── Response ──────────────────────────────────────────────────────────────────

pub const RESPONSE_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "status",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_STATUS",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "response.status — HTTP status code (number).",
        ts_signature: "readonly status: number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "ok",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_OK",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "response.ok — true se status 200-299.",
        ts_signature: "readonly ok: boolean",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "statusText",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_STATUS_TEXT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.statusText — 'OK', 'Not Found', etc.",
        ts_signature: "readonly statusText: string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "url",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_URL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.url — URL final (após redirects).",
        ts_signature: "readonly url: string",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "text",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_TEXT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.text() → string (RTS sync, sem Promise).",
        ts_signature: "text(): Promise<string>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "json",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_JSON",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.json() → JSON handle (RTS sync, sem Promise).",
        ts_signature: "json(): Promise<any>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "blob",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_ARRAY_BUFFER",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.blob() → Buffer handle (RTS sync).",
        ts_signature: "blob(): Promise<Blob>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "arrayBuffer",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_ARRAY_BUFFER",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "response.arrayBuffer() → Buffer handle (RTS sync).",
        ts_signature: "arrayBuffer(): Promise<ArrayBuffer>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "then",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_FETCH_RESPONSE_THEN",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "response.then(fn) → fn(response). Compatibilidade com Promise.then().",
        ts_signature: "then<T>(fn: (response: Response) => T): T",
        intrinsic: None,
        pure: false,
    },
];

pub const RESPONSE_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Response",
    doc: "Fetch API Response — status/ok/statusText/url/text()/json()/blob()/arrayBuffer().",
    members: RESPONSE_MEMBERS,
};

// ── Promise ───────────────────────────────────────────────────────────────────

pub const PROMISE_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "then",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_PROMISE_THEN",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.then(fn) — executa fn(value) imediatamente, retorna Promise<result>.",
        ts_signature: "then<T>(onFulfilled: (value: any) => T): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "catch",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_PROMISE_CATCH",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.catch(fn) — passthrough (RTS é síncrono).",
        ts_signature: "catch(onRejected: (err: any) => any): Promise<any>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "finally",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_PROMISE_FINALLY",
        args: &[AbiType::Handle, AbiType::U64],
        returns: AbiType::Handle,
        doc: "promise.finally(fn) — chama fn() e retorna promise original.",
        ts_signature: "finally(onFinally: () => void): Promise<any>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "resolve",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_PROMISE_RESOLVE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "Promise.resolve(v) — cria Promise já resolvida.",
        ts_signature: "static resolve<T>(value: T): Promise<T>",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "reject",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_PROMISE_RESOLVE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Promise.reject(v) — em RTS é alias de resolve (síncrono).",
        ts_signature: "static reject<T>(reason?: any): Promise<T>",
        intrinsic: None,
        pure: false,
    },
];

pub const PROMISE_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Promise",
    doc: "Promise síncrona — then/catch/finally executam imediatamente. await = resolve().",
    members: PROMISE_MEMBERS,
};
