use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "suite_begin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_SUITE_BEGIN",
        args: &[AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Opens a named test suite block. Nested calls increase indent.",
        ts_signature: "suite_begin(name: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "suite_end",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_SUITE_END",
        args: &[],
        returns: AbiType::Void,
        doc: "Closes the innermost test suite block.",
        ts_signature: "suite_end(): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "case_begin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_CASE_BEGIN",
        args: &[AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Starts a named test case and resets the failure flag.",
        ts_signature: "case_begin(name: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "case_end",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_CASE_END",
        args: &[],
        returns: AbiType::Void,
        doc: "Ends the current case. Prints ✓ if no failures, updates counters.",
        ts_signature: "case_end(): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "case_fail",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_CASE_FAIL",
        args: &[AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Marks current case as failed and emits message in red.",
        ts_signature: "case_fail(msg: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "case_fail_diff",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_CASE_FAIL_DIFF",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Marks current case as failed and prints an expected/received diff.",
        ts_signature: "case_fail_diff(expected: string, actual: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "print_summary",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_TEST_CORE_PRINT_SUMMARY",
        args: &[],
        returns: AbiType::Void,
        doc: "Prints pass/fail counts. Call once at the end of the test file.",
        ts_signature: "print_summary(): void",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "test_core",
    doc: "Low-level test runner primitives. Use rts:test for the high-level API.",
    members: MEMBERS,
};
