use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const DOM_EXCEPTION_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DOM_EXCEPTION_NEW_EMPTY",
        args: &[],
        returns: AbiType::Handle,
        doc: "new DOMException()",
        ts_signature: "new DOMException()",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DOM_EXCEPTION_NEW_MSG",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "new DOMException(message)",
        ts_signature: "new DOMException(message: string)",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_DOM_EXCEPTION_NEW",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "new DOMException(message, name)",
        ts_signature: "new DOMException(message: string, name: string)",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "name",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_GL_DOM_EXCEPTION_NAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "exception.name",
        ts_signature: "readonly name: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "message",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_GL_DOM_EXCEPTION_MESSAGE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "exception.message",
        ts_signature: "readonly message: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "code",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_GL_DOM_EXCEPTION_CODE",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "exception.code — legacy WebIDL numeric code.",
        ts_signature: "readonly code: number",
        intrinsic: None,
        pure: true,
    },
];

pub const DOM_EXCEPTION_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "DOMException",
    doc: "DOMException — WebIDL legacy exception class com name/message/code.",
    members: DOM_EXCEPTION_MEMBERS,
};
