console.log(NaN == NaN);
console.log(NaN === NaN);
console.log(NaN < 1);
console.log(NaN > 1);
console.log(NaN >= NaN);
console.log(Infinity - Infinity);
console.log(Infinity + -Infinity);
console.log(1 / 0);
console.log(-1 / 0);
console.log(0 / 0);
console.log(Infinity > Number.MAX_VALUE);
console.log(0 === -0);
console.log(Object.is(0, -0));
console.log(Object.is(NaN, NaN));
