console.log([] == false);
console.log([] == 0);
console.log([0] == false);
console.log([0] == 0);
console.log([1] == 1);
console.log([1] == true);
console.log(["1"] == 1);
console.log([] == "");
console.log([null] == 0);
console.log([undefined] == 0);
console.log([] == ![]);
console.log([1, 2] == "1,2");
