use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── App ──────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "app_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_APP_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Creates the FLTK application. Call once before any widget.",
        ts_signature: "app_new(): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "app_run",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_APP_RUN",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Enters the FLTK event loop. Blocks until all windows are closed.",
        ts_signature: "app_run(app: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "app_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_APP_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Frees the app handle.",
        ts_signature: "app_free(app: number): void",
        intrinsic: None,
    },
    // ── Window ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "window_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_NEW",
        args: &[AbiType::I64, AbiType::I64, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Creates a window (w, h, title). Returns a window handle.",
        ts_signature: "window_new(w: number, h: number, title: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "window_show",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_SHOW",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Makes the window visible.",
        ts_signature: "window_show(win: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "window_end",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_END",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Ends the window widget group. Call after adding all child widgets.",
        ts_signature: "window_end(win: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "window_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Frees the window handle.",
        ts_signature: "window_free(win: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "window_set_callback",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_SET_CALLBACK",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets a callback invoked when the window close button is pressed.",
        ts_signature: "window_set_callback(win: number, fn: () => void): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "window_set_color",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_SET_COLOR",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets the background color of the window (r, g, b in 0–255).",
        ts_signature: "window_set_color(win: number, r: number, g: number, b: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "window_resize",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WINDOW_RESIZE",
        args: &[
            AbiType::Handle,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
        ],
        returns: AbiType::Void,
        doc: "Moves and resizes the window (x, y, w, h).",
        ts_signature: "window_resize(win: number, x: number, y: number, w: number, h: number): void",
        intrinsic: None,
    },
    // ── Generic widget ops ───────────────────────────────────────────────
    NamespaceMember {
        name: "widget_set_label",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SET_LABEL",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Sets the label text of any widget.",
        ts_signature: "widget_set_label(widget: number, text: string): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_label",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_LABEL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Returns the widget label as a GC string handle.",
        ts_signature: "widget_label(widget: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_set_callback",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SET_CALLBACK",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Void,
        doc: "Registers a callback invoked when the widget is activated (click, change, etc).",
        ts_signature: "widget_set_callback(widget: number, fn: () => void): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_set_callback_with_ud",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SET_CALLBACK_WITH_UD",
        args: &[AbiType::Handle, AbiType::I64, AbiType::U64],
        returns: AbiType::Void,
        doc: "Variante de set_callback que passa userdata (ex: handle de `this`) ao callback.",
        ts_signature: "widget_set_callback_with_ud(widget: number, fn: (this: number) => void, userdata: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_set_color",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SET_COLOR",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets the background color of a widget (r, g, b in 0–255).",
        ts_signature: "widget_set_color(widget: number, r: number, g: number, b: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_set_label_color",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SET_LABEL_COLOR",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets the label text color of a widget (r, g, b in 0–255).",
        ts_signature: "widget_set_label_color(widget: number, r: number, g: number, b: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_resize",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_RESIZE",
        args: &[
            AbiType::Handle,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
        ],
        returns: AbiType::Void,
        doc: "Moves and resizes a widget (x, y, w, h).",
        ts_signature: "widget_resize(widget: number, x: number, y: number, w: number, h: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_redraw",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_REDRAW",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Marks the widget as needing a redraw.",
        ts_signature: "widget_redraw(widget: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_hide",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_HIDE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Hides the widget.",
        ts_signature: "widget_hide(widget: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_show",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SHOW",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Shows the widget.",
        ts_signature: "widget_show(widget: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "widget_set_draw",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_WIDGET_SET_DRAW",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets a custom draw callback. Use draw_* functions inside to paint the widget.",
        ts_signature: "widget_set_draw(widget: number, fn: () => void): void",
        intrinsic: None,
    },
    // ── Button ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "button_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_BUTTON_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a push button at (x, y) with size (w, h) and label.",
        ts_signature: "button_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    // ── Frame ────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "frame_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_FRAME_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a text frame (static label) at (x, y) with size (w, h) and text.",
        ts_signature: "frame_new(x: number, y: number, w: number, h: number, text: string): number",
        intrinsic: None,
    },
    // ── CheckButton ──────────────────────────────────────────────────────
    NamespaceMember {
        name: "check_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_CHECK_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a checkbox widget.",
        ts_signature: "check_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "check_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_CHECK_VALUE",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "Returns true if the checkbox is checked.",
        ts_signature: "check_value(handle: number): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "check_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_CHECK_SET_VALUE",
        args: &[AbiType::Handle, AbiType::Bool],
        returns: AbiType::Void,
        doc: "Sets the checked state of a checkbox.",
        ts_signature: "check_set_value(handle: number, val: boolean): void",
        intrinsic: None,
    },
    // ── RadioButton ──────────────────────────────────────────────────────
    NamespaceMember {
        name: "radio_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_RADIO_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a radio button widget.",
        ts_signature: "radio_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "radio_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_RADIO_VALUE",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "Returns true if the radio button is selected.",
        ts_signature: "radio_value(handle: number): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "radio_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_RADIO_SET_VALUE",
        args: &[AbiType::Handle, AbiType::Bool],
        returns: AbiType::Void,
        doc: "Sets the selected state of a radio button.",
        ts_signature: "radio_set_value(handle: number, val: boolean): void",
        intrinsic: None,
    },
    // ── Input ────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "input_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_INPUT_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a single-line text input field.",
        ts_signature: "input_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "input_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_INPUT_VALUE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Returns the current text of the input field as a GC string handle.",
        ts_signature: "input_value(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "input_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_INPUT_SET_VALUE",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Sets the text content of an input field.",
        ts_signature: "input_set_value(handle: number, text: string): void",
        intrinsic: None,
    },
    // ── Output ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "output_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_OUTPUT_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a read-only output widget.",
        ts_signature: "output_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "output_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_OUTPUT_SET_VALUE",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Sets the text displayed in an output widget.",
        ts_signature: "output_set_value(handle: number, text: string): void",
        intrinsic: None,
    },
    // ── Slider ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "slider_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SLIDER_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a horizontal slider.",
        ts_signature: "slider_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "slider_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SLIDER_VALUE",
        args: &[AbiType::Handle],
        returns: AbiType::F64,
        doc: "Returns the current value of a slider.",
        ts_signature: "slider_value(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "slider_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SLIDER_SET_VALUE",
        args: &[AbiType::Handle, AbiType::F64],
        returns: AbiType::Void,
        doc: "Sets the current value of a slider.",
        ts_signature: "slider_set_value(handle: number, val: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "slider_set_bounds",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SLIDER_SET_BOUNDS",
        args: &[AbiType::Handle, AbiType::F64, AbiType::F64],
        returns: AbiType::Void,
        doc: "Sets the minimum and maximum bounds of a slider.",
        ts_signature: "slider_set_bounds(handle: number, min: number, max: number): void",
        intrinsic: None,
    },
    // ── Progress ─────────────────────────────────────────────────────────
    NamespaceMember {
        name: "progress_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_PROGRESS_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a progress bar widget.",
        ts_signature: "progress_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "progress_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_PROGRESS_VALUE",
        args: &[AbiType::Handle],
        returns: AbiType::F64,
        doc: "Returns the current value of a progress bar.",
        ts_signature: "progress_value(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "progress_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_PROGRESS_SET_VALUE",
        args: &[AbiType::Handle, AbiType::F64],
        returns: AbiType::Void,
        doc: "Sets the current value of a progress bar.",
        ts_signature: "progress_set_value(handle: number, val: number): void",
        intrinsic: None,
    },
    // ── Spinner ──────────────────────────────────────────────────────────
    NamespaceMember {
        name: "spinner_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SPINNER_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a numeric spinner widget.",
        ts_signature: "spinner_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "spinner_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SPINNER_VALUE",
        args: &[AbiType::Handle],
        returns: AbiType::F64,
        doc: "Returns the current numeric value of a spinner.",
        ts_signature: "spinner_value(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "spinner_set_value",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SPINNER_SET_VALUE",
        args: &[AbiType::Handle, AbiType::F64],
        returns: AbiType::Void,
        doc: "Sets the numeric value of a spinner.",
        ts_signature: "spinner_set_value(handle: number, val: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "spinner_set_bounds",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SPINNER_SET_BOUNDS",
        args: &[AbiType::Handle, AbiType::F64, AbiType::F64],
        returns: AbiType::Void,
        doc: "Sets the min/max range of a spinner.",
        ts_signature: "spinner_set_bounds(handle: number, min: number, max: number): void",
        intrinsic: None,
    },
    // ── MenuBar ──────────────────────────────────────────────────────────
    NamespaceMember {
        name: "menubar_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_MENUBAR_NEW",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Creates a menu bar at (x, y) with size (w, h).",
        ts_signature: "menubar_new(x: number, y: number, w: number, h: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "menubar_add",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_MENUBAR_ADD",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Void,
        doc: "Adds a menu item. Path uses '/' for submenus (e.g. 'File/Open'). fn_ptr=0 for separators.",
        ts_signature: "menubar_add(handle: number, path: string, fn: () => void): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "menubar_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_MENUBAR_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Frees a menu bar handle.",
        ts_signature: "menubar_free(handle: number): void",
        intrinsic: None,
    },
    // ── TextBuffer ───────────────────────────────────────────────────────
    NamespaceMember {
        name: "textbuf_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTBUF_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Creates a text buffer.",
        ts_signature: "textbuf_new(): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "textbuf_set_text",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTBUF_SET_TEXT",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Replaces the entire text buffer contents.",
        ts_signature: "textbuf_set_text(handle: number, text: string): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "textbuf_text",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTBUF_TEXT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Returns the text buffer contents as a GC string handle.",
        ts_signature: "textbuf_text(handle: number): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "textbuf_append",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTBUF_APPEND",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Appends text to the end of the buffer.",
        ts_signature: "textbuf_append(handle: number, text: string): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "textbuf_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTBUF_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Frees the text buffer handle.",
        ts_signature: "textbuf_free(handle: number): void",
        intrinsic: None,
    },
    // ── TextDisplay ──────────────────────────────────────────────────────
    NamespaceMember {
        name: "textdisplay_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTDISPLAY_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates a read-only text display widget.",
        ts_signature: "textdisplay_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "textdisplay_set_buffer",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTDISPLAY_SET_BUFFER",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Void,
        doc: "Associates a TextBuffer with the display.",
        ts_signature: "textdisplay_set_buffer(display: number, buf: number): void",
        intrinsic: None,
    },
    // ── TextEditor ───────────────────────────────────────────────────────
    NamespaceMember {
        name: "texteditor_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTEDITOR_NEW",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::StrPtr,
        ],
        returns: AbiType::Handle,
        doc: "Creates an editable text editor widget.",
        ts_signature: "texteditor_new(x: number, y: number, w: number, h: number, label: string): number",
        intrinsic: None,
    },
    NamespaceMember {
        name: "texteditor_set_buffer",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_TEXTEDITOR_SET_BUFFER",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Void,
        doc: "Associates a TextBuffer with the editor.",
        ts_signature: "texteditor_set_buffer(editor: number, buf: number): void",
        intrinsic: None,
    },
    // ── Draw ─────────────────────────────────────────────────────────────
    NamespaceMember {
        name: "draw_rect",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DRAW_RECT",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Draws a rectangle outline at (x, y) with size (w, h).",
        ts_signature: "draw_rect(x: number, y: number, w: number, h: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "draw_rect_fill",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DRAW_RECT_FILL",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Draws a filled rectangle at (x, y) with size (w, h).",
        ts_signature: "draw_rect_fill(x: number, y: number, w: number, h: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "draw_line",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DRAW_LINE",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Draws a line from (x1, y1) to (x2, y2).",
        ts_signature: "draw_line(x1: number, y1: number, x2: number, y2: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "draw_circle",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DRAW_CIRCLE",
        args: &[AbiType::I64, AbiType::I64, AbiType::F64],
        returns: AbiType::Void,
        doc: "Draws a circle centered at (x, y) with radius r.",
        ts_signature: "draw_circle(x: number, y: number, r: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "draw_arc",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DRAW_ARC",
        args: &[
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::I64,
            AbiType::F64,
            AbiType::F64,
        ],
        returns: AbiType::Void,
        doc: "Draws an arc/pie within bounding box (x, y, w, h) from angle a1 to a2 (degrees).",
        ts_signature: "draw_arc(x: number, y: number, w: number, h: number, a1: number, a2: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "draw_text",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DRAW_TEXT",
        args: &[AbiType::StrPtr, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Draws text at (x, y) using the current font and color.",
        ts_signature: "draw_text(text: string, x: number, y: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "set_draw_color",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SET_DRAW_COLOR",
        args: &[AbiType::I64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets the current drawing color (r, g, b in 0–255).",
        ts_signature: "set_draw_color(r: number, g: number, b: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "set_font",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SET_FONT",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets the current font (font_id: 0=Helvetica..14, size in pixels).",
        ts_signature: "set_font(font_id: number, size: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "set_line_style",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_SET_LINE_STYLE",
        args: &[AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Sets line style (style: 0=solid,1=dash,2=dot) and width in pixels.",
        ts_signature: "set_line_style(style: number, width: number): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "measure_width",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_MEASURE_WIDTH",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Returns the pixel width of a string in the current font.",
        ts_signature: "measure_width(text: string): number",
        intrinsic: None,
    },
    // ── Dialog ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "alert",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_ALERT",
        args: &[AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "Shows a blocking alert dialog with a message.",
        ts_signature: "alert(msg: string): void",
        intrinsic: None,
    },
    NamespaceMember {
        name: "dialog_ask",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DIALOG_ASK",
        args: &[AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "Shows a yes/no dialog. Returns true if user clicks Yes.",
        ts_signature: "dialog_ask(msg: string): boolean",
        intrinsic: None,
    },
    NamespaceMember {
        name: "dialog_input",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_UI_DIALOG_INPUT",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Shows an input dialog (label, def). Returns GC string handle, or 0 on cancel.",
        ts_signature: "dialog_input(label: string, def: string): number",
        intrinsic: None,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "ui",
    doc: "FLTK GUI: windows, widgets, menus, text, drawing, and dialogs.",
    members: MEMBERS,
};
