//! String — ABI registration: NamespaceSpec (rts:string) + GlobalClassSpec (JS String class).

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};
use crate::abi::global_class::GlobalClassSpec;

pub const MEMBERS: &[NamespaceMember] = &[
    // ── Search ────────────────────────────────────────────────────────
    NamespaceMember {
        name: "contains",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CONTAINS",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when `haystack` contains `needle`.",
        ts_signature: "contains(haystack: string, needle: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "starts_with",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_STARTS_WITH",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when `s` starts with `prefix`.",
        ts_signature: "starts_with(s: string, prefix: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "ends_with",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_ENDS_WITH",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when `s` ends with `suffix`.",
        ts_signature: "ends_with(s: string, suffix: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "find",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_FIND",
        args: &[AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Byte index of first occurrence of `needle`, or -1 when absent.",
        ts_signature: "find(s: string, needle: string): number",
        intrinsic: None,
        pure: true,
    },
    // ── Transform ─────────────────────────────────────────────────────
    NamespaceMember {
        name: "to_upper",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TO_UPPER",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Uppercase copy (Unicode-aware).",
        ts_signature: "to_upper(s: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "to_lower",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TO_LOWER",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Lowercase copy (Unicode-aware).",
        ts_signature: "to_lower(s: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trim",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TRIM",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Removes ASCII + Unicode whitespace from both ends.",
        ts_signature: "trim(s: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trim_start",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TRIM_START",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Removes whitespace from the start.",
        ts_signature: "trim_start(s: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trim_end",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_TRIM_END",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Removes whitespace from the end.",
        ts_signature: "trim_end(s: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "repeat",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_REPEAT",
        args: &[AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Concatenates `s` with itself `n` times.",
        ts_signature: "repeat(s: string, n: number): string",
        intrinsic: None,
        pure: true,
    },
    // ── Replace ───────────────────────────────────────────────────────
    NamespaceMember {
        name: "replace",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_REPLACE",
        args: &[AbiType::StrPtr, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Replaces every occurrence of `from` with `to`.",
        ts_signature: "replace(s: string, from: string, to: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "replacen",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_REPLACEN",
        args: &[
            AbiType::StrPtr,
            AbiType::StrPtr,
            AbiType::StrPtr,
            AbiType::I64,
        ],
        returns: AbiType::Handle,
        doc: "Replaces the first `n` occurrences of `from` with `to`.",
        ts_signature: "replacen(s: string, from: string, to: string, n: number): string",
        intrinsic: None,
        pure: true,
    },
    // ── Split / count / indexing ──────────────────────────────────────
    NamespaceMember {
        name: "char_count",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CHAR_COUNT",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Unicode codepoint count (chars).",
        ts_signature: "char_count(s: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "byte_len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_BYTE_LEN",
        args: &[AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Length in UTF-8 bytes.",
        ts_signature: "byte_len(s: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "char_at",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CHAR_AT",
        args: &[AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Character at Unicode index `idx` as a single-char string handle, or 0 out of range.",
        ts_signature: "char_at(s: string, idx: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "char_code_at",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_STRING_CHAR_CODE_AT",
        args: &[AbiType::StrPtr, AbiType::I64],
        returns: AbiType::I64,
        doc: "Unicode code point at `idx`, or -1 out of range.",
        ts_signature: "char_code_at(s: string, idx: number): number",
        intrinsic: None,
        pure: true,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "string",
    doc: "Rich string operations beyond the basic gc pool.",
    members: MEMBERS,
};

// ── GlobalClassSpec: JS String class ──────────────────────────────────────────

pub const STRING_CLASS_MEMBERS: &[NamespaceMember] = &[
    // ── Constructor ──────────────────────────────────────────────────────
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_STRING_NEW_BOXED",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "new String(value) — wraps value como StringBox (typeof returns 'object').",
        ts_signature: "new(value: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_STRING_NEW_EMPTY",
        args: &[],
        returns: AbiType::Handle,
        doc: "new String() — empty string.",
        ts_signature: "new(): string",
        intrinsic: None,
        pure: true,
    },
    // ── Static methods ───────────────────────────────────────────────────
    NamespaceMember {
        name: "fromCharCode",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_STRING_FROM_CHAR_CODE",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "String.fromCharCode(code) — char from UTF-16 code unit.",
        ts_signature: "fromCharCode(code: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "fromCodePoint",
        kind: MemberKind::StaticMethod,
        symbol: "__RTS_FN_GL_STRING_FROM_CODE_POINT",
        args: &[AbiType::I64],
        returns: AbiType::Handle,
        doc: "String.fromCodePoint(codePoint) — char from full Unicode code point.",
        ts_signature: "fromCodePoint(codePoint: number): string",
        intrinsic: None,
        pure: true,
    },
    // ── Instance getter ──────────────────────────────────────────────────
    NamespaceMember {
        name: "length",
        kind: MemberKind::InstanceGetter,
        symbol: "__RTS_FN_GL_STRING_LENGTH_UTF16",
        args: &[AbiType::Handle],
        returns: AbiType::I64,
        doc: "str.length — number of UTF-16 code units (JS spec).",
        ts_signature: "length: number",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods — search ────────────────────────────────────────
    NamespaceMember {
        name: "indexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_INDEX_OF",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "str.indexOf(needle) — first occurrence index, or -1.",
        ts_signature: "indexOf(needle: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "lastIndexOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_LAST_INDEX_OF",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "str.lastIndexOf(needle) — last occurrence index, or -1.",
        ts_signature: "lastIndexOf(needle: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "includes",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_INCLUDES",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Bool,
        doc: "str.includes(needle) — true when needle is found.",
        ts_signature: "includes(needle: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "startsWith",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_STARTS_WITH",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Bool,
        doc: "str.startsWith(prefix).",
        ts_signature: "startsWith(prefix: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "endsWith",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_ENDS_WITH",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Bool,
        doc: "str.endsWith(suffix).",
        ts_signature: "endsWith(suffix: string): boolean",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods — indexing ──────────────────────────────────────
    NamespaceMember {
        name: "charAt",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_CHAR_AT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "str.charAt(idx).",
        ts_signature: "charAt(idx: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "charCodeAt",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_CHAR_CODE_AT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "str.charCodeAt(idx) — UTF-16 code unit at index.",
        ts_signature: "charCodeAt(idx: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "codePointAt",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_CODE_POINT_AT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::I64,
        doc: "str.codePointAt(idx) — full Unicode code point at index.",
        ts_signature: "codePointAt(idx: number): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "at",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_AT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "str.at(idx) — char at index (negative counts from end).",
        ts_signature: "at(idx: number): string",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods — slicing ───────────────────────────────────────
    NamespaceMember {
        name: "slice",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_SLICE",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "str.slice(start, end) — negatives from end.",
        ts_signature: "slice(start: number, end?: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "substring",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_SUBSTRING",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "str.substring(start, end) — like slice but clamps negatives to 0.",
        ts_signature: "substring(start: number, end?: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "substr",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_SUBSTR",
        args: &[AbiType::Handle, AbiType::I64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "str.substr(start, length) — deprecated start+count form.",
        ts_signature: "substr(start: number, length?: number): string",
        intrinsic: None,
        pure: true,
    },
    // ── Instance methods — transform ─────────────────────────────────────
    NamespaceMember {
        name: "toUpperCase",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_UPPER_CASE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.toUpperCase().",
        ts_signature: "toUpperCase(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLocaleUpperCase",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_UPPER_CASE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.toLocaleUpperCase() — alias for toUpperCase.",
        ts_signature: "toLocaleUpperCase(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLowerCase",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_LOWER_CASE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.toLowerCase().",
        ts_signature: "toLowerCase(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toLocaleLowerCase",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_LOWER_CASE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.toLocaleLowerCase() — alias for toLowerCase.",
        ts_signature: "toLocaleLowerCase(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trim",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TRIM",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.trim().",
        ts_signature: "trim(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trimStart",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TRIM_START",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.trimStart().",
        ts_signature: "trimStart(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trimLeft",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TRIM_START",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.trimLeft() — alias for trimStart.",
        ts_signature: "trimLeft(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trimEnd",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TRIM_END",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.trimEnd().",
        ts_signature: "trimEnd(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "trimRight",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TRIM_END",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.trimRight() — alias for trimEnd.",
        ts_signature: "trimRight(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "repeat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_REPEAT",
        args: &[AbiType::Handle, AbiType::I64],
        returns: AbiType::Handle,
        doc: "str.repeat(n).",
        ts_signature: "repeat(n: number): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "replace",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_REPLACE",
        args: &[AbiType::Handle, AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.replace(from, to) — replace first occurrence.",
        ts_signature: "replace(from: string, to: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "replaceAll",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_REPLACE_ALL",
        args: &[AbiType::Handle, AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.replaceAll(from, to) — replace all occurrences.",
        ts_signature: "replaceAll(from: string, to: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "concat",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_CONCAT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.concat(other) — concatenate two strings.",
        ts_signature: "concat(other: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "padStart",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_PAD_START",
        args: &[AbiType::Handle, AbiType::I64, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.padStart(targetLength, padString).",
        ts_signature: "padStart(targetLength: number, padString?: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "padEnd",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_PAD_END",
        args: &[AbiType::Handle, AbiType::I64, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.padEnd(targetLength, padString).",
        ts_signature: "padEnd(targetLength: number, padString?: string): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "split",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_SPLIT",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.split(sep) — Vec handle of string handles.",
        ts_signature: "split(sep: string): string[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "localeCompare",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_LOCALE_COMPARE",
        args: &[AbiType::Handle, AbiType::Handle],
        returns: AbiType::I64,
        doc: "str.localeCompare(other) — -1 / 0 / 1.",
        ts_signature: "localeCompare(other: string): number",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.toString() — identity.",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "valueOf",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_BOX_VALUE_OF",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.valueOf() — identity para string primitive, unwrap para StringBox.",
        ts_signature: "valueOf(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "isWellFormed",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_IS_WELL_FORMED",
        args: &[AbiType::Handle],
        returns: AbiType::Bool,
        doc: "str.isWellFormed() — always true for RTS UTF-8 strings.",
        ts_signature: "isWellFormed(): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toWellFormed",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_WELL_FORMED",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.toWellFormed() — substitui lone surrogates por U+FFFD.",
        ts_signature: "toWellFormed(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "normalize",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_STRING_TO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "str.normalize() — stub: identity (full NFC/NFD is a follow-up).",
        ts_signature: "normalize(form?: string): string",
        intrinsic: None,
        pure: true,
    },
];

pub const STRING_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "String",
    doc: "JS String primitive class — new String(), String.fromCharCode(), str.slice() etc.",
    members: STRING_CLASS_MEMBERS,
};
