//! `collections` namespace — ABI registration.

use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    // ── Map ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "map_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Creates an empty HashMap<string, number> and returns its handle.",
        ts_signature: "map_new(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_FREE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Releases the map handle.",
        ts_signature: "map_free(h: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_LEN",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Number of entries; -1 if the handle is invalid.",
        ts_signature: "map_len(h: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_has",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_HAS",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True when the map contains `key`.",
        ts_signature: "map_has(h: number, key: string): boolean",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_get",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_GET",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Value for `key`, or 0 when absent. Use map_has to distinguish.",
        ts_signature: "map_get(h: number, key: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_set",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_SET",
        args: &[AbiType::U64, AbiType::StrPtr, AbiType::I64],
        returns: AbiType::Void,
        doc: "Inserts/overwrites `key` with `value`.",
        ts_signature: "map_set(h: number, key: string, value: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_delete",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_DELETE",
        args: &[AbiType::U64, AbiType::StrPtr],
        returns: AbiType::I64,
        doc: "Removes `key`. Returns 1 if removed, 0 if absent.",
        ts_signature: "map_delete(h: number, key: string): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_clear",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_CLEAR",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Removes all entries.",
        ts_signature: "map_clear(h: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_key_at",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_KEY_AT",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Handle,
        doc: "Returns the key at index in deterministic order (sorted). 0 if out of range.",
        ts_signature: "map_key_at(h: number, idx: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_keys",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_KEYS",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Returns Vec<i64> with key handles (sorted asc). Used by Object.keys.",
        ts_signature: "map_keys(h: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "map_values",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_MAP_VALUES",
        args: &[AbiType::U64],
        returns: AbiType::Handle,
        doc: "Returns Vec<i64> with values (in key-sorted order). Used by Object.values.",
        ts_signature: "map_values(h: number): number",
        intrinsic: None,
        pure: false,
    },
    // ── Vec ───────────────────────────────────────────────────────────
    NamespaceMember {
        name: "vec_new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "Creates an empty Vec<number>.",
        ts_signature: "vec_new(): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_FREE",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Releases the vec handle.",
        ts_signature: "vec_free(h: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_len",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_LEN",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Number of elements; -1 if the handle is invalid.",
        ts_signature: "vec_len(h: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_push",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_PUSH",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Appends `value` to the end.",
        ts_signature: "vec_push(h: number, value: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_pop",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_POP",
        args: &[AbiType::U64],
        returns: AbiType::I64,
        doc: "Removes and returns the last element; 0 when empty.",
        ts_signature: "vec_pop(h: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_get",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_GET",
        args: &[AbiType::U64, AbiType::I64],
        returns: AbiType::I64,
        doc: "Element at `index`, or 0 out of range.",
        ts_signature: "vec_get(h: number, index: number): number",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_set",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_SET",
        args: &[AbiType::U64, AbiType::I64, AbiType::I64],
        returns: AbiType::Void,
        doc: "Writes `value` at `index`. No-op out of range.",
        ts_signature: "vec_set(h: number, index: number, value: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_clear",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_CLEAR",
        args: &[AbiType::U64],
        returns: AbiType::Void,
        doc: "Removes all elements.",
        ts_signature: "vec_clear(h: number): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "vec_join",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_NS_COLLECTIONS_VEC_JOIN",
        args: &[AbiType::U64, AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Junta os elementos do vec separados por `sep` (string handle). Cada elemento i64 e' tratado como string handle se valido, senao formatado como numero decimal. Retorna handle da string resultante.",
        ts_signature: "vec_join(h: number, sep: number): number",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "collections",
    doc: "Handle-based HashMap and Vec backed by std::collections.",
    members: MEMBERS,
};
