use crate::abi::{AbiType, MemberKind, NamespaceMember, NamespaceSpec};

pub const MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_NEW",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Parse URL string. Retorna URL handle ou 0 em caso de URL inválida.",
        ts_signature: "new URL(url: string): URL",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "href",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_HREF",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "URL completa serializada.",
        ts_signature: "href(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "protocol",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_PROTOCOL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Scheme com dois-pontos: 'https:'.",
        ts_signature: "protocol(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "host",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_HOST",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "host:port (ou só host se porta padrão).",
        ts_signature: "host(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hostname",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_HOSTNAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Hostname sem porta.",
        ts_signature: "hostname(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "port",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_PORT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Porta como string (vazio se padrão).",
        ts_signature: "port(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "pathname",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_PATHNAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Path da URL: '/foo/bar'.",
        ts_signature: "pathname(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "search",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_SEARCH",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Query string com '?': '?a=1&b=2' (vazio se ausente).",
        ts_signature: "search(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hash",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_HASH",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Fragment com '#': '#section' (vazio se ausente).",
        ts_signature: "hash(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "origin",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_ORIGIN",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "'scheme://host:port' — origem da URL.",
        ts_signature: "origin(url: URL): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "free",
        kind: MemberKind::Function,
        symbol: "__RTS_FN_GL_URL_FREE",
        args: &[AbiType::Handle],
        returns: AbiType::Void,
        doc: "Libera URL handle.",
        ts_signature: "free(url: URL): void",
        intrinsic: None,
        pure: false,
    },
];

pub const SPEC: NamespaceSpec = NamespaceSpec {
    name: "url",
    doc: "URL parser: new/href/protocol/host/hostname/port/pathname/search/hash/origin/free.",
    members: MEMBERS,
};
