use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const URL_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_URL_NEW",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "new URL(url) — parse URL. Retorna URL handle ou 0 se inválida.",
        ts_signature: "new URL(url: string): URL",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "href",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HREF",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.href — URL completa serializada.",
        ts_signature: "readonly href: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "protocol",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_PROTOCOL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.protocol — scheme com dois-pontos.",
        ts_signature: "readonly protocol: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "host",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HOST",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.host — host:port.",
        ts_signature: "readonly host: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hostname",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HOSTNAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.hostname — hostname sem porta.",
        ts_signature: "readonly hostname: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "port",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_PORT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.port — porta como string (vazio se padrão).",
        ts_signature: "readonly port: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "pathname",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_PATHNAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.pathname — path: '/foo/bar'.",
        ts_signature: "readonly pathname: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "search",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_SEARCH",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.search — query string com '?'.",
        ts_signature: "readonly search: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hash",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HASH",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.hash — fragment com '#'.",
        ts_signature: "readonly hash: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "origin",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_ORIGIN",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.origin — 'scheme://host:port'.",
        ts_signature: "readonly origin: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HREF",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.toString() — alias de href.",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    // (#373) url.searchParams — constroi URLSearchParams a partir de search.
    NamespaceMember {
        name: "searchParams",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_SEARCH_PARAMS",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.searchParams — URLSearchParams parseada do search query.",
        ts_signature: "readonly searchParams: URLSearchParams",
        intrinsic: None,
        pure: false,
    },
];

pub const URL_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "URL",
    doc: "WHATWG URL API — new URL(href)/href/protocol/host/hostname/port/pathname/search/hash/origin.",
    members: URL_MEMBERS,
};

// (#373) URLSearchParams — minimal: get/has/set/delete/toString.
pub const URLSP_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_USP_NEW",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "new URLSearchParams(init?) — init e' string \"a=1&b=2\".",
        ts_signature: "new URLSearchParams(init?: string): URLSearchParams",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "get",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_GET",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Retorna handle de string com value, ou 0 (undefined) se ausente.",
        ts_signature: "get(key: string): string | null",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "has",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_HAS",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "True se key existe.",
        ts_signature: "has(key: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "set",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_SET",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Substitui ou adiciona pair. Retorna self.",
        ts_signature: "set(key: string, value: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "delete",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_DELETE",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Remove pair. Retorna self.",
        ts_signature: "delete(key: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_TO_STRING",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Serializa como 'a=1&b=2'.",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "append",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_APPEND",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Append (v0 limitacao: equivalente a set — sem multi-value).",
        ts_signature: "append(key: string, value: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "getAll",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_GET_ALL",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "Vec com 0 ou 1 elemento (v0 sem multi-value).",
        ts_signature: "getAll(key: string): string[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "keys",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_KEYS",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Vec de string handles com as keys.",
        ts_signature: "keys(): string[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "values",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_USP_VALUES",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "Vec de string handles com os values.",
        ts_signature: "values(): string[]",
        intrinsic: None,
        pure: true,
    },
];

pub const URLSP_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "URLSearchParams",
    doc: "WHATWG URLSearchParams API minimal — get/has/set/delete/toString.",
    members: URLSP_MEMBERS,
};
