use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const URL_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_URL_NEW",
        args: &[AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "new URL(url) — parse URL. Retorna URL handle ou 0 se inválida.",
        ts_signature: "new URL(url: string): URL",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "href",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HREF",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.href — URL completa serializada.",
        ts_signature: "readonly href: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "protocol",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_PROTOCOL",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.protocol — scheme com dois-pontos.",
        ts_signature: "readonly protocol: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "host",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HOST",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.host — host:port.",
        ts_signature: "readonly host: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hostname",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HOSTNAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.hostname — hostname sem porta.",
        ts_signature: "readonly hostname: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "port",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_PORT",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.port — porta como string (vazio se padrão).",
        ts_signature: "readonly port: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "pathname",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_PATHNAME",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.pathname — path: '/foo/bar'.",
        ts_signature: "readonly pathname: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "search",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_SEARCH",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.search — query string com '?'.",
        ts_signature: "readonly search: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "hash",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HASH",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.hash — fragment com '#'.",
        ts_signature: "readonly hash: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "origin",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_ORIGIN",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.origin — 'scheme://host:port'.",
        ts_signature: "readonly origin: string",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "toString",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_URL_HREF",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "url.toString() — alias de href.",
        ts_signature: "toString(): string",
        intrinsic: None,
        pure: true,
    },
];

pub const URL_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "URL",
    doc: "WHATWG URL API — new URL(href)/href/protocol/host/hostname/port/pathname/search/hash/origin.",
    members: URL_MEMBERS,
};
