use crate::abi::{AbiType, GlobalClassSpec, MemberKind, NamespaceMember};

pub const HEADERS_MEMBERS: &[NamespaceMember] = &[
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_HEADERS_NEW",
        args: &[],
        returns: AbiType::Handle,
        doc: "new Headers() — vazio.",
        ts_signature: "new Headers()",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "new",
        kind: MemberKind::Constructor,
        symbol: "__RTS_FN_GL_HEADERS_NEW_FROM",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "new Headers(init) — init eh array de pares [name, value].",
        ts_signature: "new Headers(init: [string, string][])",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "append",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_APPEND",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "headers.append(name, value)",
        ts_signature: "append(name: string, value: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "set",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_SET",
        args: &[AbiType::Handle, AbiType::StrPtr, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "headers.set(name, value) — substitui todos valores.",
        ts_signature: "set(name: string, value: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "get",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_GET",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Handle,
        doc: "headers.get(name) — junta com ', '.",
        ts_signature: "get(name: string): string | null",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "has",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_HAS",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Bool,
        doc: "headers.has(name)",
        ts_signature: "has(name: string): boolean",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "delete",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_DELETE",
        args: &[AbiType::Handle, AbiType::StrPtr],
        returns: AbiType::Void,
        doc: "headers.delete(name)",
        ts_signature: "delete(name: string): void",
        intrinsic: None,
        pure: false,
    },
    NamespaceMember {
        name: "getSetCookie",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_GET_SET_COOKIE",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "headers.getSetCookie() — Array<string> dos set-cookie sem juntar.",
        ts_signature: "getSetCookie(): string[]",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "entries",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_ENTRIES",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "headers.entries() — iterable [name, value].",
        ts_signature: "entries(): IterableIterator<[string, string]>",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "keys",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_KEYS",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "headers.keys()",
        ts_signature: "keys(): IterableIterator<string>",
        intrinsic: None,
        pure: true,
    },
    NamespaceMember {
        name: "values",
        kind: MemberKind::InstanceMethod,
        symbol: "__RTS_FN_GL_HEADERS_VALUES",
        args: &[AbiType::Handle],
        returns: AbiType::Handle,
        doc: "headers.values()",
        ts_signature: "values(): IterableIterator<string>",
        intrinsic: None,
        pure: true,
    },
];

pub const HEADERS_CLASS_SPEC: GlobalClassSpec = GlobalClassSpec {
    name: "Headers",
    doc: "Headers — multimap case-insensitive de HTTP headers.",
    members: HEADERS_MEMBERS,
};
