//! `os.constants.errno` — POSIX `E*` numbers (from `libc`, real per-target) plus
//! the Windows `WSA*` family on `win32`. Fixed `<errno.h>`/`<winsock2.h>` values
//! on Windows. Absent codes are omitted.

/// `(name, number)` pairs for every errno present on the compiled platform.
pub fn entries() -> Vec<(&'static str, i64)> {
    #[cfg(unix)]
    {
        unix_entries()
    }
    #[cfg(windows)]
    {
        windows_entries()
    }
    #[cfg(not(any(unix, windows)))]
    {
        Vec::new()
    }
}

#[cfg(unix)]
fn unix_entries() -> Vec<(&'static str, i64)> {
    let mut v: Vec<(&'static str, i64)> = vec![
        ("E2BIG", libc::E2BIG as i64),
        ("EACCES", libc::EACCES as i64),
        ("EADDRINUSE", libc::EADDRINUSE as i64),
        ("EADDRNOTAVAIL", libc::EADDRNOTAVAIL as i64),
        ("EAFNOSUPPORT", libc::EAFNOSUPPORT as i64),
        ("EAGAIN", libc::EAGAIN as i64),
        ("EALREADY", libc::EALREADY as i64),
        ("EBADF", libc::EBADF as i64),
        ("EBADMSG", libc::EBADMSG as i64),
        ("EBUSY", libc::EBUSY as i64),
        ("ECANCELED", libc::ECANCELED as i64),
        ("ECHILD", libc::ECHILD as i64),
        ("ECONNABORTED", libc::ECONNABORTED as i64),
        ("ECONNREFUSED", libc::ECONNREFUSED as i64),
        ("ECONNRESET", libc::ECONNRESET as i64),
        ("EDEADLK", libc::EDEADLK as i64),
        ("EDESTADDRREQ", libc::EDESTADDRREQ as i64),
        ("EDOM", libc::EDOM as i64),
        ("EDQUOT", libc::EDQUOT as i64),
        ("EEXIST", libc::EEXIST as i64),
        ("EFAULT", libc::EFAULT as i64),
        ("EFBIG", libc::EFBIG as i64),
        ("EHOSTUNREACH", libc::EHOSTUNREACH as i64),
        ("EIDRM", libc::EIDRM as i64),
        ("EILSEQ", libc::EILSEQ as i64),
        ("EINPROGRESS", libc::EINPROGRESS as i64),
        ("EINTR", libc::EINTR as i64),
        ("EINVAL", libc::EINVAL as i64),
        ("EIO", libc::EIO as i64),
        ("EISCONN", libc::EISCONN as i64),
        ("EISDIR", libc::EISDIR as i64),
        ("ELOOP", libc::ELOOP as i64),
        ("EMFILE", libc::EMFILE as i64),
        ("EMLINK", libc::EMLINK as i64),
        ("EMSGSIZE", libc::EMSGSIZE as i64),
        ("ENAMETOOLONG", libc::ENAMETOOLONG as i64),
        ("ENETDOWN", libc::ENETDOWN as i64),
        ("ENETRESET", libc::ENETRESET as i64),
        ("ENETUNREACH", libc::ENETUNREACH as i64),
        ("ENFILE", libc::ENFILE as i64),
        ("ENOBUFS", libc::ENOBUFS as i64),
        ("ENODEV", libc::ENODEV as i64),
        ("ENOENT", libc::ENOENT as i64),
        ("ENOEXEC", libc::ENOEXEC as i64),
        ("ENOLCK", libc::ENOLCK as i64),
        ("ENOMEM", libc::ENOMEM as i64),
        ("ENOMSG", libc::ENOMSG as i64),
        ("ENOPROTOOPT", libc::ENOPROTOOPT as i64),
        ("ENOSPC", libc::ENOSPC as i64),
        ("ENOSYS", libc::ENOSYS as i64),
        ("ENOTCONN", libc::ENOTCONN as i64),
        ("ENOTDIR", libc::ENOTDIR as i64),
        ("ENOTEMPTY", libc::ENOTEMPTY as i64),
        ("ENOTSOCK", libc::ENOTSOCK as i64),
        ("ENOTSUP", libc::ENOTSUP as i64),
        ("ENOTTY", libc::ENOTTY as i64),
        ("ENXIO", libc::ENXIO as i64),
        ("EOPNOTSUPP", libc::EOPNOTSUPP as i64),
        ("EOVERFLOW", libc::EOVERFLOW as i64),
        ("EPERM", libc::EPERM as i64),
        ("EPIPE", libc::EPIPE as i64),
        ("EPROTO", libc::EPROTO as i64),
        ("EPROTONOSUPPORT", libc::EPROTONOSUPPORT as i64),
        ("EPROTOTYPE", libc::EPROTOTYPE as i64),
        ("ERANGE", libc::ERANGE as i64),
        ("EROFS", libc::EROFS as i64),
        ("ESPIPE", libc::ESPIPE as i64),
        ("ESRCH", libc::ESRCH as i64),
        ("ESTALE", libc::ESTALE as i64),
        ("ETIMEDOUT", libc::ETIMEDOUT as i64),
        ("ETXTBSY", libc::ETXTBSY as i64),
        ("EWOULDBLOCK", libc::EWOULDBLOCK as i64),
        ("EXDEV", libc::EXDEV as i64),
    ];
    // STREAMS/XSI codes — present on Linux; omitted elsewhere (Node omits absent).
    #[cfg(target_os = "linux")]
    {
        v.push(("EMULTIHOP", libc::EMULTIHOP as i64));
        v.push(("ENODATA", libc::ENODATA as i64));
        v.push(("ENOLINK", libc::ENOLINK as i64));
        v.push(("ENOSR", libc::ENOSR as i64));
        v.push(("ENOSTR", libc::ENOSTR as i64));
        v.push(("ETIME", libc::ETIME as i64));
    }
    v
}

#[cfg(windows)]
fn windows_entries() -> Vec<(&'static str, i64)> {
    // POSIX subset — MSVC <errno.h> values.
    let mut v: Vec<(&'static str, i64)> = vec![
        ("E2BIG", 7),
        ("EACCES", 13),
        ("EADDRINUSE", 100),
        ("EADDRNOTAVAIL", 101),
        ("EAFNOSUPPORT", 102),
        ("EAGAIN", 11),
        ("EALREADY", 103),
        ("EBADF", 9),
        ("EBADMSG", 104),
        ("EBUSY", 16),
        ("ECANCELED", 105),
        ("ECHILD", 10),
        ("ECONNABORTED", 106),
        ("ECONNREFUSED", 107),
        ("ECONNRESET", 108),
        ("EDEADLK", 36),
        ("EDESTADDRREQ", 109),
        ("EDOM", 33),
        ("EEXIST", 17),
        ("EFAULT", 14),
        ("EFBIG", 27),
        ("EHOSTUNREACH", 110),
        ("EIDRM", 111),
        ("EILSEQ", 42),
        ("EINPROGRESS", 112),
        ("EINTR", 4),
        ("EINVAL", 22),
        ("EIO", 5),
        ("EISCONN", 113),
        ("EISDIR", 21),
        ("ELOOP", 114),
        ("EMFILE", 24),
        ("EMLINK", 31),
        ("EMSGSIZE", 115),
        ("ENAMETOOLONG", 38),
        ("ENETDOWN", 116),
        ("ENETRESET", 117),
        ("ENETUNREACH", 118),
        ("ENFILE", 23),
        ("ENOBUFS", 119),
        ("ENODATA", 120),
        ("ENODEV", 19),
        ("ENOENT", 2),
        ("ENOEXEC", 8),
        ("ENOLCK", 39),
        ("ENOLINK", 121),
        ("ENOMEM", 12),
        ("ENOMSG", 122),
        ("ENOPROTOOPT", 123),
        ("ENOSPC", 28),
        ("ENOSR", 124),
        ("ENOSTR", 125),
        ("ENOSYS", 40),
        ("ENOTCONN", 126),
        ("ENOTDIR", 20),
        ("ENOTEMPTY", 41),
        ("ENOTRECOVERABLE", 127),
        ("ENOTSOCK", 128),
        ("ENOTSUP", 129),
        ("ENOTTY", 25),
        ("ENXIO", 6),
        ("EOPNOTSUPP", 130),
        ("EOVERFLOW", 132),
        ("EOWNERDEAD", 133),
        ("EPERM", 1),
        ("EPIPE", 32),
        ("EPROTO", 134),
        ("EPROTONOSUPPORT", 135),
        ("EPROTOTYPE", 136),
        ("ERANGE", 34),
        ("EROFS", 30),
        ("ESPIPE", 29),
        ("ESRCH", 3),
        ("ETIME", 137),
        ("ETIMEDOUT", 138),
        ("ETXTBSY", 139),
        ("EWOULDBLOCK", 140),
        ("EXDEV", 18),
    ];
    // Winsock (WSA*) family — <winsock2.h>, WSABASEERR = 10000.
    v.extend_from_slice(&[
        ("WSAEINTR", 10004),
        ("WSAEBADF", 10009),
        ("WSAEACCES", 10013),
        ("WSAEFAULT", 10014),
        ("WSAEINVAL", 10022),
        ("WSAEMFILE", 10024),
        ("WSAEWOULDBLOCK", 10035),
        ("WSAEINPROGRESS", 10036),
        ("WSAEALREADY", 10037),
        ("WSAENOTSOCK", 10038),
        ("WSAEDESTADDRREQ", 10039),
        ("WSAEMSGSIZE", 10040),
        ("WSAEPROTOTYPE", 10041),
        ("WSAENOPROTOOPT", 10042),
        ("WSAEPROTONOSUPPORT", 10043),
        ("WSAESOCKTNOSUPPORT", 10044),
        ("WSAEOPNOTSUPP", 10045),
        ("WSAEPFNOSUPPORT", 10046),
        ("WSAEAFNOSUPPORT", 10047),
        ("WSAEADDRINUSE", 10048),
        ("WSAEADDRNOTAVAIL", 10049),
        ("WSAENETDOWN", 10050),
        ("WSAENETUNREACH", 10051),
        ("WSAENETRESET", 10052),
        ("WSAECONNABORTED", 10053),
        ("WSAECONNRESET", 10054),
        ("WSAENOBUFS", 10055),
        ("WSAEISCONN", 10056),
        ("WSAENOTCONN", 10057),
        ("WSAESHUTDOWN", 10058),
        ("WSAETOOMANYREFS", 10059),
        ("WSAETIMEDOUT", 10060),
        ("WSAECONNREFUSED", 10061),
        ("WSAELOOP", 10062),
        ("WSAENAMETOOLONG", 10063),
        ("WSAEHOSTDOWN", 10064),
        ("WSAEHOSTUNREACH", 10065),
        ("WSAENOTEMPTY", 10066),
        ("WSAEPROCLIM", 10067),
        ("WSAEUSERS", 10068),
        ("WSAEDQUOT", 10069),
        ("WSAESTALE", 10070),
        ("WSAEREMOTE", 10071),
        ("WSASYSNOTREADY", 10091),
        ("WSAVERNOTSUPPORTED", 10092),
        ("WSANOTINITIALISED", 10093),
        ("WSAEDISCON", 10101),
        ("WSAENOMORE", 10102),
        ("WSAECANCELLED", 10103),
        ("WSAEINVALIDPROCTABLE", 10104),
        ("WSAEINVALIDPROVIDER", 10105),
        ("WSAEPROVIDERFAILEDINIT", 10106),
        ("WSASYSCALLFAILURE", 10107),
        ("WSASERVICE_NOT_FOUND", 10108),
        ("WSATYPE_NOT_FOUND", 10109),
        ("WSA_E_NO_MORE", 10110),
        ("WSA_E_CANCELLED", 10111),
        ("WSAEREFUSED", 10112),
    ]);
    v
}
